### **Подключение модулей**

In [1]:
from system_check import *
CUDA_state_print()

CUDA доступна: True
Количество GPU: 4

GPU #0:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #1:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #2:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #3:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

In [2]:
import sys
sys.path.append("/global_functions")
from global_functions.global_functions import *

------------------------------------
---> Choosing resource
---> Result of torch.cuda.is_available():
True
---> Final resource
-----> CUDA: 1
-----> device: cuda:1
------------------------------------

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
loading file vocab.txt
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file tokenizer.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/model.safetensors
All model checkpoint weights were used when initializing BertModel.

All the weights of BertModel were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_model/config.json
Model config BertConfig {
  "architectures": [
    "BertForQuestionAnswering"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_model/model.safetensors
All model checkpoint weights were used when initializing BertForQuestionAnswering.

All the weights of BertForQuestionAnswering were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertForQuestionAnswering for predictions without further training.

### **Подключение датасета**

In [3]:
name = "scirex_structured.json"
datasets_path = "../datasets"

df_loaded = load_dataframe_from_json(f"{datasets_path}/{name}")
df_loaded

,doc_id,methods,tasks,metrics,materials,score,original_text
0,000f90380d768a85e2316225854fc377c079b5c4,[FRRN],"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Frame__fps_, Mean_IoU, mIoU, Time__ms_]",[Cityscapes],"[2.1, 71.8%, 469]",Full - Resolution Residual Networks for Semant...
1,0012de6bec1f25599e4f02517637e531a71909b9,[V-Net___Dice-based_loss],[Volumetric_Medical_Image_Segmentation],[Dice_Score],[PROMISE_2012],[0.869],document: V - Net: Fully Convolutional Neural ...
2,007ab5528b3bd310a80d553cccad4b78dc496b02,"[BiDAF__single_model_, BiDAF, BiDAF__ensemble_...","[Question_Answering, Open-Domain_Question_Answ...","[METEOR, EM__Quasar-T_, F1__Quasar-T_, F1, EM,...","[NarrativeQA, MS_MARCO, SQuAD1_1, CNN___Daily_...","[33.45, 23.96, 15.69, 25.9, 79.6, 36.74, 76.9,...",document: Bi - Directional Attention Flow for ...
3,0095c269e7d0c990249312687fc43521019809c4,[50D_stacked_TC-LSTMs],[Natural_Language_Inference],"[Parameters, __Train_Accuracy, __Test_Accuracy]",[SNLI],"[190k, 86.7, 85.1]",document: Modelling Interaction of Sentence Pa...
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,"[AlphaZero, AlphaGo_Zero]","[Game_of_Go, Game_of_Shogi]",[ELO_Rating],[ELO_Ratings],"[4650, 5185]",document: Mastering Chess and Shogi by Self - ...
...,...,...,...,...,...,...,...
301,45b559e6271570598602fcf9777ed6f2f2d133e6,[Deep_CNN__10_conv__4_FC_layers___multi-scale_...,[Speech_Recognition],[Percentage_error],[Switchboard___Hub500],[],document: Very Deep Multilingual Convolutional...
302,45e8ef229fae18b0a2ab328037d8e520866c3c81,[Pyramid_Residual_Modules__PRMs_],[Pose_Estimation],"[PCKh-0_5, PCK]","[Leeds_Sports_Poses, MPII_Human_Pose]","[93.9%, 92.0%]",document: Learning Feature Pyramids for Human ...
303,45fdc73a239e9c6ea65e98c96f6a2d6dc35d6f72,[QCNN-10L-256FM],[Speech_Recognition],[Percentage_error],[TIMIT],[19.64],document: Quaternion Convolutional Neural Netw...
304,46018a894d533813d67322827ca51f78aed6d59e,[InputCascadeCNN],[Brain_Tumor_Segmentation],[Dice_Score],[BRATS-2013],[0.88],document: Brain Tumor Segmentation with Deep N...
305,462d4e265c9cbe9ad5feeb9a7736184a90b36fed,"[CRF___AutoEncoder, Neural-CRF_AE]",[Named_Entity_Recognition__NER_],[F1],[CoNLL_2003__English_],"[92.29, 91.87]",document: Evaluating the Utility of Hand - cra...

In [4]:
df_loaded = replace_underscores_in_array_column(df=df_loaded,
                                        column_name="tasks")
df_loaded.head()

,doc_id,methods,tasks,metrics,materials,score,original_text,tasks_cleaned
0,000f90380d768a85e2316225854fc377c079b5c4,[FRRN],"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Frame__fps_, Mean_IoU, mIoU, Time__ms_]",[Cityscapes],"[2.1, 71.8%, 469]",Full - Resolution Residual Networks for Semant...,"[Semantic Segmentation, Real-Time Semantic Seg..."
1,0012de6bec1f25599e4f02517637e531a71909b9,[V-Net___Dice-based_loss],[Volumetric_Medical_Image_Segmentation],[Dice_Score],[PROMISE_2012],[0.869],document: V - Net: Fully Convolutional Neural ...,[Volumetric Medical Image Segmentation]
2,007ab5528b3bd310a80d553cccad4b78dc496b02,"[BiDAF__single_model_, BiDAF, BiDAF__ensemble_...","[Question_Answering, Open-Domain_Question_Answ...","[METEOR, EM__Quasar-T_, F1__Quasar-T_, F1, EM,...","[NarrativeQA, MS_MARCO, SQuAD1_1, CNN___Daily_...","[33.45, 23.96, 15.69, 25.9, 79.6, 36.74, 76.9,...",document: Bi - Directional Attention Flow for ...,"[Question Answering, Open-Domain Question Answ..."
3,0095c269e7d0c990249312687fc43521019809c4,[50D_stacked_TC-LSTMs],[Natural_Language_Inference],"[Parameters, __Train_Accuracy, __Test_Accuracy]",[SNLI],"[190k, 86.7, 85.1]",document: Modelling Interaction of Sentence Pa...,[Natural Language Inference]
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,"[AlphaZero, AlphaGo_Zero]","[Game_of_Go, Game_of_Shogi]",[ELO_Rating],[ELO_Ratings],"[4650, 5185]",document: Mastering Chess and Shogi by Self - ...,"[Game of Go, Game of Shogi]"

In [5]:
df_loaded['first_answer'] = None
df_loaded['corrected_answer'] = None
df_loaded['keywords'] = None
df_loaded['metrics'] = None

# Оставляем только нужные колонки и новые колонки
columns_to_keep = ['doc_id', 'original_text', 'tasks', 'tasks_cleaned', 
                    'first_answer', 'corrected_answer', 'keywords', 'metrics']
df_loaded = df_loaded[columns_to_keep]

df_loaded.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",None,None,None,None
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],None,None,None,None
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",None,None,None,None
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],None,None,None,None
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",None,None,None,None

In [6]:
datasets_results_path = "../datasets_results"
res_name = "results.json"

save_dataframe_to_json(df=df_loaded, 
                    file_path=f"{datasets_results_path}/{res_name}")

The dataset was successfully saved to datasets_results/results.json

### **Первичная обработка**

### Загрузка настроечных параметров

In [7]:
model_name = "scart_init_model.json"
model_params_path = "../model_params"

df_model_params = pd.read_json(f"{model_params_path}/{model_name}")

df_model_params

,model_name,description,fields
0,ScArt Model,Модель для обработки научных статей на английс...,"{'field_id': 1, 'field_name': 'task', 'field_t..."

In [8]:
field_name = df_model_params["fields"][0]["field_name"]
questions = df_model_params["fields"][0]["questions"]
keywords = df_model_params["fields"][0]["keywords"]
text = df_model_params["fields"][0]["text"]

In [9]:
them_aspect = ThematicAspect(field_name, convert_into_question_class(questions))

In [10]:
filtering_set = FilteringSet(text, keywords)

### **Обработка**

In [11]:
num_of_sample = 0

In [12]:
text_of_doc = df_loaded["original_text"][num_of_sample]
text_of_doc

"Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible?), they lack localization accuracy (i.e., where precisely is something located?). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71.8% on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams. One stream undergoes a sequence of pooling operations and is responsible for understanding large - scale relationships of image elements; the other stream carries feature maps at the full image resolution, resulting in precise boundary adherence. This idea is visualized in Figure 1, where the two processing streams are shown in blue and red. The blue residual lane reflects the high - resolution stream. It can be combined with classical residual units (left and right), as well as with our new full - resolution residual units (FRRU). The FRRUs from the red pooling lane act as residual units for the blue stream, but also undergo pooling operations and carry high - level information through the network. This results in a network that successively combines and computes features at two resolutions. This paper makes the following contributions: (i) We propose a novel network architecture geared towards precise semantic segmentation in street scenes which is not limited to pre - trained architectures and achieves state - ofthe - art results. (ii) We propose to use two processing streams to realize strong recognition and strong localization performance: One stream undergoes a sequence of pooling operations while the other stream stays at the full image resolution. (iii) In order to foster further research in this area, we publish our code and the trained models in Theano / Lasagne [reference ][ reference] 1. 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference]. In theory, however, the training loss of a shallow network should be an upper bound on the training loss of a corresponding deep network. This is due to the fact that increasing the depth by adding layers strictly increases the expressive power of the model. A deep network can express all functions that the original shallow network can express by using identity mappings for the added layers. Hence a deep network should perform at least as well as the shallower model on the training data. The violation of this principle implied that current training algorithms have difficulties optimizing very deep traditional feedforward networks. He et al. proposed residual networks (ResNets) that exhibit significantly improved training characteristics, allowing network depths that were previously unattainable. A ResNet is composed of a sequence of residual units (RUs). As depicted in Figure 2b, the output x n of the n - th RU in a ResNet is computed as where F (x n−1; W n) is the residual, which is parametrized by W n. Thus, instead of computing the output x n directly, F only computes a residual that is added to the input x n−1. One commonly refers to this design as skip connection, because there is a connection from the input x n−1 to the output x n that skips the actual computation F. It has been empirically observed that ResNets have superior training properties over traditional feedforward networks. This can be explained by an improved gradient flow within the network. In oder to understand this, consider the n - th and m - th residual units in a ResNet where m > n (i.e., the m - th unit is closer to the output layer of the network). By applying the recursion (2) several times, He et al. showed in [reference] that the output of the m - th residual unit admits a representation of the form Furthermore, if l is the loss that is used to train the network, we can use the chain rule of calculus and express the derivative of the loss l with respect to the output x n of the n - th RU as Thus, we find We see that the weight updates depend on two sources of information,. While the amount of information that is contained in the latter may depend crucially on the depth n, the former allows a gradient flow that is independent of the depth. Hence, gradients can flow unhindered from the deeper unit to the shallower unit. This makes training even extremely deep ResNets possible. section: Full - Resolution Residual Networks (FRRNs). In this paper, we unify the two above - mentioned principles of network design and propose full - resolution residual networks (FRRNs) that exhibit the same superior training properties as ResNets but have two processing streams. The features on one stream, the residual stream, are computed by adding successive residuals, while the features on the other stream, the pooling stream, are the direct result of a sequence of convolution and pooling operations applied to the input. Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively. If G ≡ 0, then an FRRU corresponds to an RU since it disregards the pooling input y n, and the network effectively becomes an ordinary ResNet. On the other hand, if H ≡ 0, then the output of an FRRU only depends on its input via the function G. Hence, no residuals are computed and we obtain a traditional feedforward network. By carefully constructing G and H, we can combine the two network principles. In order to show that FRRNs have similar training characteristics as ResNets, we adapt the analysis presented in [reference] to our case. Using the same recursive argument as before, we find that for m > n, z m has the representation We can then express the derivative of the loss l with respect to the weights W n as Hence, the weight updates depend on three sources of information. Analogous to the analysis of ResNets, the two sources ∂H (yi, zi;Wi + 1) ∂zn depend crucially on the depth n, while the term ∂l ∂zm is independent of the depth. Thus, we achieve a depth - independent gradient flow for all parameters that are used by the residual function H. If we use some of these weights in order to compute the output of G, all weights of the unit benefit from the improved gradient flow. This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation perfo

In [13]:
reference_answers = df_loaded["tasks_cleaned"][num_of_sample]
reference_answers

['Semantic Segmentation', 'Real-Time Semantic Segmentation']

In [14]:
res1 = extract_short_answer(text=text_of_doc,
                them_asp=them_aspect, 
                filter_mode=FilterMode.NO_FILTER,
                filter_set=filtering_set,
                agg_mode=AggMode.NO_AGG)
res1

---> Number of sentences:
--> 276

Device set to use cuda:1
Disabling tokenizer parallelism, we're using DataLoader multithreading already

---
---> Number of chunks:
--> 22

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

---
---> Founded answers:
----->1/1
----->Which task was solved?
obtain pixel - accurate segmentations.
0.36837196350097656
understanding large - scale relationships of image elements;
0.33733153343200684
deviation of U from 0. 5
0.2780102789402008
find the correct sidewalk boundary,
0.201487734913826
Semantic image segmentation
0.1799963414669037
F only computes a residual that is added to the input x n−1.
0.15894180536270142
bootstrapped cross - entropy loss
0.09279076009988785
Semantic image segmentation
0.0805731937289238
classification,
0.06699735671281815
upscale the spatial dimensions
0.05958155170083046
compute the derivatives for each block individually.
0.022159956395626068
compute both kinds of features simultaneously.
0.019417406991124153
To improve segmentation performance at object boundaries,
0.014865842647850513
F only computes a residual that is added to the input x n−1.
0.009961247444152832
sampling the augmentation parameter γ
0.005953924264758825
quantify detailed boundary adherence
0.004992116708308458
annotated data is crucial in order to train such deep networks,
0.0033286705147475004
adjust the number of feature channels
0.003291688160970807
upsample our predictions using bilinear interpolation
0.0009743220871314406
Quantitative Evaluation
0.00025023301714099944
localizing object boundaries, but performs poorly at recognizing the actual objects.
0.00019962855731137097
initialized with pre - trained weights.
3.633206870290451e-05
------------------------

{'final_answer': FinalAnswer(text='To improve segmentation performance at object boundaries,', confidence=np.float64(0.08679608585076824), supporting_answers=[Answer(text='To improve segmentation performance at object boundaries,', chunk=TextChunk(sentences=[Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58), Sentence(text='Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance.', num=59), Sentence(text='However, they have the downside that the resulting network outputs are at a lower resolution.', num=60), Sentence(text='To overcome this, various strategies have been proposed.', num=61), Sentence(text='Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference].', num=62), Sentence(text='Noh et al.', num=63), Sentence(text='propose an encoder / decoder network [reference].', num=64), Sentence(text='The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations.', num=65), Sentence(text='The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference].', num=66), Sentence(text='Similarly, Badrinarayanan et al.', num=67), Sentence(text='[reference ][ reference] use convolutions instead of deconvolutions in the decoder network.', num=68), Sentence(text='In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream.', num=69), Sentence(text='Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions.', num=70), Sentence(text='Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference].', num=71), Sentence(text='More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference].', num=72)], text='Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference].', word_token_count=381), confidence=0.014865842647850513, start_pos=175, end_pos=232)]),

In [15]:
res2 = extract_keywords(them_asp=them_aspect,
                        reference_answer=reference_answers[0])

---
---> Keyword extraction result:
{'reference_answer': 'Semantic Segmentation', 'valid_answers_count': 2, 'valid_answers': [Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=384), confidence=0.1799963414669037, start_pos=0, end_pos=27), Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning.', num=0), Sentence(text='Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole.', num=1), Sentence(text='While these networks exhibit outstanding recognition performance (i.e., what is visible?', num=2), Sentence(text='), they lack localization accuracy (i.e., where precisely is something located?', num=3), Sentence(text=').', num=4), Sentence(text='Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution.', num=5), Sentence(text='To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance.', num=6), Sentence(text='We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries.', num=7), Sentence(text='The other stream undergoes a sequence of pooling operations to obtain robust features for recognition.', num=8), Sentence(text='The two streams are coupled at the full image resolution using residuals.', num=9), Sentence(text='Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset.', num=10), Sentence(text='section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems.', num=11), Sentence(text='A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving.', num=12), Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13)], text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', word_token_count=374), confidence=0.0805731937289238, start_pos=1718, end_pos=1745)], 'analysis': {'keywords': ['modern', 'score', 'target', 'training', 'accuracy', 'trained', 'targetnetworks', 'pretrained', 'fullresolution', 'geometry'], 'chunks': [TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=384), TextChunk(sentences=[Sentence(text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning.', num=0), Sentence(text='Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole.', num=1), Sentence(text='While these networks exhibit outstanding recognition performance (i.e., what is visible?', num=2), Sentence(text='), they lack localization accuracy (i.e., where precisely is something located?', num=3), Sentence(text=').', num=4), Sentence(text='Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution.', num=5), Sentence(text='To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance.', num=6), Sentence(text='We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries.', num=7), Sentence(text='The other stream undergoes a sequence of pooling operations to obtain robust features for recognition.', num=8), Sentence(text='The two streams are coupled at the full image resolution using residuals.', num=9), Sentence(text='Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset.', num=10), Sentence(text='section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems.', num=11), Sentence(text='A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving.', num=12), Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13)], text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', word_token_count=374)]}}

In [16]:
filtered_keywords = filter_keywords(result=res2, 
                    them_asp=them_aspect,
                    similarity_threshold=0.5,
                    dissimilarity_threshold=0.55)
filtered_keywords

['score', 'training', 'accuracy', 'trained', 'pretrained', 'geometry']

TODO:
>Здесь можно тестировать, насколько конкретно эти слова позволяют искать нужный фрагмент текста

In [17]:
filtering_set = FilteringSet(text, filtered_keywords)

In [18]:
them_aspect = ThematicAspect(field_name, convert_into_question_class(questions))

In [19]:
res3 = extract_short_answer(text=text_of_doc,
                them_asp=them_aspect, 
                filter_mode=FilterMode.BY_KW_LEMSTEM,
                filter_set=filtering_set,
                agg_mode=AggMode.NO_AGG)
res3

---> Number of sentences:
--> 276

Device set to use cuda:1

---
---> Number of chunks:
--> 22

---
---> Number of filtered by keyword's lemms & stemms chunks:
--> 12

---
---> Founded answers:
----->1/1
----->Which task was solved?
find the correct sidewalk boundary,
0.201487734913826
Semantic image segmentation
0.1799963414669037
F only computes a residual that is added to the input x n−1.
0.15894180536270142
bootstrapped cross - entropy loss
0.09279076009988785
Semantic image segmentation
0.0805731937289238
upscale the spatial dimensions
0.05958155170083046
sampling the augmentation parameter γ
0.005953924264758825
quantify detailed boundary adherence
0.004992116708308458
annotated data is crucial in order to train such deep networks,
0.0033286705147475004
Quantitative Evaluation
0.00025023301714099944
localizing object boundaries, but performs poorly at recognizing the actual objects.
0.00019962855731137097
initialized with pre - trained weights.
3.633206870290451e-05
------------------------

{'final_answer': FinalAnswer(text='Semantic image segmentation', confidence=np.float64(0.06567769103367027), supporting_answers=[Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=384), confidence=0.1799963414669037, start_pos=0, end_pos=27), Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning.', num=0), Sentence(text='Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole.', num=1), Sentence(text='While these networks exhibit outstanding recognition performance (i.e., what is visible?', num=2), Sentence(text='), they lack localization accuracy (i.e., where precisely is something located?', num=3), Sentence(text=').', num=4), Sentence(text='Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution.', num=5), Sentence(text='To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance.', num=6), Sentence(text='We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries.', num=7), Sentence(text='The other stream undergoes a sequence of pooling operations to obtain robust features for recognition.', num=8), Sentence(text='The two streams are coupled at the full image resolution using residuals.', num=9), Sentence(text='Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset.', num=10), Sentence(text='section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems.', num=11), Sentence(text='A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving.', num=12), Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13)], text='Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', word_token_count=374), confidence=0.0805731937289238, start_pos=1718, end_pos=1745)]),

In [20]:
df_loaded.loc[num_of_sample, "first_answer"] = res1['final_answer'].text
df_loaded.loc[num_of_sample, "corrected_answer"] = res3['final_answer'].text
df_loaded.loc[num_of_sample, "keywords"] = str(filtered_keywords)

df_loaded

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'training', 'accuracy', 'trained', '...",None
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],None,None,None,None
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",None,None,None,None
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],None,None,None,None
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",None,None,None,None
...,...,...,...,...,...,...,...,...
301,45b559e6271570598602fcf9777ed6f2f2d133e6,document: Very Deep Multilingual Convolutional...,[Speech_Recognition],[Speech Recognition],None,None,None,None
302,45e8ef229fae18b0a2ab328037d8e520866c3c81,document: Learning Feature Pyramids for Human ...,[Pose_Estimation],[Pose Estimation],None,None,None,None
303,45fdc73a239e9c6ea65e98c96f6a2d6dc35d6f72,document: Quaternion Convolutional Neural Netw...,[Speech_Recognition],[Speech Recognition],None,None,None,None
304,46018a894d533813d67322827ca51f78aed6d59e,document: Brain Tumor Segmentation with Deep N...,[Brain_Tumor_Segmentation],[Brain Tumor Segmentation],None,None,None,None
305,462d4e265c9cbe9ad5feeb9a7736184a90b36fed,document: Evaluating the Utility of Hand - cra...,[Named_Entity_Recognition__NER_],[Named Entity Recognition NER ],None,None,None,None

In [21]:
metrics = calculate_string_metrics(model=SentenceTokenizerSingleton(),
                            text1=df_loaded.loc[num_of_sample, "tasks_cleaned"][0], 
                            text2=res3['final_answer'].text)
metrics

{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}

In [23]:
df_loaded.loc[num_of_sample, "metrics"] = str(metrics)

df_loaded

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'training', 'accuracy', 'trained', '...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}"
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],None,None,None,None
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",None,None,None,None
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],None,None,None,None
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",None,None,None,None
...,...,...,...,...,...,...,...,...
301,45b559e6271570598602fcf9777ed6f2f2d133e6,document: Very Deep Multilingual Convolutional...,[Speech_Recognition],[Speech Recognition],None,None,None,None
302,45e8ef229fae18b0a2ab328037d8e520866c3c81,document: Learning Feature Pyramids for Human ...,[Pose_Estimation],[Pose Estimation],None,None,None,None
303,45fdc73a239e9c6ea65e98c96f6a2d6dc35d6f72,document: Quaternion Convolutional Neural Netw...,[Speech_Recognition],[Speech Recognition],None,None,None,None
304,46018a894d533813d67322827ca51f78aed6d59e,document: Brain Tumor Segmentation with Deep N...,[Brain_Tumor_Segmentation],[Brain Tumor Segmentation],None,None,None,None
305,462d4e265c9cbe9ad5feeb9a7736184a90b36fed,document: Evaluating the Utility of Hand - cra...,[Named_Entity_Recognition__NER_],[Named Entity Recognition NER ],None,None,None,None

In [24]:
save_dataframe_to_json(df=df_loaded, 
                    file_path=f"{datasets_results_path}/{res_name}")

The dataset was successfully saved to datasets_results/results.json