### Подключение

In [1]:
from system_check import *
CUDA_state_print()

CUDA доступна: True
Количество GPU: 4

GPU #0:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #1:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #2:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #3:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

In [2]:
import sys
sys.path.append("/global_functions")
from global_functions.global_functions import *

------------------------------------
---> Choosing resource
---> Result of torch.cuda.is_available():
True
---> Final resource
-----> CUDA: 1
-----> device: cuda:1
------------------------------------

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/model.safetensors
All model checkpoint weights were used when initializing BertModel.

All the weights of BertModel were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/config.json
Model config RobertaConfig {
  "architectures": [
    "RobertaForQuestionAnswering"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "language": "english",
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "name": "Roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_attentions": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/model.safetensors
All model checkpoint weights were used when initializing RobertaForQuestionAnswering.

All the weights of RobertaForQuestionAnswering were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use RobertaForQuestionAnswering for predictions without further training.

### Датасет

In [3]:
name = "scirex_structured.json"
datasets_path = "../datasets"

df_loaded = load_dataframe_from_json(f"{datasets_path}/{name}")

In [4]:
df_loaded = replace_underscores_in_array_column(df=df_loaded,
                                        column_name="tasks")
df_loaded.head()

,doc_id,methods,tasks,metrics,materials,score,original_text,tasks_cleaned
0,000f90380d768a85e2316225854fc377c079b5c4,[FRRN],"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Frame__fps_, Mean_IoU, mIoU, Time__ms_]",[Cityscapes],"[2.1, 71.8%, 469]",Full - Resolution Residual Networks for Semant...,"[Semantic Segmentation, Real-Time Semantic Seg..."
1,0012de6bec1f25599e4f02517637e531a71909b9,[V-Net___Dice-based_loss],[Volumetric_Medical_Image_Segmentation],[Dice_Score],[PROMISE_2012],[0.869],document: V - Net: Fully Convolutional Neural ...,[Volumetric Medical Image Segmentation]
2,007ab5528b3bd310a80d553cccad4b78dc496b02,"[BiDAF__single_model_, BiDAF, BiDAF__ensemble_...","[Question_Answering, Open-Domain_Question_Answ...","[METEOR, EM__Quasar-T_, F1__Quasar-T_, F1, EM,...","[NarrativeQA, MS_MARCO, SQuAD1_1, CNN___Daily_...","[33.45, 23.96, 15.69, 25.9, 79.6, 36.74, 76.9,...",document: Bi - Directional Attention Flow for ...,"[Question Answering, Open-Domain Question Answ..."
3,0095c269e7d0c990249312687fc43521019809c4,[50D_stacked_TC-LSTMs],[Natural_Language_Inference],"[Parameters, __Train_Accuracy, __Test_Accuracy]",[SNLI],"[190k, 86.7, 85.1]",document: Modelling Interaction of Sentence Pa...,[Natural Language Inference]
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,"[AlphaZero, AlphaGo_Zero]","[Game_of_Go, Game_of_Shogi]",[ELO_Rating],[ELO_Ratings],"[4650, 5185]",document: Mastering Chess and Shogi by Self - ...,"[Game of Go, Game of Shogi]"

### Модель

In [5]:
model_name = "scart_init_model.json"
model_params_path = "../model_params"

df_model_params = pd.read_json(f"{model_params_path}/{model_name}")

df_model_params

,model_name,description,fields
0,ScArt Model,Модель для обработки научных статей на английс...,"{'field_id': 1, 'field_name': 'task', 'field_t..."

In [6]:
field_name = df_model_params["fields"][0]["field_name"]
questions = df_model_params["fields"][0]["questions"]
keywords = df_model_params["fields"][0]["keywords"]
text = df_model_params["fields"][0]["text"]

In [7]:
them_aspect = ThematicAspect(field_name, convert_into_question_class(questions))

### Сэмпл

In [8]:
num_of_sample = 0

In [9]:
text_of_doc = df_loaded["original_text"][num_of_sample]

In [10]:
reference_answers = df_loaded["tasks_cleaned"][num_of_sample]
reference_answers

['Semantic Segmentation', 'Real-Time Semantic Segmentation']

### Обработка

In [11]:
text_proc = TextProcesser()
sents = text_proc.split_into_sentences(text_of_doc)

sentences = [Sentence(sents[i], i) for i in range(len(sents))]

print("---> Number of sentences:")
print(f"--> {len(sentences)}")

chunk_builder = ChunkBuilder()
text_chunks = chunk_builder.build_chunks(sentences)

print("---\n---> Number of chunks:")
print(f"--> {len(text_chunks)}")

---> Number of sentences:
--> 276
---
---> Number of chunks:
--> 22

#### Базовый ответ

In [12]:
simp_ans_finder = SimpleAnswerFinder()


question_with_answers = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        chunks = text_chunks
        )

Device set to use cuda:1
Disabling tokenizer parallelism, we're using DataLoader multithreading already
RobertaSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [13]:
print("\n---\n---> Founded answers:")
for ans in question_with_answers.answers:
    print(ans.text)
    print(ans.confidence)
    print(ans.chunk.text)
    print("----------------------\n")

---
---> Founded answers:
overfitting
0.04313625767827034
We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne. In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation. The former method randomly translates an image and its annotations. In order to keep consistent image dimensions, we have to pad the translated images and annotations. To this end, we use reflection padding on the image and constant padding with void labels on the annotations. Our second method of data augmentation is gamma augmentation. We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities. This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively). The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation. Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server. We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images. We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels. Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design. However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.
----------------------

stereo or optical flow
0.010819800023455173
We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .
----------------------

look at the deviation of U from 0. 5 .
0.010365484282374382
Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 . Let Z be this deviation. Then (11) is equivalent to Hence, without solving for the implicitly defined variable U explicitly, we found a transformation of a zero - mean random variable Z such that γ has the desired properties. Because Z was defined to be the offset from 0. 5  and U ∈ [0, 1], it follows Z ∈ [−0. 5 , 0. 5 ]. We are free to choose any distribution such that Z has zero mean and falls into the range [−0. 5 , 0. 5 ]. For simplicity reasons, we choose Z to be uniformly distributed over [−a, a] where a ∈ [0, 0. 5 ] determines the strength of the augmentation. Figure 8b illustrates the obvious bias reduction. section: B. Baseline Evaluation In Section 5. 2  of the main paper, we describe the setting of our baseline method (Residual Network Baseline) and compare it to our FRRN A network. To emphasize on a proper training procedure of both baselines, Figure 9 shows the mean IoU score on the validation set over time. We can see that our model outperforms the baseline with a significant margin and both methods are trained until convergence. Figure 10 shows and compares addtional output labelings of our method. Please also consult our labeled video sequence [reference] to gain a better sense of the quality of our method. We all know Latex is a pain. section: C. Qualitative Results section: Image Ground Truth Ours LRR [reference] Figure 10. Additional qualitative results on the Cityscapes validation set.
----------------------

bootstrapped cross - entropy loss
0.0026516092475503683
We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations. The pooled feature maps are then successively upscaled using bilinear interpolation in the decoder. Furthermore, similar to Simonyan and Zisserman [reference], we define a number of base channels that we double after each pooling operation (up to a certain upper limit). Instead of choosing 64 base channels as in VGG net, we use 48 channels in order to have a manageable number of trainable parameters. Depending on the input image resolution, we use FRRN A or FRRN B to keep the relative size of the receptive fields consistent. section: Training Procedure Following Wu et al. , we train our network by minimizing a bootstrapped cross - entropy loss [reference]. Let c be the number of classes, y 1,. , y N ∈ {1,. , c} be the target class labels for the pixels 1,. , N, and let p i, j be the posterior class + Bias Softmax probability for class j and pixel i. Then, the bootstrapped cross - entropy loss over K pixels is defined as where 1 [x] = 1 iff x is true and t k ∈ R is chosen such that |{i ∈ {1,. , N}: p i, yi < t k} | = K. The threshold parameter t k can easily be determined by sorting the predicted log probabilities and choosing the K + 1 - th one as threshold. Figure 4 visualizes the concept. Depending on the number of pixels K that we consider, we select misclassified pixels or pixels where we predict the correct label with a small probability. We minimize the loss using ADAM [reference].
----------------------

correct sidewalk boundary
0.0023512907791882753
The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions. Even though we only train on half - resolution images, Figure 5 clearly shows we can match the current published state - of - the - art (LRR [reference] Figure 7. Qualitative comparison on the Cityscapes validation set. Interesting cases are the fence in the first row, the truck in the second row, or the street light poles in the last row. An interesting failure case is shown in the third row: all methods struggle to find the correct sidewalk boundary, however our network makes a clean and reasonable prediction. section: Boundary Adherence Due to several pooling operations (and subsequent upsampling) in many of today 's FCN architectures, boundaries are often overly smooth, resulting in lost details and edge - bleeding. This leads to suboptimal scores, but it also makes the output of a semantic segmentation approach harder to use without further post - processing. Since inaccurate boundaries are often not apparent from the standard evaluation metric scores, a typical approach is a trimap evaluation in order to quantify detailed boundary adherence [reference ][ reference ][ reference]. During trimap evaluation, all predictions are ignored if they do not fall within a certain radius r of a ground truth label boundary. Figure 6 visualizes our trimap evaluation performed on the validation set for varying trimap widths r between 1 and 80 pixels. We compare to LRR [reference] and Dilation [reference], who made code and pre - trained models available. We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries.
----------------------

upscaling by repeating the entries along the spatial dimensions
0.0022367131896317005
This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation performance. The proposed architectures are based on several principles employed by other authors. We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations.
----------------------

no residuals are computed
0.0014246442588046193
Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively. If G ≡ 0, then an FRRU corresponds to an RU since it disregards the pooling input y n, and the network effectively becomes an ordinary ResNet. On the other hand, if H ≡ 0, then the output of an FRRU only depends on its input via the function G. Hence, no residuals are computed and we obtain a traditional feedforward network. By carefully constructing G and H, we can combine the two network principles. In order to show that FRRNs have similar training characteristics as ResNets, we adapt the analysis presented in [reference] to our case. Using the same recursive argument as before, we find that for m > n, z m has the representation We can then express the derivative of the loss l with respect to the weights W n as Hence, the weight updates depend on three sources of information. Analogous to the analysis of ResNets, the two sources ∂H (yi, zi;Wi + 1) ∂zn depend crucially on the depth n, while the term ∂l ∂zm is independent of the depth. Thus, we achieve a depth - independent gradient flow for all parameters that are used by the residual function H. If we use some of these weights in order to compute the output of G, all weights of the unit benefit from the improved gradient flow. This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design.
----------------------

precise semantic segmentation
0.0009385889861732721
Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams. One stream undergoes a sequence of pooling operations and is responsible for understanding large - scale relationships of image elements; the other stream carries feature maps at the full image resolution, resulting in precise boundary adherence. This idea is visualized in Figure 1, where the two processing streams are shown in blue and red. The blue residual lane reflects the high - resolution stream. It can be combined with classical residual units (left and right), as well as with our new full - resolution residual units (FRRU). The FRRUs from the red pooling lane act as residual units for the blue stream, but also undergo pooling operations and carry high - level information through the network. This results in a network that successively combines and computes features at two resolutions. This paper makes the following contributions: (i) We propose a novel network architecture geared towards precise semantic segmentation in street scenes which is not limited to pre - trained architectures and achieves state - ofthe - art results. (ii) We propose to use two processing streams to realize strong recognition and strong localization performance: One stream undergoes a sequence of pooling operations while the other stream stays at the full image resolution. (iii) In order to foster further research in this area, we publish our code and the trained models in Theano / Lasagne [reference ][ reference] 1. 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.
----------------------

smoothing the network predictions
0.0007261462160386145
To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
----------------------

Training FRRN B
0.0007058468763716519
The resulting ResNet has slightly fewer parameters than the original FRRN (16. 7  × 10 6 vs. 17. 7  × 10 6). This is due to the fact that RUs lack the 1 × 1 convolutions that connect the pooling to the residual Table 2. IoU scores from the cityscapes test set. We highlight the best published baselines for the different sampling rates. (Additional anonymous submissions exist as concurrent work. ) Bold numbers represent the best, italic numbers the second best score for a class. We also indicate the subsampling factor used on the input images, whether additional coarsely annotated data was used, and whether the model was initialized with pre - trained weights. stream. section: Method We train both networks on the quarter - resolution Cityscapes dataset for 45, 000 iterations at a batch size of 3. We use a learning rate of 10 −3 for the first 35, 000 iterations and then reduce it to 10 −4 for the following 10, 000 iterations. Both networks converged within these iterations. The FRRN A resulted in a validation set mean IoU score of 65. 7 % while the ResNet baseline only achieved 62. 8 %, showing a significant advantage of our FRRNs. Training FRRN B is performed in a similar fashion. Detailed training curves are shown in Appendix B. section: Quantitative Evaluation Overview In Table 2 we compare our method to the best (published) performers on the Cityscapes leader board, namely LRR [reference], Adelaide [reference], and Dilation [reference]. Note that our network performs on par with the very complex and well engineered system by [reference]. Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores.
----------------------

semantic segmentation
0.0005423750844784081

In [14]:
filtering_set = FilteringSet(text, keywords)

res1 = extract_short_answer(text=text_of_doc,
                them_asp=them_aspect, 
                filter_mode=FilterMode.NO_FILTER,
                filter_set=filtering_set,
                agg_mode=AggMode.NO_AGG)

Device set to use cuda:1

In [15]:
print(res1['final_answer'].text)

for ans in res1['final_answer'].supporting_answers:
    print(ans.text)
    print(ans.chunk.text)

semantic segmentation
semantic segmentation
1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.

In [16]:
validator = AnswerValidator()
validator_result = validator.validate_answers(question_with_answers.answers, reference_answers[0])

In [17]:
validator_result

[Answer(text='semantic segmentation', chunk=TextChunk(sentences=[Sentence(text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.', num=45), Sentence(text='As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference].', num=46), Sentence(text='In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations.', num=47), Sentence(text='Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures.', num=48), Sentence(text='Semantic Segmentation Approaches.', num=49), Sentence(text='Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs).', num=50), Sentence(text='Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference].', num=51), Sentence(text='Rather than classifying entire regions in the first place, the approach by Farabet et al.', num=52), Sentence(text='performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference].', num=53), Sentence(text='The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al.', num=54), Sentence(text='[reference] opened a wide range of semantic segmentation research using end - to - end training [reference].', num=55), Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58)], text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', word_token_count=371), confidence=0.0005423750844784081, start_pos=120, end_pos=141),
 Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)]

In [18]:
valid_chunks = [ans.chunk.text for ans in validator_result]

print("Искомые фрагменты:")
for chunk in valid_chunks:
    print("\t" + chunk)

Искомые фрагменты:
	1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.
	Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.

In [19]:
dicts_with_attention_keywords = []

for chunk in valid_chunks:
    key_dict = get_qa_attention_weights(model = BERTEngQASingleton(),
                                    question = questions[0], 
                                    context = chunk,
                                    device = get_device())
    dicts_with_attention_keywords.append(key_dict)

dicts_with_attention_keywords

[{'tokens': ['</s>',
   '1',
   'Ġhttps',
   ':',
   'Ġ//',
   'Ġgithub',
   '.',
   'com',
   'Ġ/',
   'ĠToby',
   'PD',
   'E',
   'Ġ/',
   'ĠFR',
   'RN',
   'Ġsection',
   ':',
   'ĠRelated',
   'ĠWork',
   'ĠThe',
   'Ġdramatic',
   'Ġperformance',
   'Ġimprovements',
   'Ġfrom',
   'Ġusing',
   'ĠCNN',
   's',
   'Ġfor',
   'Ġsemantic',
   'Ġsegment',
   'ation',
   'Ġhave',
   'Ġbrought',
   'Ġabout',
   'Ġan',
   'Ġincreasing',
   'Ġdemand',
   'Ġfor',
   'Ġsuch',
   'Ġalgorithms',
   'Ġin',
   'Ġthe',
   'Ġcontext',
   'Ġof',
   'Ġautonomous',
   'Ġdriving',
   'Ġscenarios',
   '.',
   'ĠAs',
   'Ġa',
   'Ġlarge',
   'Ġamount',
   'Ġof',
   'Ġannot',
   'ated',
   'Ġdata',
   'Ġis',
   'Ġcrucial',
   'Ġin',
   'Ġorder',
   'Ġto',
   'Ġtrain',
   'Ġsuch',
   'Ġdeep',
   'Ġnetworks',
   ',',
   'Ġmultiple',
   'Ġnew',
   'Ġdatasets',
   'Ġhave',
   'Ġbeen',
   'Ġreleased',
   'Ġto',
   'Ġencourage',
   'Ġfurther',
   'Ġresearch',
   'Ġin',
   'Ġthis',
   'Ġarea',
   ',',
   'Ġincluding',
   'ĠSyn',
   'thia',
   'Ġ[',
   'reference',
   '],',
   'ĠVirtual',
   'ĠK',
   'ITT',
   'I',
   'Ġ[',
   'reference',
   '],',
   'Ġand',
   'ĠCity',
   'sc',
   'apes',
   'Ġ[',
   'reference',
   '].',
   'ĠIn',
   'Ġthis',
   'Ġwork',
   ',',
   'Ġwe',
   'Ġfocus',
   'Ġon',
   'ĠCity',
   'sc',
   'apes',
   ',',
   'Ġa',
   'Ġrecent',
   'Ġlarge',
   'Ġ-',
   'Ġscale',
   'Ġdataset',
   'Ġconsisting',
   'Ġof',
   'Ġreal',
   'Ġ-',
   'Ġworld',
   'Ġimagery',
   'Ġwith',
   'Ġwell',
   'Ġ-',
   'Ġcurated',
   'Ġannotations',
   '.',
   'ĠGiven',
   'Ġtheir',
   'Ġsuccess',
   ',',
   'Ġwe',
   'Ġwill',
   'Ġconst',
   'rain',
   'Ġour',
   'Ġliterature',
   'Ġreview',
   'Ġto',
   'Ġdeep',
   'Ġlearning',
   'Ġbased',
   'Ġsemantic',
   'Ġsegment',
   'ation',
   'Ġapproaches',
   'Ġand',
   'Ġdeep',
   'Ġlearning',
   'Ġnetwork',
   'Ġarchitectures',
   '.',
   'ĠSem',
   'antic',
   'ĠSe',
   'gment',
   'ation',
   'ĠAppro',
   'aches',
   '.',
   'ĠOver',
   'Ġthe',
   'Ġlast',
   'Ġyears',
   ',',
   'Ġthe',
   'Ġmost',
   'Ġsuccessful',
   'Ġsemantic',
   'Ġsegment',
   'ation',
   'Ġapproaches',
   'Ġhave',
   'Ġbeen',
   'Ġbased',
   'Ġon',
   'Ġconv',
   'olution',
   'al',
   'Ġneural',
   'Ġnetworks',
   'Ġ(',
   'CNN',
   's',
   ').',
   'ĠEarly',
   'Ġapproaches',
   'Ġconstrained',
   'Ġtheir',
   'Ġoutput',
   'Ġto',
   'Ġa',
   'Ġbottom',
   'Ġ-',
   'Ġup',
   'Ġsegment',
   'ation',
   'Ġfollowed',
   'Ġby',
   'Ġa',
   'ĠCNN',
   'Ġbased',
   'Ġregion',
   'Ġclassification',
   'Ġ[',
   'reference',
   '].',
   'ĠRather',
   'Ġthan',
   'Ġclass',
   'ifying',
   'Ġentire',
   'Ġregions',
   'Ġin',
   'Ġthe',
   'Ġfirst',
   'Ġplace',
   ',',
   'Ġthe',
   'Ġapproach',
   'Ġby',
   'ĠFar',
   'abet',
   'Ġet',
   'Ġal',
   '.',
   'Ġperforms',
   'Ġpixel',
   'Ġ-',
   'Ġwise',
   'Ġclassification',
   'Ġusing',
   'ĠCNN',
   'Ġfeatures',
   'Ġoriginating',
   'Ġfrom',
   'Ġmultiple',
   'Ġscales',
   ',',
   'Ġfollowed',
   'Ġby',
   'Ġaggregation',
   'Ġof',
   'Ġthese',
   'Ġnoisy',
   'Ġpixel',
   'Ġpredictions',
   'Ġover',
   'Ġsuper',
   'pixel',
   'Ġregions',
   'Ġ[',
   'reference',
   '].',
   'ĠThe',
   'Ġintroduction',
   'Ġof',
   'Ġso',
   'Ġ-',
   'Ġcalled',
   'Ġfully',
   'Ġconv',
   'olution',
   'al',
   'Ġnetworks',
   'Ġ(',
   'FC',
   'Ns',
   ')',
   'Ġfor',
   'Ġsemantic',
   'Ġimage',
   'Ġsegment',
   'ation',
   'Ġby',
   'ĠLong',
   'Ġet',
   'Ġal',
   '.',
   'Ġ[',
   'reference',
   ']',
   'Ġopened',
   'Ġa',
   'Ġwide',
   'Ġrange',
   'Ġof',
   'Ġsemantic',
   'Ġsegment',
   'ation',
   'Ġresearch',
   'Ġusing',
   'Ġend',
   'Ġ-',
   'Ġto',
   'Ġ-',
   'Ġend',
   'Ġtraining',
   'Ġ[',
   'reference',
   '].',
   'ĠLong',
   'Ġet',
   'Ġal',
   '.',
   'Ġfurther',
   'Ġreform',
   'ulated',
   'Ġthe',
   'Ġpopular',
   'ĠV',
   'GG',
   'Ġarchitecture',
   'Ġ[',
   'reference',
   ']',
   'Ġas',
   'Ġa',
   'Ġfully',
   'Ġconv',
   'olution',
   'al',
   'Ġnetwork',
   'Ġ(',
   'FC',
   'N',
   '),',
   'Ġenabling',
   'Ġthe',
   'Ġuse',
   'Ġof',
   'Ġpret',
   'rained',
   'Ġmodels',
   'Ġfor',
   'Ġthis',
   'Ġarchitecture',
   '.',
   'ĠTo',
   'Ġimprove',
   'Ġsegment',
   'ation',
   'Ġperformance',
   'Ġat',
   'Ġobject',
   'Ġboundaries',
   ',',
   'Ġskip',
   'Ġconnections',
   'Ġwere',
   'Ġadded',
   'Ġwhich',
   'Ġallow',
   'Ġinformation',
   'Ġto',
   'Ġpropagate',
   'Ġdirectly',
   'Ġfrom',
   'Ġearly',
   ',',
   'Ġhigh',
   'Ġ-',
   'Ġresolution',
   'Ġlayers',
   'Ġto',
   'Ġdeeper',
   'Ġlayers',
   '.',
   '</s>'],
  'attention_weights': array([0.00417039, 0.00226192, 0.00221764, 0.00147409, 0.00230852,
         0.0027375 , 0.00117877, 0.00146758, 0.0021329 , 0.00208909,
         0.0015463 , 0.00118714, 0.00200701, 0.00124597, 0.00127983,
         0.00243995, 0.00202467, 0.00189696, 0.00239486, 0.00420431,
         0.0015184 , 0.00187043, 0.00226606, 0.00201824, 0.00219722,
         0.00203009, 0.00149446, 0.00208304, 0.00199329, 0.00201516,
         0.00175558, 0.00228693, 0.00170751, 0.00122806, 0.00128046,
         0.00145472, 0.00168422, 0.00124988, 0.00166045, 0.00244344,
         0.00137718, 0.00133083, 0.00143138, 0.00137776, 0.00206999,
         0.00185894, 0.00163343, 0.06861462, 0.00263885, 0.0014316 ,
         0.00113395, 0.00101504, 0.00105357, 0.00228646, 0.00090938,
         0.00188572, 0.00192059, 0.00228483, 0.00110651, 0.00120694,
         0.00149703, 0.00275813, 0.0019351 , 0.00162894, 0.00187222,
         0.00322255, 0.0019005 , 0.00172144, 0.00230244, 0.00165126,
         0.00131583, 0.00178267, 0.00164442, 0.00183167, 0.00146667,
         0.00221757, 0.00111256, 0.0017248 , 0.00146352, 0.0028108 ,
         0.00243951, 0.00153568, 0.00137866, 0.00159112, 0.00146972,
         0.00229923, 0.00194327, 0.00120183, 0.00110444, 0.00120142,
         0.0015027 , 0.00133363, 0.00142126, 0.00227161, 0.00198115,
         0.00122865, 0.00143117, 0.00157063, 0.00124036, 0.00193664,
         0.00191325, 0.00222219, 0.00265718, 0.00237243, 0.00315795,
         0.00197884, 0.00339826, 0.0028819 , 0.00164721, 0.00193673,
         0.00246896, 0.00198862, 0.00165241, 0.001139  , 0.00110317,
         0.00116205, 0.00268519, 0.00160337, 0.00122928, 0.00132749,
         0.00105002, 0.00111205, 0.00219551, 0.00166937, 0.00128402,
         0.00103167, 0.0014543 , 0.00220608, 0.06827512, 0.0019556 ,
         0.00195509, 0.00218032, 0.00217249, 0.00232682, 0.00219562,
         0.00148465, 0.00149779, 0.00207855, 0.00165054, 0.0016688 ,
         0.00270539, 0.00188949, 0.0019488 , 0.00138757, 0.00183366,
         0.00154474, 0.00135864, 0.00189219, 0.00224969, 0.00133214,
         0.00162005, 0.00123566, 0.00200948, 0.0060238 , 0.00221559,
         0.00118713, 0.00125514, 0.0013083 , 0.0012677 , 0.0021217 ,
         0.00175093, 0.06739401, 0.00203886, 0.00131561, 0.001461  ,
         0.00162615, 0.0034715 , 0.00192598, 0.00173413, 0.00195222,
         0.0020343 , 0.00192733, 0.00162631, 0.00226253, 0.00189076,
         0.00163255, 0.00166057, 0.00197992, 0.00151204, 0.00100009,
         0.0008905 , 0.00245269, 0.0017273 , 0.00167268, 0.00164378,
         0.00118473, 0.00263178, 0.00281804, 0.00222708, 0.0031934 ,
         0.00175728, 0.00166762, 0.00166532, 0.00157358, 0.00143771,
         0.00103766, 0.00114984, 0.00175502, 0.00145653, 0.0022192 ,
         0.00161059, 0.00163842, 0.00189598, 0.00126609, 0.00140193,
         0.0028215 , 0.00175151, 0.00143507, 0.00210616, 0.00257509,
         0.00187163, 0.00199859, 0.00189117, 0.00146442, 0.00156505,
         0.00115942, 0.00105706, 0.00133183, 0.00144614, 0.00354685,
         0.00270158, 0.00217461, 0.00229981, 0.00124477, 0.00113086,
         0.00162397, 0.00120095, 0.00167289, 0.00390646, 0.00202875,
         0.00145907, 0.00150472, 0.00305248, 0.0023857 , 0.002093  ,
         0.00172712, 0.00142793, 0.00117039, 0.00140532, 0.00154298,
         0.00240884, 0.00205003, 0.00170457, 0.00222367, 0.00124552,
         0.00189485, 0.00154992, 0.00144012, 0.00192716, 0.00173878,
         0.00143913, 0.00153275, 0.00153329, 0.0018582 , 0.0013341 ,
         0.00229665, 0.00393665, 0.00245215, 0.00189112, 0.00132862,
         0.00150858, 0.00141974, 0.00192252, 0.00126229, 0.00105728,
         0.00095172, 0.00223698, 0.00155534, 0.00126502, 0.00152731,
         0.00155801, 0.00242205, 0.00170966, 0.00198609, 0.00169787,
         0.00157864, 0.00246379, 0.00177506, 0.00141122, 0.00128356,
         0.00157274, 0.0017868 , 0.00148693, 0.00216369, 0.00319246,
         0.00173423, 0.00117746, 0.00127099, 0.00155025, 0.00164602,
         0.0016701 , 0.00156689, 0.00285806, 0.00247336, 0.00135933,
         0.00131244, 0.0011512 , 0.00109398, 0.0012367 , 0.00320691,
         0.00162104, 0.00126938, 0.00248822, 0.00207241, 0.00152623,
         0.001279  , 0.00185642, 0.00245028, 0.00209991, 0.0023603 ,
         0.00210129, 0.00157237, 0.00138218, 0.00129801, 0.00212134,
         0.00171377, 0.00132618, 0.00129509, 0.00205942, 0.00157629,
         0.00179606, 0.00123936, 0.00102477, 0.00095316, 0.0020058 ,
         0.00164669, 0.00134696, 0.00121758, 0.00251049, 0.00226116,
         0.00121514, 0.00134661, 0.00121426, 0.00135669, 0.00124252,
         0.0019194 , 0.00154907, 0.0019219 , 0.00178535, 0.06393354,
         0.00241767, 0.00214892, 0.00163527, 0.00147213, 0.00163925,
         0.00195105, 0.00183587, 0.0016103 , 0.00285148, 0.00189559,
         0.00181147, 0.00232226, 0.0016809 , 0.00199578, 0.0018446 ,
         0.00188287, 0.00145386, 0.00170593, 0.00138333, 0.00166946,
         0.00155167, 0.00144953, 0.00101332, 0.0010826 , 0.00145484,
         0.00165167, 0.00178815, 0.0014118 , 0.00149498, 0.06723244,
         0.00849935], dtype=float32),
  'question': 'Which task was solved?',
  'context': '1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.'},
 {'tokens': ['</s>',
   'Sem',
   'antic',
   'Ġimage',
   'Ġsegment',
   'ation',
   'Ġ[',
   'reference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   '],',
   'Ġthe',
   'Ġtask',
   'Ġof',
   'Ġassigning',
   'Ġa',
   'Ġset',
   'Ġof',
   'Ġpred',
   'efined',
   'Ġclass',
   'Ġlabels',
   'Ġto',
   'Ġimage',
   'Ġpixels',
   ',',
   'Ġis',
   'Ġan',
   'Ġimportant',
   'Ġtool',
   'Ġfor',
   'Ġmodeling',
   'Ġthe',
   'Ġcomplex',
   'Ġrelationships',
   'Ġof',
   'Ġthe',
   'Ġsemantic',
   'Ġentities',
   'Ġusually',
   'Ġfound',
   'Ġin',
   'Ġstreet',
   'Ġscenes',
   ',',
   'Ġsuch',
   'Ġas',
   'Ġcars',
   ',',
   'Ġpedestrians',
   ',',
   'Ġroad',
   ',',
   'Ġor',
   'Ġsidewalks',
   '.',
   'ĠIn',
   'Ġautomotive',
   'Ġscenarios',
   'Ġit',
   'Ġis',
   'Ġused',
   'Ġin',
   'Ġvarious',
   'Ġways',
   ',',
   'Ġe',
   '.',
   'g',
   '.',
   'Ġas',
   'Ġa',
   'Ġpre',
   'Ġ-',
   'Ġprocessing',
   'Ġstep',
   'Ġto',
   'Ġdiscard',
   'Ġimage',
   'Ġregions',
   'Ġthat',
   'Ġare',
   'Ġunlikely',
   'Ġto',
   'Ġcontain',
   'Ġobjects',
   'Ġof',
   'Ġinterest',
   'Ġ[',
   'reference',
   'Ġ][',
   'Ġreference',
   '],',
   'Ġto',
   'Ġimprove',
   'Ġobject',
   'Ġdetection',
   'Ġ[',
   'reference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   '].',
   'ĠExample',
   'Ġoutput',
   'Ġand',
   'Ġthe',
   'Ġabstract',
   'Ġstructure',
   'Ġof',
   'Ġour',
   'Ġfull',
   'resolution',
   'Ġresidual',
   'Ġnetwork',
   '.',
   'ĠThe',
   'Ġnetwork',
   'Ġhas',
   'Ġtwo',
   'Ġprocessing',
   'Ġstreams',
   '.',
   'ĠThe',
   'Ġresidual',
   'Ġstream',
   'Ġ(',
   'blue',
   ')',
   'Ġstays',
   'Ġat',
   'Ġthe',
   'Ġfull',
   'Ġimage',
   'Ġresolution',
   ',',
   'Ġthe',
   'Ġpool',
   'ing',
   'Ġstream',
   'Ġ(',
   'red',
   ')',
   'Ġundergo',
   'es',
   'Ġa',
   'Ġsequence',
   'Ġof',
   'Ġpool',
   'ing',
   'Ġand',
   'Ġun',
   'pool',
   'ing',
   'Ġoperations',
   '.',
   'ĠThe',
   'Ġtwo',
   'Ġprocessing',
   'Ġstreams',
   'Ġare',
   'Ġcoupled',
   'Ġusing',
   'Ġfull',
   'Ġ-',
   'Ġresolution',
   'Ġresidual',
   'Ġunits',
   'Ġ[',
   'reference',
   ']',
   'Ġor',
   'Ġin',
   'Ġcombination',
   'Ġwith',
   'Ġ3',
   'D',
   'Ġscene',
   'Ġgeometry',
   'Ġ[',
   'reference',
   'Ġ][',
   'Ġreference',
   'Ġ][',
   'Ġreference',
   '].',
   'ĠMany',
   'Ġof',
   'Ġthose',
   'Ġapplications',
   'Ġrequire',
   'Ġprecise',
   'Ġregion',
   'Ġboundaries',
   'Ġ[',
   'reference',
   '].',
   'ĠIn',
   'Ġthis',
   'Ġwork',
   ',',
   'Ġwe',
   'Ġtherefore',
   'Ġpursue',
   'Ġthe',
   'Ġgoal',
   'Ġof',
   'Ġachieving',
   'Ġhigh',
   'Ġ-',
   'Ġquality',
   'Ġsemantic',
   'Ġsegment',
   'ation',
   'Ġwith',
   'Ġprecise',
   'Ġboundary',
   'Ġadherence',
   '.',
   'ĠCurrent',
   'Ġstate',
   'Ġ-',
   'Ġof',
   'Ġ-',
   'Ġthe',
   'Ġ-',
   'Ġart',
   'Ġapproaches',
   'Ġfor',
   'Ġimage',
   'Ġsegment',
   'ation',
   'Ġall',
   'Ġemploy',
   'Ġsome',
   'Ġform',
   'Ġof',
   'Ġfully',
   'Ġconv',
   'olution',
   'al',
   'Ġnetwork',
   'Ġ(',
   'FC',
   'Ns',
   ')',
   'Ġ[',
   'reference',
   ']',
   'Ġthat',
   'Ġtakes',
   'Ġthe',
   'Ġimage',
   'Ġas',
   'Ġinput',
   'Ġand',
   'Ġoutputs',
   'Ġa',
   'Ġprobability',
   'Ġmap',
   'Ġfor',
   'Ġeach',
   'Ġclass',
   '.',
   'ĠMany',
   'Ġpapers',
   'Ġrely',
   'Ġon',
   'Ġnetwork',
   'Ġarchitectures',
   'Ġthat',
   'Ġhave',
   'Ġalready',
   'Ġbeen',
   'Ġproven',
   'Ġsuccessful',
   'Ġfor',
   'Ġimage',
   'Ġclassification',
   'Ġsuch',
   'Ġas',
   'Ġvariants',
   'Ġof',
   'Ġthe',
   'ĠRes',
   'Net',
   'Ġ[',
   'reference',
   ']',
   'Ġor',
   'Ġthe',
   'ĠV',
   'GG',
   'Ġarchitecture',
   'Ġ[',
   'reference',
   '].',
   'ĠStarting',
   'Ġfrom',
   'Ġpre',
   'Ġ-',
   'Ġtrained',
   'Ġnets',
   ',',
   'Ġwhere',
   'Ġa',
   'Ġlarge',
   'Ġnumber',
   'Ġof',
   'Ġweights',
   'Ġfor',
   'Ġthe',
   'Ġtarget',
   'Ġtask',
   'Ġcan',
   'Ġbe',
   'Ġpre',
   'Ġ-',
   'Ġset',
   'Ġby',
   'Ġan',
   'Ġauxiliary',
   'Ġclassification',
   'Ġtask',
   ',',
   'Ġreduces',
   'Ġtraining',
   'Ġtime',
   'Ġand',
   'Ġoften',
   'Ġyields',
   'Ġsuperior',
   'Ġperformance',
   'Ġcompared',
   'Ġto',
   'Ġtraining',
   'Ġa',
   'Ġnetwork',
   'Ġfrom',
   'Ġscratch',
   'Ġusing',
   'Ġthe',
   'Ġ(',
   'possibly',
   'Ġlimited',
   'Ġamount',
   'Ġof',
   ')',
   'Ġdata',
   'Ġof',
   'Ġthe',
   'Ġtarget',
   'Ġapplication',
   '.',
   '</s>'],
  'attention_weights': array([0.00686599, 0.00252242, 0.00157141, 0.00207893, 0.00227719,
         0.00245426, 0.00237077, 0.00137793, 0.00193614, 0.00131423,
         0.00194569, 0.00125715, 0.00200684, 0.00113485, 0.00176583,
         0.00137071, 0.00286398, 0.00331032, 0.00366832, 0.00250368,
         0.0030231 , 0.00164919, 0.00127483, 0.00153675, 0.0012546 ,
         0.00157415, 0.0015792 , 0.00186331, 0.00186597, 0.0017541 ,
         0.0023887 , 0.0026325 , 0.0027813 , 0.00161203, 0.00158686,
         0.00160464, 0.00185319, 0.00371997, 0.00169595, 0.00140385,
         0.0016553 , 0.00124044, 0.00160268, 0.00225676, 0.00169185,
         0.00208342, 0.00123787, 0.00145764, 0.00186172, 0.00186673,
         0.00177779, 0.00153255, 0.00132756, 0.00164357, 0.00139509,
         0.00165663, 0.00143827, 0.00121838, 0.00111594, 0.00151879,
         0.00177034, 0.05735246, 0.00214011, 0.00255848, 0.00180012,
         0.00363945, 0.00185056, 0.00226617, 0.00121672, 0.00146863,
         0.00161264, 0.00228026, 0.00160294, 0.00092127, 0.00160232,
         0.00167932, 0.00169381, 0.00136492, 0.0013909 , 0.00103068,
         0.00145937, 0.00179392, 0.00247414, 0.00284272, 0.00175261,
         0.00165653, 0.0016469 , 0.00118453, 0.00192705, 0.00110742,
         0.00142887, 0.00154735, 0.00101642, 0.00140897, 0.00217047,
         0.00121009, 0.00199794, 0.00123803, 0.00261469, 0.00184322,
         0.00225945, 0.00161891, 0.00242863, 0.00229593, 0.00121663,
         0.00211848, 0.0011455 , 0.00208034, 0.00110625, 0.00180248,
         0.00124487, 0.00219346, 0.00285409, 0.0018292 , 0.00243386,
         0.00146559, 0.00148269, 0.00128718, 0.00117794, 0.00265052,
         0.00134254, 0.00137246, 0.00166668, 0.00204973, 0.05652064,
         0.00346672, 0.00227269, 0.00217737, 0.00163704, 0.00157244,
         0.00165537, 0.05633327, 0.00288304, 0.00183485, 0.00162754,
         0.00150908, 0.00177723, 0.00145394, 0.00216794, 0.00129816,
         0.00114558, 0.00134272, 0.0015081 , 0.00178214, 0.00334963,
         0.00172741, 0.00138103, 0.00105969, 0.00151673, 0.00139407,
         0.00159265, 0.00135982, 0.00220727, 0.00134991, 0.00146777,
         0.00153769, 0.00121542, 0.00135224, 0.00102007, 0.00165704,
         0.00133847, 0.00109928, 0.00100419, 0.00262503, 0.05780032,
         0.00267155, 0.00163408, 0.00162171, 0.00177077, 0.00228773,
         0.00224332, 0.00255767, 0.00135586, 0.00130679, 0.00142271,
         0.00162931, 0.00164527, 0.00193863, 0.0015395 , 0.00135965,
         0.00253173, 0.00101407, 0.00143899, 0.00144196, 0.00115833,
         0.00135358, 0.00131438, 0.00199127, 0.00200915, 0.00118137,
         0.00210735, 0.00105651, 0.00182448, 0.00118778, 0.00217413,
         0.00209644, 0.00123195, 0.00184979, 0.00243655, 0.00268391,
         0.00170814, 0.0012269 , 0.00198325, 0.001624  , 0.00134855,
         0.00167594, 0.00176847, 0.00222104, 0.00282487, 0.00223666,
         0.00337801, 0.00203866, 0.0022047 , 0.0015348 , 0.00158178,
         0.00164671, 0.00258812, 0.00135143, 0.00121782, 0.00140212,
         0.00246896, 0.00174961, 0.00169029, 0.00187462, 0.00161548,
         0.00165208, 0.00153087, 0.00732317, 0.00317947, 0.0018194 ,
         0.00150529, 0.00116998, 0.00140415, 0.00130118, 0.00150096,
         0.00173298, 0.0031494 , 0.00230001, 0.00208951, 0.00189051,
         0.00198318, 0.0028261 , 0.00303971, 0.00232562, 0.00138071,
         0.00168765, 0.00180258, 0.00147437, 0.00120828, 0.00109467,
         0.00251158, 0.00163071, 0.00128592, 0.00158271, 0.00147648,
         0.00188572, 0.00192721, 0.00154   , 0.00275976, 0.00232251,
         0.00140823, 0.00180374, 0.00132977, 0.00139987, 0.00179331,

In [20]:
len(dicts_with_attention_keywords)

2

In [21]:
filtered_valid_chunks = dymamic_filter_uniform_words(valid_chunks, IDF_THRESHOLD)
filtered_valid_chunks

(['https frrn section relate dramatic improvement cnn bring about increase demand algorithm context autonomous drive annotate crucial order deep multiple new dataset release encourage far research area include virtual cityscape focus cityscape recent scale dataset consist real world imagery well curate annotation give their success will constrain literature review deep learn base deep learn over last year most base neural early constrain their bottom up follow base rather than classify entire first place et al perform wise feature originate multiple scale follow aggregation these noisy prediction over superpixel introduction so call long et al open wide range research end end long et al far reformulate popular enable pretraine skip connection add which allow information propagate directly early layer deeply layer',
  'reference reference reference reference task assign set predefine class label important tool complex relationship entity usually find street scene car pedestrian road or sidewalk automotive it various way pre process step discard that unlikely contain interest reference detection reference reference reference example abstract structure fullresolution residual two process stream residual stream stay full pool stream undergoe sequence pool unpoole operation two process stream couple full residual unit or combination 3d scene geometry reference reference many those application require precise therefore pursue goal achieve quality precise adherence current state art all employ some form that take input probability map each class many paper rely that already prove variant resnet or start pre net where number weight target task can pre set auxiliary task reduce time often yield superior compare scratch limit target application'],
 1.5)

In [22]:
filtered_valid_chunks[0]

['https frrn section relate dramatic improvement cnn bring about increase demand algorithm context autonomous drive annotate crucial order deep multiple new dataset release encourage far research area include virtual cityscape focus cityscape recent scale dataset consist real world imagery well curate annotation give their success will constrain literature review deep learn base deep learn over last year most base neural early constrain their bottom up follow base rather than classify entire first place et al perform wise feature originate multiple scale follow aggregation these noisy prediction over superpixel introduction so call long et al open wide range research end end long et al far reformulate popular enable pretraine skip connection add which allow information propagate directly early layer deeply layer',
 'reference reference reference reference task assign set predefine class label important tool complex relationship entity usually find street scene car pedestrian road or sidewalk automotive it various way pre process step discard that unlikely contain interest reference detection reference reference reference example abstract structure fullresolution residual two process stream residual stream stay full pool stream undergoe sequence pool unpoole operation two process stream couple full residual unit or combination 3d scene geometry reference reference many those application require precise therefore pursue goal achieve quality precise adherence current state art all employ some form that take input probability map each class many paper rely that already prove variant resnet or start pre net where number weight target task can pre set auxiliary task reduce time often yield superior compare scratch limit target application']

In [23]:
cleaned_keywords_by_chunks = []

for key_dict in dicts_with_attention_keywords:

        cleaned_keys_batch = get_keywords_top_attention_clean(key_dict['tokens'], 
                key_dict['attention_weights'], top_k=100)

        cleaned_keywords_by_chunks.append(cleaned_keys_batch)

cleaned_keywords_by_chunks

[[{'word': 'the', 'weight': np.float32(0.004204311)},
  {'word': 'the', 'weight': np.float32(0.003936652)},
  {'word': 'performs', 'weight': np.float32(0.0039064568)},
  {'word': 'on', 'weight': np.float32(0.003398265)},
  {'word': 'training', 'weight': np.float32(0.003206912)},
  {'word': 'constrained', 'weight': np.float32(0.0031933999)},
  {'word': 'opened', 'weight': np.float32(0.0031924634)},
  {'word': 'we', 'weight': np.float32(0.0031579488)},
  {'word': 'classification', 'weight': np.float32(0.0030524763)},
  {'word': 'research', 'weight': np.float32(0.0028580574)},
  {'word': 'classification', 'weight': np.float32(0.002821498)},
  {'word': 'early', 'weight': np.float32(0.0028180352)},
  {'word': 'train', 'weight': np.float32(0.0027581344)},
  {'word': 'to', 'weight': np.float32(0.0027053903)},
  {'word': 'the', 'weight': np.float32(0.0027015836)},
  {'word': 'dataset', 'weight': np.float32(0.0026851872)},
  {'word': 'work', 'weight': np.float32(0.002657178)},
  {'word': 'as', 'weight': np.float32(0.0026388536)},
  {'word': 'rather', 'weight': np.float32(0.002575087)},
  {'word': 'using', 'weight': np.float32(0.0024733632)},
  {'word': 'by', 'weight': np.float32(0.0024637934)},
  {'word': 'neural', 'weight': np.float32(0.002452692)},
  {'word': 'introduction', 'weight': np.float32(0.0024521477)},
  {'word': 'further', 'weight': np.float32(0.00245028)},
  {'word': 'algorithms', 'weight': np.float32(0.002443442)},
  {'word': 'including', 'weight': np.float32(0.0024395096)},
  {'word': 'for', 'weight': np.float32(0.002422047)},
  {'word': 'to', 'weight': np.float32(0.0024176657)},
  {'word': 'work', 'weight': np.float32(0.0023948597)},
  {'word': 'using', 'weight': np.float32(0.002385697)},
  {'word': 'we', 'weight': np.float32(0.0023268245)},
  {'word': 'were', 'weight': np.float32(0.0023222636)},
  {'word': '//', 'weight': np.float32(0.0023085217)},
  {'word': 'datasets', 'weight': np.float32(0.002302439)},
  {'word': 'by', 'weight': np.float32(0.002299812)},
  {'word': 'have', 'weight': np.float32(0.0022869303)},
  {'word': 'crucial', 'weight': np.float32(0.002284828)},
  {'word': 'and', 'weight': np.float32(0.0022716094)},
  {'word': 'improvements', 'weight': np.float32(0.0022660573)},
  {'word': 'approaches', 'weight': np.float32(0.0022625262)},
  {'word': '1', 'weight': np.float32(0.0022619213)},
  {'word': 'enabling', 'weight': np.float32(0.002261162)},
  {'word': 'and', 'weight': np.float32(0.0022496923)},
  {'word': 'networks', 'weight': np.float32(0.0022369754)},
  {'word': 'section:', 'weight': np.float32(0.0022323062)},
  {'word': 'reformulated', 'weight': np.float32(0.0022301082)},
  {'word': 'approaches', 'weight': np.float32(0.0022270824)},
  {'word': 'aggregation', 'weight': np.float32(0.0022236684)},
  {'word': 'this', 'weight': np.float32(0.0022221862)},
  {'word': 'followed', 'weight': np.float32(0.002219202)},
  {'word': 'research', 'weight': np.float32(0.0022175685)},
  {'word': 'annotations', 'weight': np.float32(0.0022060808)},
  {'word': 'using', 'weight': np.float32(0.0021972165)},
  {'word': 'will', 'weight': np.float32(0.0021956167)},
  {'word': 'imagery', 'weight': np.float32(0.0021955133)},
  {'word': 'success', 'weight': np.float32(0.0021803232)},
  {'word': 'approach', 'weight': np.float32(0.0021746128)},
  {'word': 'cityscapes', 'weight': np.float32(0.002155279)},
  {'word': 'improve', 'weight': np.float32(0.0021489174)},
  {'word': '/', 'weight': np.float32(0.0021328982)},
  {'word': 'architecture', 'weight': np.float32(0.0021213377)},
  {'word': 'githubcom', 'weight': np.float32(0.002102536)},
  {'word': 'the', 'weight': np.float32(0.0021012886)},
  {'word': 'cnn', 'weight': np.float32(0.0020930015)},
  {'word': 'for', 'weight': np.float32(0.002083044)},
  {'word': 'our', 'weight': np.float32(0.002078545)},
  {'word': 'long', 'weight': np.float32(0.0020724086)},
  {'word': 'autonomous', 'weight': np.float32(0.00206999)},
  {'word': 'as', 'weight': np.float32(0.002059422)},
  {'word': 'followed', 'weight': np.float32(0.002050034)},
  {'word': 'over', 'weight': np.float32(0.00203886)},
  {'word': 'semantic', 'weight': np.float32(0.002034304)},
  {'word': 'pixel', 'weight': np.float32(0.0020287503)},
  {'word': 'from', 'weight': np.float32(0.0020182382)},
  {'word': 'architectures', 'weight': np.float32(0.0020094835)},
  {'word': '/', 'weight': np.float32(0.0020070109)},
  {'word': 'network', 'weight': np.float32(0.0020058032)},
  {'word': 'which', 'weight': np.float32(0.0019957756)},
  {'word': 'semantic', 'weight': np.float32(0.0019932906)},
  {'word': 'a', 'weight': np.float32(0.0019886235)},
  {'word': 'image', 'weight': np.float32(0.0019860913)},
  {'word': 'on', 'weight': np.float32(0.0019799187)},
  {'word': 'focus', 'weight': np.float32(0.001978835)},
  {'word': 'given', 'weight': np.float32(0.0019556037)},
  {'word': 'their', 'weight': np.float32(0.0019550854)},
  {'word': 'successful', 'weight': np.float32(0.001952219)},
  {'word': 'at', 'weight': np.float32(0.0019510459)},
  {'word': 'learning', 'weight': np.float32(0.0019487985)},
  {'word': 'classifying', 'weight': np.float32(0.0019448819)},
  {'word': 'virtual', 'weight': np.float32(0.0019432703)},
  {'word': 'approaches', 'weight': np.float32(0.0019363195)},
  {'word': 'such', 'weight': np.float32(0.0019351019)},
  {'word': 'predictions', 'weight': np.float32(0.0019271597)},
  {'word': 'the', 'weight': np.float32(0.001925978)},
  {'word': 'fully', 'weight': np.float32(0.0019225173)},
  {'word': 'this', 'weight': np.float32(0.0019218962)},
  {'word': 'is', 'weight': np.float32(0.0019205874)},
  {'word': 'models', 'weight': np.float32(0.0019194022)},
  {'word': 'in', 'weight': np.float32(0.0019132466)},
  {'word': 'multiple', 'weight': np.float32(0.0019005021)}],
 [{'word': 'modeling', 'weight': np.float32(0.003719972)},
  {'word': 'task', 'weight': np.float32(0.0036683218)},
  {'word': 'it', 'weight': np.float32(0.0036394533)},
  {'word': 'the', 'weight': np.float32(0.0034667244)},
  {'word': 'we', 'weight': np.float32(0.00337801)},
  {'word': 'the', 'weight': np.float32(0.003310318)},
  {'word': 'current', 'weight': np.float32(0.0031794677)},
  {'word': 'approaches', 'weight': np.float32(0.0031493956)},
  {'word': 'employ', 'weight': np.float32(0.0030397072)},
  {'word': 'assigning', 'weight': np.float32(0.0030230973)},
  {'word': 'classification', 'weight': np.float32(0.0029087598)},
  {'word': 'the', 'weight': np.float32(0.0028830364)},
  {'word': 'example', 'weight': np.float32(0.002854088)},
  {'word': 'discard', 'weight': np.float32(0.002842721)},
  {'word': 'all', 'weight': np.float32(0.0028261032)},
  {'word': 'work', 'weight': np.float32(0.002824873)},
  {'word': 'is', 'weight': np.float32(0.0027812968)},
  {'word': 'that', 'weight': np.float32(0.0027597568)},
  {'word': 'training', 'weight': np.float32(0.0027447492)},
  {'word': 'starting', 'weight': np.float32(0.002693846)},
  {'word': 'require', 'weight': np.float32(0.0026839064)},
  {'word': 'the', 'weight': np.float32(0.0026715458)},
  {'word': 'our', 'weight': np.float32(0.002650516)},
  {'word': 'operations', 'weight': np.float32(0.0026250305)},
  {'word': 'achieving', 'weight': np.float32(0.002588118)},
  {'word': 'automotive', 'weight': np.float32(0.0025584828)},
  {'word': 'using', 'weight': np.float32(0.0025576688)},
  {'word': 'papers', 'weight': np.float32(0.0025516045)},
  {'word': 'or', 'weight': np.float32(0.0025317275)},
  {'word': 'network', 'weight': np.float32(0.0025115798)},
  {'word': 'architectures', 'weight': np.float32(0.0025084075)},
  {'word': 'of', 'weight': np.float32(0.0025036833)},
  {'word': 'task', 'weight': np.float32(0.0025007876)},
  {'word': 'where', 'weight': np.float32(0.002497729)},
  {'word': 'to', 'weight': np.float32(0.0024741418)},
  {'word': 'semantic', 'weight': np.float32(0.0024689632)},
  {'word': 'many', 'weight': np.float32(0.0024618274)},
  {'word': 'applications', 'weight': np.float32(0.0024365503)},
  {'word': 'and', 'weight': np.float32(0.0024338628)},
  {'word': 'detection', 'weight': np.float32(0.0024286306)},
  {'word': 'data', 'weight': np.float32(0.0023897432)},
  {'word': 'pixels', 'weight': np.float32(0.002388696)},
  {'word': 'can', 'weight': np.float32(0.002377504)},
  {'word': 'auxiliary', 'weight': np.float32(0.0023717775)},
  {'word': 'reduces', 'weight': np.float32(0.0023702073)},
  {'word': 'segmentation', 'weight': np.float32(0.0023657253)},
  {'word': 'task', 'weight': np.float32(0.002350516)},
  {'word': 'or', 'weight': np.float32(0.0023276596)},
  {'word': 'some', 'weight': np.float32(0.0023256189)},
  {'word': 'takes', 'weight': np.float32(0.0023225148)},
  {'word': 'for', 'weight': np.float32(0.002300015)},
  {'word': 'are', 'weight': np.float32(0.0022877338)},
  {'word': 'network', 'weight': np.float32(0.0022726888)},
  {'word': 'used', 'weight': np.float32(0.0022661726)},
  {'word': 'using', 'weight': np.float32(0.0022616168)},
  {'word': 'improve', 'weight': np.float32(0.00225945)},
  {'word': 'semantic', 'weight': np.float32(0.0022567553)},
  {'word': 'coupled', 'weight': np.float32(0.0022433184)},
  {'word': 'this', 'weight': np.float32(0.002221039)},
  {'word': 'weights', 'weight': np.float32(0.002218139)},
  {'word': 'such', 'weight': np.float32(0.0022065556)},
  {'word': 'pursue', 'weight': np.float32(0.002204703)},
  {'word': 'classification', 'weight': np.float32(0.0022037975)},
  {'word': 'has', 'weight': np.float32(0.0021773744)},
  {'word': 'class', 'weight': np.float32(0.002174602)},
  {'word': 'stays', 'weight': np.float32(0.0021679413)},
  {'word': 'in', 'weight': np.float32(0.00214011)},
  {'word': '][', 'weight': np.float32(0.0021184813)},
  {'word': 'reference],', 'weight': np.float32(0.0021173486)},
  {'word': 'network', 'weight': np.float32(0.0021094864)},
  {'word': '][', 'weight': np.float32(0.0021073478)},
  {'word': 'many', 'weight': np.float32(0.0020964416)},
  {'word': 'image', 'weight': np.float32(0.0020895097)},
  {'word': 'usually', 'weight': np.float32(0.0020834235)},
  {'word': '][', 'weight': np.float32(0.0020803376)},
  {'word': 'image', 'weight': np.float32(0.0020789295)},
  {'word': 'application', 'weight': np.float32(0.0020525798)},
  {'word': 'network', 'weight': np.float32(0.002049728)},
  {'word': 'semantic', 'weight': np.float32(0.0020469143)},
  {'word': 'therefore', 'weight': np.float32(0.0020386574)},
  {'word': 'nets', 'weight': np.float32(0.0020314546)},
  {'word': '][', 'weight': np.float32(0.002006839)},
  {'word': 'target', 'weight': np.float32(0.00200168)},
  {'word': '][', 'weight': np.float32(0.0019979437)},
  {'word': 'geometry', 'weight': np.float32(0.001991266)},
  {'word': 'boundaries', 'weight': np.float32(0.0019832544)},
  {'word': 'variants', 'weight': np.float32(0.001959779)},
  {'word': 'by', 'weight': np.float32(0.0019494471)},
  {'word': 'network', 'weight': np.float32(0.001947615)},
  {'word': 'to', 'weight': np.float32(0.0019463887)},
  {'word': '][', 'weight': np.float32(0.0019456911)},
  {'word': 'segmentation', 'weight': np.float32(0.0019368466)},
  {'word': '][', 'weight': np.float32(0.001936137)},
  {'word': 'unlikely', 'weight': np.float32(0.0019270518)},
  {'word': 'reference],', 'weight': np.float32(0.0019263604)},
  {'word': 'and', 'weight': np.float32(0.0019196671)},
  {'word': 'often', 'weight': np.float32(0.0019116271)},
  {'word': 'for', 'weight': np.float32(0.0019110851)},
  {'word': 'architecture', 'weight': np.float32(0.001908165)},
  {'word': 'from', 'weight': np.float32(0.0019069443)}]]

In [24]:
len(cleaned_keywords_by_chunks)

2

In [25]:
filtered_keywords_by_chunks = []

for key_dict, filtered_chunk in zip(cleaned_keywords_by_chunks, filtered_valid_chunks[0]):

    filtered_keywords_by_chunks.append(filter_words_by_text(key_dict, filtered_chunk))

filtered_keywords_by_chunks

[[{'word': 'research', 'weight': np.float32(0.0028580574)},
  {'word': 'early', 'weight': np.float32(0.0028180352)},
  {'word': 'dataset', 'weight': np.float32(0.0026851872)},
  {'word': 'rather', 'weight': np.float32(0.002575087)},
  {'word': 'neural', 'weight': np.float32(0.002452692)},
  {'word': 'introduction', 'weight': np.float32(0.0024521477)},
  {'word': 'crucial', 'weight': np.float32(0.002284828)},
  {'word': 'aggregation', 'weight': np.float32(0.0022236684)},
  {'word': 'research', 'weight': np.float32(0.0022175685)},
  {'word': 'will', 'weight': np.float32(0.0021956167)},
  {'word': 'imagery', 'weight': np.float32(0.0021955133)},
  {'word': 'success', 'weight': np.float32(0.0021803232)},
  {'word': 'cnn', 'weight': np.float32(0.0020930015)},
  {'word': 'long', 'weight': np.float32(0.0020724086)},
  {'word': 'autonomous', 'weight': np.float32(0.00206999)},
  {'word': 'over', 'weight': np.float32(0.00203886)},
  {'word': 'which', 'weight': np.float32(0.0019957756)},
  {'word': 'focus', 'weight': np.float32(0.001978835)},
  {'word': 'their', 'weight': np.float32(0.0019550854)},
  {'word': 'virtual', 'weight': np.float32(0.0019432703)},
  {'word': 'multiple', 'weight': np.float32(0.0019005021)}],
 [{'word': 'task', 'weight': np.float32(0.0036683218)},
  {'word': 'it', 'weight': np.float32(0.0036394533)},
  {'word': 'current', 'weight': np.float32(0.0031794677)},
  {'word': 'employ', 'weight': np.float32(0.0030397072)},
  {'word': 'example', 'weight': np.float32(0.002854088)},
  {'word': 'discard', 'weight': np.float32(0.002842721)},
  {'word': 'all', 'weight': np.float32(0.0028261032)},
  {'word': 'that', 'weight': np.float32(0.0027597568)},
  {'word': 'require', 'weight': np.float32(0.0026839064)},
  {'word': 'automotive', 'weight': np.float32(0.0025584828)},
  {'word': 'or', 'weight': np.float32(0.0025317275)},
  {'word': 'task', 'weight': np.float32(0.0025007876)},
  {'word': 'where', 'weight': np.float32(0.002497729)},
  {'word': 'many', 'weight': np.float32(0.0024618274)},
  {'word': 'detection', 'weight': np.float32(0.0024286306)},
  {'word': 'can', 'weight': np.float32(0.002377504)},
  {'word': 'auxiliary', 'weight': np.float32(0.0023717775)},
  {'word': 'task', 'weight': np.float32(0.002350516)},
  {'word': 'or', 'weight': np.float32(0.0023276596)},
  {'word': 'some', 'weight': np.float32(0.0023256189)},
  {'word': 'pursue', 'weight': np.float32(0.002204703)},
  {'word': 'class', 'weight': np.float32(0.002174602)},
  {'word': 'many', 'weight': np.float32(0.0020964416)},
  {'word': 'usually', 'weight': np.float32(0.0020834235)},
  {'word': 'application', 'weight': np.float32(0.0020525798)},
  {'word': 'therefore', 'weight': np.float32(0.0020386574)},
  {'word': 'target', 'weight': np.float32(0.00200168)},
  {'word': 'geometry', 'weight': np.float32(0.001991266)},
  {'word': 'unlikely', 'weight': np.float32(0.0019270518)},
  {'word': 'often', 'weight': np.float32(0.0019116271)}]]

In [26]:
all_filtered_keywords = merge_and_deduplicate_word_arrays(filtered_keywords_by_chunks)

all_filtered_keywords

[{'word': 'task', 'weight': 0.0036683217622339725},
 {'word': 'it', 'weight': 0.003639453323557973},
 {'word': 'current', 'weight': 0.003179467748850584},
 {'word': 'employ', 'weight': 0.0030397071968764067},
 {'word': 'research', 'weight': 0.0028580573853105307},
 {'word': 'example', 'weight': 0.0028540880884975195},
 {'word': 'discard', 'weight': 0.002842721063643694},
 {'word': 'all', 'weight': 0.0028261032421141863},
 {'word': 'early', 'weight': 0.0028180351946502924},
 {'word': 'that', 'weight': 0.002759756753221154},
 {'word': 'dataset', 'weight': 0.0026851871516555548},
 {'word': 'require', 'weight': 0.002683906350284815},
 {'word': 'rather', 'weight': 0.002575086895376444},
 {'word': 'automotive', 'weight': 0.002558482810854912},
 {'word': 'or', 'weight': 0.0025317275431007147},
 {'word': 'where', 'weight': 0.0024977289140224457},
 {'word': 'many', 'weight': 0.0024618273600935936},
 {'word': 'neural', 'weight': 0.0024526920169591904},
 {'word': 'introduction', 'weight': 0.0024521476589143276},
 {'word': 'detection', 'weight': 0.0024286305997520685},
 {'word': 'can', 'weight': 0.0023775040172040462},
 {'word': 'auxiliary', 'weight': 0.0023717775475233793},
 {'word': 'some', 'weight': 0.0023256188724189997},
 {'word': 'crucial', 'weight': 0.00228482810780406},
 {'word': 'aggregation', 'weight': 0.002223668387159705},
 {'word': 'pursue', 'weight': 0.0022047029342502356},
 {'word': 'will', 'weight': 0.0021956167183816433},
 {'word': 'imagery', 'weight': 0.002195513341575861},
 {'word': 'success', 'weight': 0.002180323237553239},
 {'word': 'class', 'weight': 0.0021746018901467323},
 {'word': 'cnn', 'weight': 0.002093001501634717},
 {'word': 'usually', 'weight': 0.0020834235474467278},
 {'word': 'long', 'weight': 0.002072408562526107},
 {'word': 'autonomous', 'weight': 0.0020699899177998304},
 {'word': 'application', 'weight': 0.0020525797735899687},
 {'word': 'over', 'weight': 0.0020388599950820208},
 {'word': 'therefore', 'weight': 0.002038657432422042},
 {'word': 'target', 'weight': 0.0020016799680888653},
 {'word': 'which', 'weight': 0.001995775615796447},
 {'word': 'geometry', 'weight': 0.001991265919059515},
 {'word': 'focus', 'weight': 0.001978835090994835},
 {'word': 'their', 'weight': 0.0019550854340195656},
 {'word': 'virtual', 'weight': 0.0019432703265920281},
 {'word': 'unlikely', 'weight': 0.0019270518096163869},
 {'word': 'often', 'weight': 0.0019116271287202835},
 {'word': 'multiple', 'weight': 0.0019005021313205361}]

In [27]:
all_filtered_keywords = postprocess_words_array(all_filtered_keywords)
all_filtered_keywords

[{'word': 'task', 'weight': 0.0036683217622339725},
 {'word': 'current', 'weight': 0.003179467748850584},
 {'word': 'employ', 'weight': 0.0030397071968764067},
 {'word': 'research', 'weight': 0.0028580573853105307},
 {'word': 'example', 'weight': 0.0028540880884975195},
 {'word': 'discard', 'weight': 0.002842721063643694},
 {'word': 'dataset', 'weight': 0.0026851871516555548},
 {'word': 'require', 'weight': 0.002683906350284815},
 {'word': 'automotive', 'weight': 0.002558482810854912},
 {'word': 'neural', 'weight': 0.0024526920169591904},
 {'word': 'introduction', 'weight': 0.0024521476589143276},
 {'word': 'detection', 'weight': 0.0024286305997520685},
 {'word': 'auxiliary', 'weight': 0.0023717775475233793},
 {'word': 'crucial', 'weight': 0.00228482810780406},
 {'word': 'aggregation', 'weight': 0.002223668387159705},
 {'word': 'pursue', 'weight': 0.0022047029342502356},
 {'word': 'imagery', 'weight': 0.002195513341575861},
 {'word': 'success', 'weight': 0.002180323237553239},
 {'word': 'class', 'weight': 0.0021746018901467323},
 {'word': 'cnn', 'weight': 0.002093001501634717},
 {'word': 'long', 'weight': 0.002072408562526107},
 {'word': 'autonomous', 'weight': 0.0020699899177998304},
 {'word': 'application', 'weight': 0.0020525797735899687},
 {'word': 'target', 'weight': 0.0020016799680888653},
 {'word': 'geometry', 'weight': 0.001991265919059515},
 {'word': 'focus', 'weight': 0.001978835090994835},
 {'word': 'virtual', 'weight': 0.0019432703265920281},
 {'word': 'multiple', 'weight': 0.0019005021313205361}]

In [28]:
ls_filtered_keywords = get_lemm_stemm_words(all_filtered_keywords)

In [29]:
ls_filtered_keywords

[{'word': 'task',
  'lemma': 'task',
  'stem': 'task',
  'weight': 0.0036683217622339725},
 {'word': 'current',
  'lemma': 'current',
  'stem': 'current',
  'weight': 0.003179467748850584},
 {'word': 'employ',
  'lemma': 'employ',
  'stem': 'employ',
  'weight': 0.0030397071968764067},
 {'word': 'research',
  'lemma': 'research',
  'stem': 'research',
  'weight': 0.0028580573853105307},
 {'word': 'example',
  'lemma': 'example',
  'stem': 'exampl',
  'weight': 0.0028540880884975195},
 {'word': 'discard',
  'lemma': 'discard',
  'stem': 'discard',
  'weight': 0.002842721063643694},
 {'word': 'dataset',
  'lemma': 'dataset',
  'stem': 'dataset',
  'weight': 0.0026851871516555548},
 {'word': 'require',
  'lemma': 'require',
  'stem': 'requir',
  'weight': 0.002683906350284815},
 {'word': 'automotive',
  'lemma': 'automotive',
  'stem': 'automot',
  'weight': 0.002558482810854912},
 {'word': 'neural',
  'lemma': 'neural',
  'stem': 'neural',
  'weight': 0.0024526920169591904},
 {'word': 'introduction',
  'lemma': 'introduction',
  'stem': 'introduct',
  'weight': 0.0024521476589143276},
 {'word': 'detection',
  'lemma': 'detection',
  'stem': 'detect',
  'weight': 0.0024286305997520685},
 {'word': 'auxiliary',
  'lemma': 'auxiliary',
  'stem': 'auxiliari',
  'weight': 0.0023717775475233793},
 {'word': 'crucial',
  'lemma': 'crucial',
  'stem': 'crucial',
  'weight': 0.00228482810780406},
 {'word': 'aggregation',
  'lemma': 'aggregation',
  'stem': 'aggreg',
  'weight': 0.002223668387159705},
 {'word': 'pursue',
  'lemma': 'pursue',
  'stem': 'pursu',
  'weight': 0.0022047029342502356},
 {'word': 'imagery',
  'lemma': 'imagery',
  'stem': 'imageri',
  'weight': 0.002195513341575861},
 {'word': 'success',
  'lemma': 'success',
  'stem': 'success',
  'weight': 0.002180323237553239},
 {'word': 'class',
  'lemma': 'class',
  'stem': 'class',
  'weight': 0.0021746018901467323},
 {'word': 'cnn',
  'lemma': 'cnn',
  'stem': 'cnn',
  'weight': 0.002093001501634717},
 {'word': 'long',
  'lemma': 'long',
  'stem': 'long',
  'weight': 0.002072408562526107},
 {'word': 'autonomous',
  'lemma': 'autonomous',
  'stem': 'autonom',
  'weight': 0.0020699899177998304},
 {'word': 'application',
  'lemma': 'application',
  'stem': 'applic',
  'weight': 0.0020525797735899687},
 {'word': 'target',
  'lemma': 'target',
  'stem': 'target',
  'weight': 0.0020016799680888653},
 {'word': 'geometry',
  'lemma': 'geometry',
  'stem': 'geometri',
  'weight': 0.001991265919059515},
 {'word': 'focus',
  'lemma': 'focus',
  'stem': 'focus',
  'weight': 0.001978835090994835},
 {'word': 'virtual',
  'lemma': 'virtual',
  'stem': 'virtual',
  'weight': 0.0019432703265920281},
 {'word': 'multiple',
  'lemma': 'multiple',
  'stem': 'multipl',
  'weight': 0.0019005021313205361}]

In [30]:
ls_filtered_keywords = filter_keywords_from_dict(
                            keywords_with_weights = ls_filtered_keywords,
                            them_asp = them_aspect,
                            antireference = reference_answers[0]
)

ls_filtered_keywords

[{'word': 'task',
  'lemma': 'task',
  'stem': 'task',
  'weight': 0.0036683217622339725,
  'score_diff': np.float32(0.40358943)},
 {'word': 'require',
  'lemma': 'require',
  'stem': 'requir',
  'weight': 0.002683906350284815,
  'score_diff': np.float32(0.30358487)},
 {'word': 'employ',
  'lemma': 'employ',
  'stem': 'employ',
  'weight': 0.0030397071968764067,
  'score_diff': np.float32(0.2867719)},
 {'word': 'crucial',
  'lemma': 'crucial',
  'stem': 'crucial',
  'weight': 0.00228482810780406,
  'score_diff': np.float32(0.26436627)},
 {'word': 'focus',
  'lemma': 'focus',
  'stem': 'focus',
  'weight': 0.001978835090994835,
  'score_diff': np.float32(0.21515632)},
 {'word': 'long',
  'lemma': 'long',
  'stem': 'long',
  'weight': 0.002072408562526107,
  'score_diff': np.float32(0.20282865)},
 {'word': 'application',
  'lemma': 'application',
  'stem': 'applic',
  'weight': 0.0020525797735899687,
  'score_diff': np.float32(0.17649734)},
 {'word': 'research',
  'lemma': 'research',
  'stem': 'research',
  'weight': 0.0028580573853105307,
  'score_diff': np.float32(0.16921246)},
 {'word': 'auxiliary',
  'lemma': 'auxiliary',
  'stem': 'auxiliari',
  'weight': 0.0023717775475233793,
  'score_diff': np.float32(0.16079235)},
 {'word': 'success',
  'lemma': 'success',
  'stem': 'success',
  'weight': 0.002180323237553239,
  'score_diff': np.float32(0.15439016)},
 {'word': 'target',
  'lemma': 'target',
  'stem': 'target',
  'weight': 0.0020016799680888653,
  'score_diff': np.float32(0.15338182)},
 {'word': 'detection',
  'lemma': 'detection',
  'stem': 'detect',
  'weight': 0.0024286305997520685,
  'score_diff': np.float32(0.123521805)},
 {'word': 'pursue',
  'lemma': 'pursue',
  'stem': 'pursu',
  'weight': 0.0022047029342502356,
  'score_diff': np.float32(0.1143105)},
 {'word': 'class',
  'lemma': 'class',
  'stem': 'class',
  'weight': 0.0021746018901467323,
  'score_diff': np.float32(0.07146126)},
 {'word': 'current',
  'lemma': 'current',
  'stem': 'current',
  'weight': 0.003179467748850584,
  'score_diff': np.float32(0.04848516)},
 {'word': 'example',
  'lemma': 'example',
  'stem': 'exampl',
  'weight': 0.0028540880884975195,
  'score_diff': np.float32(0.041388273)},
 {'word': 'imagery',
  'lemma': 'imagery',
  'stem': 'imageri',
  'weight': 0.002195513341575861,
  'score_diff': np.float32(0.008915663)},
 {'word': 'dataset',
  'lemma': 'dataset',
  'stem': 'dataset',
  'weight': 0.0026851871516555548,
  'score_diff': np.float32(0.00010681152)}]

In [31]:
len(ls_filtered_keywords)

18

In [32]:
def extra_score_chunks_by_keywords(
    chunks: List[TextChunk], 
    keywords: List[dict],
    case_sensitive: bool = False,
    use_combined_weights: bool = True,
    weight_ratio: float = 0.5,  # Соотношение между weight и score_diff (0.5 = равное значение)
    min_matches: int = 1
) -> List[ScoredChunk]:
    """
    Оценивает фрагменты на основе количества и важности ключевых слов.
    Учитывает оба веса: weight (из модели внимания) и score_diff (из сравнения с эталонами).
    
    Параметры:
        chunks: Список объектов TextChunk для оценки
        keywords: Список словарей формата [{"word": str, "lemma": str, "stem": str, 
                 "weight": float, "score_diff": float}, ...]
        case_sensitive: Учитывать регистр при поиске
        use_combined_weights: Использовать комбинированные веса (weight и score_diff)
        weight_ratio: Соотношение между weight и score_diff (0.0 - только score_diff, 1.0 - только weight)
        min_matches: Минимальное количество совпадений для включения фрагмента в результат
    
    Возвращает:
        Список объектов ScoredChunk с оценками и информацией о совпадениях
    """
    if not keywords or not chunks:
        return []
    
    # Подготавливаем ключевые слова и их комбинированные веса
    keyword_weights = {}
    search_terms = set()
    term_to_keyword = {}
    
    for keyword in keywords:
        word = keyword['word']
        
        # Вычисляем комбинированный вес
        weight = keyword.get('weight', 1.0)
        score_diff = keyword.get('score_diff', 1.0)
        
        if use_combined_weights:
            # Комбинируем веса с учетом соотношения
            combined_weight = (weight * weight_ratio) + (score_diff * (1 - weight_ratio))
        else:
            # Используем только score_diff (по умолчанию)
            combined_weight = score_diff
        
        keyword_weights[word] = combined_weight
        
        # Добавляем лемму и стем для поиска
        lemma = keyword.get('lemma', word)
        stem = keyword.get('stem', word)
        
        search_terms.add(lemma)
        search_terms.add(stem)
        
        term_to_keyword[lemma.lower()] = word
        term_to_keyword[stem.lower()] = word
    
    # Создаем regex-паттерн для поиска
    pattern = re.compile(
        r'\b(?:{})\b'.format('|'.join(map(re.escape, search_terms))),
        flags=0 if case_sensitive else re.IGNORECASE
    )
    
    scored_chunks = []
    
    for chunk in chunks:
        # Находим все совпадения терминов в тексте
        text_to_search = chunk.text if case_sensitive else chunk.text.lower()
        found_terms = pattern.findall(text_to_search)
        
        # Собираем уникальные найденные ключевые слова и их веса
        matched_keywords = set()
        total_score = 0.0
        
        for term in found_terms:
            normalized_term = term if case_sensitive else term.lower()
            if normalized_term in term_to_keyword:
                keyword_word = term_to_keyword[normalized_term]
                if keyword_word not in matched_keywords:
                    matched_keywords.add(keyword_word)
                    total_score += keyword_weights.get(keyword_word, 1.0)
        
        # Применяем дополнительные факторы для улучшения оценки
        if matched_keywords:
            # Нормализуем по количеству слов в фрагменте
            normalization_factor = 1.0 + (len(matched_keywords) / max(1, chunk.word_token_count / 10))
            
            # Учитываем плотность ключевых слов
            density_bonus = min(2.0, 1.0 + (len(matched_keywords) / max(1, len(chunk.text.split()) / 20)))
            
            final_score = total_score * normalization_factor * density_bonus
            
            if len(matched_keywords) >= min_matches:
                scored_chunks.append(ScoredChunk(
                    chunk=chunk,
                    score=final_score,
                    matched_keywords=list(matched_keywords),
                    keyword_scores={kw: keyword_weights.get(kw, 1.0) for kw in matched_keywords},
                    # Добавляем информацию об исходных весах
                    original_weights={kw: {
                        'weight': next((k['weight'] for k in keywords if k['word'] == kw), 1.0),
                        'score_diff': next((k['score_diff'] for k in keywords if k['word'] == kw), 1.0)
                    } for kw in matched_keywords}
                ))
    
    # Сортируем по убыванию оценки
    scored_chunks.sort(key=lambda x: x.score, reverse=True)
    
    return scored_chunks

# Расширенная версия с учетом обоих весов
def extra_score_chunks_advanced(
    chunks: List[TextChunk], 
    keywords: List[dict],
    case_sensitive: bool = False,
    min_matches: int = 1,
    position_weight: float = 0.3,
    frequency_weight: float = 0.7,
    weight_ratio: float = 0.5  # Соотношение между weight и score_diff
) -> List[ScoredChunk]:
    """
    Расширенная версия оценки фрагментов с учетом позиции и частоты ключевых слов.
    Учитывает оба веса: weight и score_diff.
    """
    if not keywords or not chunks:
        return []
    
    # Подготавливаем ключевые слова с комбинированными весами
    keyword_weights = {}
    search_terms = set()
    term_to_keyword = {}
    
    for keyword in keywords:
        word = keyword['word']
        
        # Комбинируем веса
        weight = keyword.get('weight', 1.0)
        score_diff = keyword.get('score_diff', 1.0)
        combined_weight = (weight * weight_ratio) + (score_diff * (1 - weight_ratio))
        
        keyword_weights[word] = combined_weight
        
        lemma = keyword.get('lemma', word)
        stem = keyword.get('stem', word)
        
        search_terms.add(lemma)
        search_terms.add(stem)
        
        term_to_keyword[lemma.lower()] = word
        term_to_keyword[stem.lower()] = word
    
    pattern = re.compile(
        r'\b(?:{})\b'.format('|'.join(map(re.escape, search_terms))),
        flags=0 if case_sensitive else re.IGNORECASE
    )
    
    scored_chunks = []
    
    for chunk in chunks:
        text_to_search = chunk.text if case_sensitive else chunk.text.lower()
        found_matches = list(pattern.finditer(text_to_search))
        
        if not found_matches:
            continue
        
        # Анализируем совпадения
        matched_keywords = set()
        position_scores = []
        keyword_frequencies = {}
        
        for match in found_matches:
            term = match.group()
            normalized_term = term if case_sensitive else term.lower()
            
            if normalized_term in term_to_keyword:
                keyword_word = term_to_keyword[normalized_term]
                matched_keywords.add(keyword_word)
                
                # Оценка позиции (слова в начале текста более важны)
                position = match.start() / max(1, len(text_to_search))
                position_score = 1.0 - position  # чем раньше, тем выше оценка
                position_scores.append(position_score)
                
                # Подсчет частоты
                keyword_frequencies[keyword_word] = keyword_frequencies.get(keyword_word, 0) + 1
        
        if len(matched_keywords) >= min_matches:
            # Вычисляем общую оценку с учетом комбинированных весов
            base_score = sum(keyword_weights.get(kw, 1.0) for kw in matched_keywords)
            
            # Учитываем позицию (средняя оценка позиций)
            avg_position_score = np.mean(position_scores) if position_scores else 0.5
            position_contribution = 1.0 + position_weight * avg_position_score
            
            # Учитываем частоту (логарифмическая шкала для избежания перекоса)
            freq_contribution = 1.0 + frequency_weight * np.log1p(sum(keyword_frequencies.values()))
            
            # Учитываем уникальность (количество разных ключевых слов)
            uniqueness_bonus = 1.0 + (len(matched_keywords) / len(keywords)) * 0.5
            
            final_score = base_score * position_contribution * freq_contribution * uniqueness_bonus
            
            scored_chunks.append(ScoredChunk(
                chunk=chunk,
                score=final_score,
                matched_keywords=list(matched_keywords),
                keyword_scores=keyword_frequencies,
                # Добавляем информацию об исходных весах
                original_weights={kw: {
                    'weight': next((k['weight'] for k in keywords if k['word'] == kw), 1.0),
                    'score_diff': next((k['score_diff'] for k in keywords if k['word'] == kw), 1.0),
                    'combined_weight': keyword_weights.get(kw, 1.0)
                } for kw in matched_keywords}
            ))
    
    scored_chunks.sort(key=lambda x: x.score, reverse=True)
    return scored_chunks

In [33]:
# Использование только score_diff
scored_1 = extra_score_chunks_by_keywords(text_chunks, ls_filtered_keywords, 
                                        weight_ratio=0.0)

print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(scored_1[:5]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Веса: {scored_chunk.original_weights}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

Топ-5 фрагментов по оценке:
1. Оценка: 4.26
   Совпадения: auxiliary, application, employ, current, target, example, detection, task, pursue, require, class
   Веса: {'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the tas...

2. Оценка: 1.80
   Совпадения: research, dataset, focus, crucial, long, imagery, success
   Веса: {'research': {'weight': 0.0028580573853105307, 'score_diff': np.float32(0.16921246)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'focus': {'weight': 0.001978835090994835, 'score_diff': np.float32(0.21515632)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'long': {'weight': 0.002072408562526107, 'score_diff': np.float32(0.20282865)}, 'imagery': {'weight': 0.002195513341575861, 'score_diff': np.float32(0.008915663)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}}
   Текст: 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements ...

3. Оценка: 1.24
   Совпадения: task, auxiliary, target, application
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}}
   Текст: Starting from pre - trained nets, where a large number of weights for the target task can be pre - s...

4. Оценка: 1.19
   Совпадения: dataset, current, crucial, task, class
   Веса: {'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Sem...

5. Оценка: 0.88
   Совпадения: task, dataset, success, class
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Our approach is able to swiftly combine high - and low - resolution information, resulting in alread...

In [34]:
# Использование только weight
scored_2 = extra_score_chunks_by_keywords(text_chunks, ls_filtered_keywords, 
                                        weight_ratio=1.0)

print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(scored_2[:5]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Веса: {scored_chunk.original_weights}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

Топ-5 фрагментов по оценке:
1. Оценка: 0.06
   Совпадения: auxiliary, application, employ, current, target, example, detection, task, pursue, require, class
   Веса: {'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the tas...

2. Оценка: 0.03
   Совпадения: research, dataset, focus, crucial, long, imagery, success
   Веса: {'research': {'weight': 0.0028580573853105307, 'score_diff': np.float32(0.16921246)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'focus': {'weight': 0.001978835090994835, 'score_diff': np.float32(0.21515632)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'long': {'weight': 0.002072408562526107, 'score_diff': np.float32(0.20282865)}, 'imagery': {'weight': 0.002195513341575861, 'score_diff': np.float32(0.008915663)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}}
   Текст: 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements ...

3. Оценка: 0.02
   Совпадения: dataset, current, crucial, task, class
   Веса: {'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Sem...

4. Оценка: 0.01
   Совпадения: task, dataset, success, class
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Our approach is able to swiftly combine high - and low - resolution information, resulting in alread...

5. Оценка: 0.01
   Совпадения: task, auxiliary, target, application
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}}
   Текст: Starting from pre - trained nets, where a large number of weights for the target task can be pre - s...

In [35]:
# Равное сочетание обоих весов (по умолчанию)
scored_3 = extra_score_chunks_by_keywords(text_chunks, ls_filtered_keywords, 
                                        weight_ratio=0.5)

print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(scored_3[:5]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Веса: {scored_chunk.original_weights}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

Топ-5 фрагментов по оценке:
1. Оценка: 2.16
   Совпадения: auxiliary, application, employ, current, target, example, detection, task, pursue, require, class
   Веса: {'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the tas...

2. Оценка: 0.91
   Совпадения: research, dataset, focus, crucial, long, imagery, success
   Веса: {'research': {'weight': 0.0028580573853105307, 'score_diff': np.float32(0.16921246)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'focus': {'weight': 0.001978835090994835, 'score_diff': np.float32(0.21515632)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'long': {'weight': 0.002072408562526107, 'score_diff': np.float32(0.20282865)}, 'imagery': {'weight': 0.002195513341575861, 'score_diff': np.float32(0.008915663)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}}
   Текст: 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements ...

3. Оценка: 0.63
   Совпадения: task, auxiliary, target, application
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}}
   Текст: Starting from pre - trained nets, where a large number of weights for the target task can be pre - s...

4. Оценка: 0.61
   Совпадения: dataset, current, crucial, task, class
   Веса: {'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Sem...

5. Оценка: 0.45
   Совпадения: task, dataset, success, class
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Our approach is able to swiftly combine high - and low - resolution information, resulting in alread...

In [36]:
# Преимущество weight (70% weight, 30% score_diff)
scored_4 = extra_score_chunks_by_keywords(text_chunks, ls_filtered_keywords, 
                                        weight_ratio=0.7)

print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(scored_4[:5]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Веса: {scored_chunk.original_weights}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

Топ-5 фрагментов по оценке:
1. Оценка: 1.32
   Совпадения: auxiliary, application, employ, current, target, example, detection, task, pursue, require, class
   Веса: {'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the tas...

2. Оценка: 0.56
   Совпадения: research, dataset, focus, crucial, long, imagery, success
   Веса: {'research': {'weight': 0.0028580573853105307, 'score_diff': np.float32(0.16921246)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'focus': {'weight': 0.001978835090994835, 'score_diff': np.float32(0.21515632)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'long': {'weight': 0.002072408562526107, 'score_diff': np.float32(0.20282865)}, 'imagery': {'weight': 0.002195513341575861, 'score_diff': np.float32(0.008915663)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}}
   Текст: 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements ...

3. Оценка: 0.38
   Совпадения: task, auxiliary, target, application
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}}
   Текст: Starting from pre - trained nets, where a large number of weights for the target task can be pre - s...

4. Оценка: 0.37
   Совпадения: dataset, current, crucial, task, class
   Веса: {'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'crucial': {'weight': 0.00228482810780406, 'score_diff': np.float32(0.26436627)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Sem...

5. Оценка: 0.28
   Совпадения: task, dataset, success, class
   Веса: {'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'dataset': {'weight': 0.0026851871516555548, 'score_diff': np.float32(0.00010681152)}, 'success': {'weight': 0.002180323237553239, 'score_diff': np.float32(0.15439016)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}
   Текст: Our approach is able to swiftly combine high - and low - resolution information, resulting in alread...

In [37]:
simp_ans_finder = ScoredAnswerFinder()


question_with_answers1 = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        scored_chunks = scored_1
        )


print("\n---\n---> Founded answers:")
for ans in question_with_answers1.answers:
    print(ans.text)
    print(ans.chunk.score)
    print(ans.confidence)
    print(ans.chunk.chunk.text)
    print("----------------------\n")

Device set to use cuda:1

---
---> Founded answers:
Semantic image segmentation
4.2634473
3.913524415111169e-05
Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.
----------------------

semantic segmentation
1.7991387
0.0005423750844784081
1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.
----------------------

segmentation
1.2425942
8.26989344204776e-06
Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams.
----------------------

assigning a set of predefined class labels to image pixels
1.1895404
0.00040491766412742436
Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.
----------------------

computes a function F
0.8817669
4.02617733925581e-05
Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference].
----------------------

By using the two processing streams together
0.6574852
5.52726341993548e-05
Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.
----------------------

stereo or optical flow
0.3310697
0.010819800023455173
We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .
----------------------

state - of - the - art results even without pre - training
0.29184046
0.0004327117057982832
Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores. To the best of our knowledge, we are the first to show that it is possible to obtain state - of - the - art results even without pre - training. This gives credibility to our claim that network architectures can have a crucial effect on a system 's overall performance. Subsampling Factor. An interesting observation that we made on the Cityscapes test set is a correlation between the subsampling factor and the test performance. This correlation can be seen in Figure 5 where we show the scores of several approaches currently listed on the leader board against their respective subsampling factors. Unsurprisingly, most of the best performers operate on the fullresolution input images. Throughout our experiments, we consistently outperformed other approaches who trained on Mean IoU Score (%) section: Subsampling factor Published Unpublished LRR [reference] Adelaide [reference] Dilation [reference] ENet [reference] SegNet [reference] DeepLab [reference] FRRN A / B Figure 5. Comparison of the mean IoU scores of all approaches on the leader board of the Cityscapes segmentation benchmark based on the subsampling factor of the images that they were trained on. Dilation [reference] LRR [reference] FRRN B Figure 6. The trimap evaluation on the validation set. The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions.
----------------------

smoothing the network predictions
0.28925288
0.0007261462160386145
To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
----------------------

bootstrapped cross - entropy loss
0.2693143
0.0026516092475503683

In [38]:
simp_ans_finder = ScoredAnswerFinder()


question_with_answers2 = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        scored_chunks = scored_2
        )


print("\n---\n---> Founded answers:")
for ans in question_with_answers2.answers:
    print(ans.text)
    print(ans.chunk.score)
    print(ans.confidence)
    print(ans.chunk.chunk.text)
    print("----------------------\n")

Device set to use cuda:1

---
---> Founded answers:
Semantic image segmentation
0.06486309
3.913524415111169e-05
Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.
----------------------

semantic segmentation
0.028813751
0.0005423750844784081
1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.
----------------------

assigning a set of predefined class labels to image pixels
0.021122266
0.00040491766412742436
Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.
----------------------

computes a function F
0.014998615
4.02617733925581e-05
Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference].
----------------------

segmentation
0.014026322
8.26989344204776e-06
Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams.
----------------------

computing the output x n directly
0.0064667147
8.887447620509192e-06
We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference]. In theory, however, the training loss of a shallow network should be an upper bound on the training loss of a corresponding deep network. This is due to the fact that increasing the depth by adding layers strictly increases the expressive power of the model. A deep network can express all functions that the original shallow network can express by using identity mappings for the added layers. Hence a deep network should perform at least as well as the shallower model on the training data. The violation of this principle implied that current training algorithms have difficulties optimizing very deep traditional feedforward networks. He et al. proposed residual networks (ResNets) that exhibit significantly improved training characteristics, allowing network depths that were previously unattainable. A ResNet is composed of a sequence of residual units (RUs). As depicted in Figure 2b, the output x n of the n - th RU in a ResNet is computed as where F (x n−1; W n) is the residual, which is parametrized by W n. Thus, instead of computing the output x n directly, F only computes a residual that is added to the input x n−1. One commonly refers to this design as skip connection, because there is a connection from the input x n−1 to the output x n that skips the actual computation F. It has been empirically observed that ResNets have superior training properties over traditional feedforward networks. This can be explained by an improved gradient flow within the network.
----------------------

By using the two processing streams together
0.006351951
5.52726341993548e-05
Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.
----------------------

Training FRRN B
0.0058060694
0.0007058468763716519
The resulting ResNet has slightly fewer parameters than the original FRRN (16. 7  × 10 6 vs. 17. 7  × 10 6). This is due to the fact that RUs lack the 1 × 1 convolutions that connect the pooling to the residual Table 2. IoU scores from the cityscapes test set. We highlight the best published baselines for the different sampling rates. (Additional anonymous submissions exist as concurrent work. ) Bold numbers represent the best, italic numbers the second best score for a class. We also indicate the subsampling factor used on the input images, whether additional coarsely annotated data was used, and whether the model was initialized with pre - trained weights. stream. section: Method We train both networks on the quarter - resolution Cityscapes dataset for 45, 000 iterations at a batch size of 3. We use a learning rate of 10 −3 for the first 35, 000 iterations and then reduce it to 10 −4 for the following 10, 000 iterations. Both networks converged within these iterations. The FRRN A resulted in a validation set mean IoU score of 65. 7 % while the ResNet baseline only achieved 62. 8 %, showing a significant advantage of our FRRNs. Training FRRN B is performed in a similar fashion. Detailed training curves are shown in Appendix B. section: Quantitative Evaluation Overview In Table 2 we compare our method to the best (published) performers on the Cityscapes leader board, namely LRR [reference], Adelaide [reference], and Dilation [reference]. Note that our network performs on par with the very complex and well engineered system by [reference]. Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores.
----------------------

bootstrapped cross - entropy loss
0.005002299
0.0026516092475503683
We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations. The pooled feature maps are then successively upscaled using bilinear interpolation in the decoder. Furthermore, similar to Simonyan and Zisserman [reference], we define a number of base channels that we double after each pooling operation (up to a certain upper limit). Instead of choosing 64 base channels as in VGG net, we use 48 channels in order to have a manageable number of trainable parameters. Depending on the input image resolution, we use FRRN A or FRRN B to keep the relative size of the receptive fields consistent. section: Training Procedure Following Wu et al. , we train our network by minimizing a bootstrapped cross - entropy loss [reference]. Let c be the number of classes, y 1,. , y N ∈ {1,. , c} be the target class labels for the pixels 1,. , N, and let p i, j be the posterior class + Bias Softmax probability for class j and pixel i. Then, the bootstrapped cross - entropy loss over K pixels is defined as where 1 [x] = 1 iff x is true and t k ∈ R is chosen such that |{i ∈ {1,. , N}: p i, yi < t k} | = K. The threshold parameter t k can easily be determined by sorting the predicted log probabilities and choosing the K + 1 - th one as threshold. Figure 4 visualizes the concept. Depending on the number of pixels K that we consider, we select misclassified pixels or pixels where we predict the correct label with a small probability. We minimize the loss using ADAM [reference].
----------------------

overfitting
0.0034840694
0.04313625767827034
We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne. In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation. The former method randomly translates an image and its annotations. In order to keep consistent image dimensions, we have to pad the translated images and annotations. To this end, we use reflection padding on the image and constant padding with void labels on the annotations. Our second method of data augmentation is gamma augmentation. We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities. This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively). The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation. Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server. We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images. We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels. Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design. However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.
----------------------

correct sidewalk boundary
0.003470515
0.0023512907791882753

In [39]:
simp_ans_finder = ScoredAnswerFinder()


question_with_answers3 = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        scored_chunks = scored_3
        )


print("\n---\n---> Founded answers:")
for ans in question_with_answers3.answers:
    print(ans.text)
    print(ans.chunk.score)
    print(ans.confidence)
    print(ans.chunk.chunk.text)
    print("----------------------\n")

Device set to use cuda:1

---
---> Founded answers:
Semantic image segmentation
2.164155
3.913524415111169e-05
Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.
----------------------

semantic segmentation
0.9139763
0.0005423750844784081
1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.
----------------------

segmentation
0.62831026
8.26989344204776e-06
Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams.
----------------------

assigning a set of predefined class labels to image pixels
0.60533124
0.00040491766412742436
Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.
----------------------

computes a function F
0.44838274
4.02617733925581e-05
Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference].
----------------------

By using the two processing streams together
0.33191854
5.52726341993548e-05
Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.
----------------------

stereo or optical flow
0.1669983
0.010819800023455173
We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .
----------------------

state - of - the - art results even without pre - training
0.14718136
0.0004327117057982832
Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores. To the best of our knowledge, we are the first to show that it is possible to obtain state - of - the - art results even without pre - training. This gives credibility to our claim that network architectures can have a crucial effect on a system 's overall performance. Subsampling Factor. An interesting observation that we made on the Cityscapes test set is a correlation between the subsampling factor and the test performance. This correlation can be seen in Figure 5 where we show the scores of several approaches currently listed on the leader board against their respective subsampling factors. Unsurprisingly, most of the best performers operate on the fullresolution input images. Throughout our experiments, we consistently outperformed other approaches who trained on Mean IoU Score (%) section: Subsampling factor Published Unpublished LRR [reference] Adelaide [reference] Dilation [reference] ENet [reference] SegNet [reference] DeepLab [reference] FRRN A / B Figure 5. Comparison of the mean IoU scores of all approaches on the leader board of the Cityscapes segmentation benchmark based on the subsampling factor of the images that they were trained on. Dilation [reference] LRR [reference] FRRN B Figure 6. The trimap evaluation on the validation set. The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions.
----------------------

smoothing the network predictions
0.1458764
0.0007261462160386145
To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
----------------------

bootstrapped cross - entropy loss
0.13715829
0.0026516092475503683

In [40]:
simp_ans_finder = ScoredAnswerFinder()


question_with_answers4 = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        scored_chunks = scored_4
        )


print("\n---\n---> Founded answers:")
for ans in question_with_answers4.answers:
    print(ans.text)
    print(ans.chunk.score)
    print(ans.confidence)
    print(ans.chunk.chunk.text)
    print("----------------------\n")

Device set to use cuda:1

---
---> Founded answers:
Semantic image segmentation
1.3244383
3.913524415111169e-05
Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.
----------------------

semantic segmentation
0.55991125
0.0005423750844784081
1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.
----------------------

segmentation
0.38259667
8.26989344204776e-06
Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams.
----------------------

assigning a set of predefined class labels to image pixels
0.37164772
0.00040491766412742436
Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.
----------------------

computes a function F
0.2750291
4.02617733925581e-05
Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference].
----------------------

By using the two processing streams together
0.20169193
5.52726341993548e-05
Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.
----------------------

stereo or optical flow
0.10136973
0.010819800023455173
We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .
----------------------

state - of - the - art results even without pre - training
0.08931773
0.0004327117057982832
Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores. To the best of our knowledge, we are the first to show that it is possible to obtain state - of - the - art results even without pre - training. This gives credibility to our claim that network architectures can have a crucial effect on a system 's overall performance. Subsampling Factor. An interesting observation that we made on the Cityscapes test set is a correlation between the subsampling factor and the test performance. This correlation can be seen in Figure 5 where we show the scores of several approaches currently listed on the leader board against their respective subsampling factors. Unsurprisingly, most of the best performers operate on the fullresolution input images. Throughout our experiments, we consistently outperformed other approaches who trained on Mean IoU Score (%) section: Subsampling factor Published Unpublished LRR [reference] Adelaide [reference] Dilation [reference] ENet [reference] SegNet [reference] DeepLab [reference] FRRN A / B Figure 5. Comparison of the mean IoU scores of all approaches on the leader board of the Cityscapes segmentation benchmark based on the subsampling factor of the images that they were trained on. Dilation [reference] LRR [reference] FRRN B Figure 6. The trimap evaluation on the validation set. The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions.
----------------------

smoothing the network predictions
0.0885258
0.0007261462160386145
To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
----------------------

bootstrapped cross - entropy loss
0.0842959
0.0026516092475503683

In [41]:
import numpy as np
from typing import List, Tuple, Dict
from sklearn.metrics.pairwise import cosine_similarity
from sentence_transformers import SentenceTransformer

class AnswerConsensusFinder:
    """
    Класс для нахождения консенсусного ответа на основе оценок фрагментов и сходства между ответами.
    """
    
    def __init__(self):
        """
        Инициализация модели для вычисления эмбеддингов.
        """
        self.model = SentenceTokenizerSingleton()
    
    def find_consensus_answer(self, 
                            answers: List[Answer],
                            chunk_weight: float = 0.6,
                            similarity_weight: float = 0.4,
                            min_similarity_threshold: float = 0.7,
                            top_k_candidates: int = 5) -> Answer:
        """
        Находит консенсусный ответ на основе комбинации оценки фрагмента и сходства с другими ответами.
        
        Args:
            answers: Список объектов Answer
            chunk_weight: Вес оценки фрагмента в финальной оценке (0-1)
            similarity_weight: Вес сходства с другими ответами (0-1)
            min_similarity_threshold: Минимальный порог сходства для учета
            top_k_candidates: Количество топ-кандидатов для анализа
            
        Returns:
            Answer: Наиболее вероятный правильный ответ
        """
        if not answers:
            return None
        
        if len(answers) == 1:
            return answers[0]
        
        # Нормализуем веса
        total_weight = chunk_weight + similarity_weight
        chunk_weight /= total_weight
        similarity_weight /= total_weight
        
        # Шаг 1: Получаем эмбеддинги для всех ответов
        answer_texts = [answer.text for answer in answers]
        embeddings = self.model.tokenizer.encode(answer_texts)
        
        # Шаг 2: Вычисляем матрицу попарных сходств
        similarity_matrix = cosine_similarity(embeddings)
        
        # Шаг 3: Вычисляем оценку консенсуса для каждого ответа
        consensus_scores = []
        
        for i, answer in enumerate(answers):
            # Базовая оценка из фрагмента (нормализованная)
            chunk_score = getattr(answer, 'chunk_score', 0.0)
            confidence_score = getattr(answer, 'confidence', 0.0)
            
            # Комбинированная оценка фрагмента
            base_score = (chunk_score + confidence_score) / 2
            
            # Оценка сходства с другими ответами
            similarity_scores = []
            for j, other_answer in enumerate(answers):
                if i != j:
                    similarity = similarity_matrix[i][j]
                    if similarity >= min_similarity_threshold:
                        # Взвешиваем сходство с важностью другого ответа
                        other_chunk_score = getattr(other_answer, 'chunk_score', 0.0)
                        other_confidence = getattr(other_answer, 'confidence', 0.0)
                        other_importance = (other_chunk_score + other_confidence) / 2
                        
                        weighted_similarity = similarity * other_importance
                        similarity_scores.append(weighted_similarity)
            
            # Средняя оценка сходства (0 если нет похожих ответов)
            avg_similarity = np.mean(similarity_scores) if similarity_scores else 0.0
            
            # Финальная оценка консенсуса
            consensus_score = (base_score * chunk_weight) + (avg_similarity * similarity_weight)
            
            consensus_scores.append(consensus_score)
        
        # Шаг 4: Выбираем ответ с максимальной оценкой консенсуса
        best_index = np.argmax(consensus_scores)
        best_answer = answers[best_index]
        
        # Добавляем информацию о консенсусе
        best_answer.consensus_score = consensus_scores[best_index]
        best_answer.similar_answers_count = sum(1 for i, score in enumerate(consensus_scores) 
                                              if i != best_index and similarity_matrix[best_index][i] >= min_similarity_threshold)
        
        return best_answer

    def find_consensus_with_clustering(self,
                                     answers: List[Answer],
                                     similarity_threshold: float = 0.75) -> Answer:
        """
        Альтернативная стратегия: кластеризация ответов и выбор из наибольшего кластера.
        """
        print(f"=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===")
        print(f"Количество ответов для анализа: {len(answers)}")
        print(f"Порог сходства для кластеризации: {similarity_threshold}")
        
        if not answers:
            print("❌ Пустой список ответов")
            return None
            
        if len(answers) == 1:
            print("✅ Только один ответ - возвращаем его")
            return answers[0]
        
        # Получаем эмбеддинги
        answer_texts = [answer.text for answer in answers]
        print(f"\n📊 Тексты ответов для анализа:")
        for i, text in enumerate(answer_texts):
            chunk_score = getattr(answers[i], 'chunk_score', 0.0)
            confidence = getattr(answers[i], 'confidence', 0.0)
            print(f"  {i+1}. '{text[:50]}{'...' if len(text) > 50 else ''}' "
                  f"(chunk_score: {chunk_score:.3f}, confidence: {confidence:.3f})")
        
        embeddings = self.model.tokenizer.encode(answer_texts)
        print(f"✅ Получены эмбеддинги размерности: {embeddings.shape}")
        
        # Простая кластеризация по сходству (возвращает индексы кластеров)
        cluster_indices = self._cluster_answers(embeddings, similarity_threshold)
        
        print(f"\n🔍 Результаты кластеризации:")
        print(f"Образовано кластеров: {len(cluster_indices)}")
        
        # Преобразуем индексы в кластеры объектов Answer
        clusters = []
        for cluster_idx, indices in enumerate(cluster_indices):
            cluster = [answers[i] for i in indices]
            clusters.append(cluster)
            print(f"Кластер {cluster_idx+1}: {len(indices)} ответов (индексы: {indices})")
            
            # Выводим содержимое кластера
            for i, answer_idx in enumerate(indices):
                answer = answers[answer_idx]
                chunk_score = getattr(answer, 'chunk_score', 0.0)
                confidence = getattr(answer, 'confidence', 0.0)
                print(f"    {i+1}. '{answer.text[:60]}{'...' if len(answer.text) > 60 else ''}' "
                      f"(score: {chunk_score:.3f}, conf: {confidence:.3f})")
        
        # Находим самый большой кластер
        if not clusters:
            print("\n⚠️ Кластеры не образовались - возвращаем ответ с наивысшей оценкой")
            best_answer = max(answers, key=lambda x: getattr(x, 'chunk_score', 0.0))
            chunk_score = getattr(best_answer, 'chunk_score', 0.0)
            print(f"✅ Выбран ответ: '{best_answer.text}' (chunk_score: {chunk_score:.3f})")
            return best_answer
        
        largest_cluster = max(clusters, key=len)
        largest_cluster_size = len(largest_cluster)
        
        print(f"\n📈 Самый большой кластер: {largest_cluster_size} ответов")
        
        if not largest_cluster:
            print("⚠️ Самый большой кластер пуст - возвращаем ответ с наивысшей оценкой")
            best_answer = max(answers, key=lambda x: getattr(x, 'chunk_score', 0.0))
            chunk_score = getattr(best_answer, 'chunk_score', 0.0)
            print(f"✅ Выбран ответ: '{best_answer.text}' (chunk_score: {chunk_score:.3f})")
            return best_answer
        
        # В самом большом кластере выбираем ответ с наивысшей оценкой фрагмента
        print(f"\n🎯 Выбор лучшего ответа в самом большом кластере:")
        best_answer_in_cluster = max(largest_cluster, 
                                   key=lambda x: getattr(x, 'chunk_score', 0.0))
        
        chunk_score = getattr(best_answer_in_cluster, 'chunk_score', 0.0)
        confidence = getattr(best_answer_in_cluster, 'confidence', 0.0)
        
        print(f"✅ Лучший ответ в кластере: '{best_answer_in_cluster.text}'")
        print(f"   - Оценка фрагмента: {chunk_score:.3f}")
        print(f"   - Уверенность модели: {confidence:.3f}")
        print(f"   - Размер кластера: {largest_cluster_size}")
        print(f"   - Всего кластеров: {len(clusters)}")
        
        # Добавляем информацию о кластере
        best_answer_in_cluster.cluster_size = len(largest_cluster)
        best_answer_in_cluster.total_clusters = len(clusters)
        
        print(f"\n✅ ФИНАЛЬНЫЙ ВЫБОР: '{best_answer_in_cluster.text[:80]}{'...' if len(best_answer_in_cluster.text) > 80 else ''}'")
        print("=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===")
        
        return best_answer_in_cluster
    
    def _cluster_answers(self, embeddings: np.ndarray, threshold: float) -> List[List[int]]:
        """
        Простая кластеризация ответов на основе косинусного сходства.
        Возвращает список кластеров, где каждый кластер - список индексов ответов.
        """
        n = len(embeddings)
        clusters = []
        visited = set()
        
        similarity_matrix = cosine_similarity(embeddings)
        
        for i in range(n):
            if i in visited:
                continue
                
            cluster = [i]
            visited.add(i)
            
            # Находим все похожие ответы
            for j in range(i + 1, n):
                if j not in visited and similarity_matrix[i][j] >= threshold:
                    cluster.append(j)
                    visited.add(j)
            
            clusters.append(cluster)
        
        return clusters

    # Альтернативная упрощенная версия без кластеризации
    def find_consensus_simple(self, answers: List[Answer]) -> Answer:
        """
        Упрощенная версия: выбирает ответ с наибольшей поддержкой от других похожих ответов.
        """
        if not answers:
            return None
            
        if len(answers) == 1:
            return answers[0]
        
        # Получаем эмбеддинги
        answer_texts = [answer.text for answer in answers]
        embeddings = self.model.tokenizer.encode(answer_texts)
        similarity_matrix = cosine_similarity(embeddings)
        
        # Для каждого ответа вычисляем сумму сходств с другими ответами, взвешенную по их оценкам
        support_scores = []
        
        for i, answer in enumerate(answers):
            chunk_score = getattr(answer, 'chunk_score', 0.0)
            confidence = getattr(answer, 'confidence', 0.0)
            base_score = (chunk_score + confidence) / 2
            
            # Вычисляем поддержку от других ответов
            support = 0.0
            for j, other_answer in enumerate(answers):
                if i != j:
                    other_chunk_score = getattr(other_answer, 'chunk_score', 0.0)
                    other_confidence = getattr(other_answer, 'confidence', 0.0)
                    other_score = (other_chunk_score + other_confidence) / 2
                    
                    support += similarity_matrix[i][j] * other_score
            
            # Комбинированная оценка
            combined_score = 0.7 * base_score + 0.3 * (support / (len(answers) - 1))
            support_scores.append(combined_score)
        
        # Выбираем ответ с максимальной комбинированной оценкой
        best_index = np.argmax(support_scores)
        best_answer = answers[best_index]
        best_answer.consensus_score = support_scores[best_index]
        
        return best_answer

    def extra_find_consensus_with_clustering(self,
                                     answers: List[Answer],
                                     similarity_threshold: float = 0.75,
                                     cluster_selection_strategy: str = "weighted_score",
                                     answer_selection_strategy: str = "highest_chunk_score") -> Answer:
        """
        Альтернативная стратегия: кластеризация ответов и выбор из наилучшего кластера.
        
        Args:
            cluster_selection_strategy: Стратегия выбора кластера:
                - "largest": Самый большой кластер (оригинальная стратегия)
                - "highest_avg_score": Кластер с наивысшим средним chunk_score
                - "weighted_score": Кластер с наивысшим взвешенным score (учитывает размер и качество)
                - "best_single": Кластер, содержащий ответ с наивысшим chunk_score
            answer_selection_strategy: Стратегия выбора ответа внутри кластера:
                - "highest_chunk_score": Ответ с наивысшим chunk_score (по умолчанию)
                - "highest_similarity": Ответ с наивысшим средним сходством с другими ответами в кластере
                - "combined_score": Комбинация chunk_score и сходства
        """
        print(f"=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===")
        print(f"Количество ответов для анализа: {len(answers)}")
        print(f"Порог сходства для кластеризации: {similarity_threshold}")
        print(f"Стратегия выбора кластера: {cluster_selection_strategy}")
        print(f"Стратегия выбора ответа: {answer_selection_strategy}")
        
        if not answers:
            print("❌ Пустой список ответов")
            return None
            
        if len(answers) == 1:
            print("✅ Только один ответ - возвращаем его")
            return answers[0]
        
        # Получаем эмбеддинги
        answer_texts = [answer.text for answer in answers]
        print(f"\n📊 Тексты ответов для анализа:")
        for i, text in enumerate(answer_texts):
            chunk_score = getattr(answers[i], 'chunk_score', 0.0)
            confidence = getattr(answers[i], 'confidence', 0.0)
            print(f"  {i+1}. '{text[:50]}{'...' if len(text) > 50 else ''}' "
                  f"(chunk_score: {chunk_score:.3f}, confidence: {confidence:.3f})")
        
        embeddings = self.model.tokenizer.encode(answer_texts)
        print(f"✅ Получены эмбеддинги размерности: {embeddings.shape}")
        
        # Вычисляем матрицу сходств для всех ответов
        similarity_matrix = cosine_similarity(embeddings)
        print(f"\n🔬 Матрица сходств (первые 5x5):")
        for i in range(min(5, len(answers))):
            row = [f"{similarity_matrix[i][j]:.2f}" for j in range(min(5, len(answers)))]
            print(f"  {i}: {row}")
        
        # Простая кластеризация по сходству (возвращает индексы кластеров)
        cluster_indices = self._cluster_answers(embeddings, similarity_threshold)
        
        print(f"\n🔍 Результаты кластеризации:")
        print(f"Образовано кластеров: {len(cluster_indices)}")
        
        # Преобразуем индексы в кластеры объектов Answer
        clusters = []
        cluster_metrics = []
        
        for cluster_idx, indices in enumerate(cluster_indices):
            cluster = [answers[i] for i in indices]
            clusters.append(cluster)
            
            # Вычисляем метрики для кластера
            chunk_scores = [getattr(answer, 'chunk_score', 0.0) for answer in cluster]
            confidences = [getattr(answer, 'confidence', 0.0) for answer in cluster]
            
            avg_chunk_score = np.mean(chunk_scores) if chunk_scores else 0.0
            avg_confidence = np.mean(confidences) if confidences else 0.0
            max_chunk_score = max(chunk_scores) if chunk_scores else 0.0
            cluster_size = len(cluster)
            
            # Вычисляем среднее сходство внутри кластера
            intra_cluster_similarities = []
            for i, idx_i in enumerate(indices):
                for j, idx_j in enumerate(indices):
                    if i < j:  # Избегаем дублирования и диагонали
                        intra_cluster_similarities.append(similarity_matrix[idx_i][idx_j])
            
            avg_intra_similarity = np.mean(intra_cluster_similarities) if intra_cluster_similarities else 0.0
            
            # Взвешенная оценка кластера (размер * среднее качество)
            weighted_score = cluster_size * avg_chunk_score
            
            cluster_metrics.append({
                'cluster': cluster,
                'size': cluster_size,
                'avg_chunk_score': avg_chunk_score,
                'avg_confidence': avg_confidence,
                'max_chunk_score': max_chunk_score,
                'weighted_score': weighted_score,
                'avg_intra_similarity': avg_intra_similarity,
                'indices': indices,
                'similarity_matrix': similarity_matrix
            })
            
            print(f"\nКластер {cluster_idx+1}:")
            print(f"  Размер: {cluster_size} ответов")
            print(f"  Средний chunk_score: {avg_chunk_score:.3f}")
            print(f"  Средняя уверенность: {avg_confidence:.3f}")
            print(f"  Максимальный chunk_score: {max_chunk_score:.3f}")
            print(f"  Среднее сходство внутри кластера: {avg_intra_similarity:.3f}")
            print(f"  Взвешенная оценка: {weighted_score:.3f}")
            print(f"  Индексы: {indices}")
            
            # Выводим содержимое кластера
            for i, answer in enumerate(cluster):
                chunk_score = getattr(answer, 'chunk_score', 0.0)
                confidence = getattr(answer, 'confidence', 0.0)
                print(f"    {i+1}. '{answer.text[:60]}{'...' if len(answer.text) > 60 else ''}' "
                      f"(score: {chunk_score:.3f}, conf: {confidence:.3f})")
        
        # Находим наилучший кластер по выбранной стратегии
        if not clusters:
            print("\n⚠️ Кластеры не образовались - возвращаем ответ с наивысшей оценкой")
            best_answer = max(answers, key=lambda x: getattr(x, 'chunk_score', 0.0))
            chunk_score = getattr(best_answer, 'chunk_score', 0.0)
            print(f"✅ Выбран ответ: '{best_answer.text}' (chunk_score: {chunk_score:.3f})")
            return best_answer
        
        selected_cluster_metrics = None
        
        if cluster_selection_strategy == "largest":
            selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['size'])
            print(f"\n📈 Стратегия 'largest': выбран самый большой кластер (размер: {selected_cluster_metrics['size']})")
            
        elif cluster_selection_strategy == "highest_avg_score":
            selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['avg_chunk_score'])
            print(f"\n📈 Стратегия 'highest_avg_score': выбран кластер с наивысшим средним score ({selected_cluster_metrics['avg_chunk_score']:.3f})")
            
        elif cluster_selection_strategy == "weighted_score":
            selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['weighted_score'])
            print(f"\n📈 Стратегия 'weighted_score': выбран кластер с наивысшей взвешенной оценкой ({selected_cluster_metrics['weighted_score']:.3f})")
            
        elif cluster_selection_strategy == "best_single":
            global_best_score = max(getattr(answer, 'chunk_score', 0.0) for answer in answers)
            for metrics in cluster_metrics:
                if metrics['max_chunk_score'] == global_best_score:
                    selected_cluster_metrics = metrics
                    break
            if selected_cluster_metrics is None:
                selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['max_chunk_score'])
            print(f"\n📈 Стратегия 'best_single': выбран кластер с наивысшим отдельным ответом (score: {selected_cluster_metrics['max_chunk_score']:.3f})")
        
        elif cluster_selection_strategy == "highest_cohesion":
            # Новая стратегия: кластер с наивысшим внутренним сходством
            selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['avg_intra_similarity'])
            print(f"\n📈 Стратегия 'highest_cohesion': выбран наиболее сплоченный кластер (сходство: {selected_cluster_metrics['avg_intra_similarity']:.3f})")
        
        else:
            selected_cluster_metrics = max(cluster_metrics, key=lambda x: x['weighted_score'])
            print(f"\n📈 Стратегия по умолчанию 'weighted_score': выбран кластер с наивысшей взвешенной оценкой ({selected_cluster_metrics['weighted_score']:.3f})")
        
        selected_cluster = selected_cluster_metrics['cluster']
        cluster_indices_list = selected_cluster_metrics['indices']
        cluster_similarity_matrix = selected_cluster_metrics['similarity_matrix']
        
        # Выбор лучшего ответа в кластере по выбранной стратегии
        print(f"\n🎯 Выбор лучшего ответа в выбранном кластере (стратегия: {answer_selection_strategy}):")
        
        if answer_selection_strategy == "highest_chunk_score":
            # Оригинальная стратегия: наивысший chunk_score
            best_answer_in_cluster = max(selected_cluster, 
                                       key=lambda x: getattr(x, 'chunk_score', 0.0))
            print(f"  Использована стратегия 'highest_chunk_score'")
            
        elif answer_selection_strategy == "highest_similarity":
            # Новая стратегия: ответ с наивысшим средним сходством с другими ответами в кластере
            best_answer_in_cluster = self._select_answer_by_similarity(
                selected_cluster, cluster_indices_list, cluster_similarity_matrix)
            print(f"  Использована стратегия 'highest_similarity'")
            
        elif answer_selection_strategy == "combined_score":
            # Комбинированная стратегия: chunk_score и сходство
            best_answer_in_cluster = self._select_answer_by_combined_score(
                selected_cluster, cluster_indices_list, cluster_similarity_matrix)
            print(f"  Использована стратегия 'combined_score'")
            
        else:
            best_answer_in_cluster = max(selected_cluster, 
                                       key=lambda x: getattr(x, 'chunk_score', 0.0))
            print(f"  Использована стратегия по умолчанию 'highest_chunk_score'")
        
        chunk_score = getattr(best_answer_in_cluster, 'chunk_score', 0.0)
        confidence = getattr(best_answer_in_cluster, 'confidence', 0.0)
        
        print(f"✅ Лучший ответ в кластере: '{best_answer_in_cluster.text}'")
        print(f"   - Оценка фрагмента: {chunk_score:.3f}")
        print(f"   - Уверенность модели: {confidence:.3f}")
        print(f"   - Размер кластера: {selected_cluster_metrics['size']}")
        print(f"   - Средний chunk_score кластера: {selected_cluster_metrics['avg_chunk_score']:.3f}")
        print(f"   - Среднее сходство в кластере: {selected_cluster_metrics['avg_intra_similarity']:.3f}")
        print(f"   - Всего кластеров: {len(clusters)}")
        print(f"   - Стратегия выбора кластера: {cluster_selection_strategy}")
        print(f"   - Стратегия выбора ответа: {answer_selection_strategy}")
        
        # Добавляем информацию о кластере
        best_answer_in_cluster.cluster_size = selected_cluster_metrics['size']
        best_answer_in_cluster.total_clusters = len(clusters)
        best_answer_in_cluster.cluster_avg_score = selected_cluster_metrics['avg_chunk_score']
        best_answer_in_cluster.cluster_avg_similarity = selected_cluster_metrics['avg_intra_similarity']
        best_answer_in_cluster.selection_strategy = f"{cluster_selection_strategy}+{answer_selection_strategy}"
        
        print(f"\n✅ ФИНАЛЬНЫЙ ВЫБОР: '{best_answer_in_cluster.text[:80]}{'...' if len(best_answer_in_cluster.text) > 80 else ''}'")
        print("=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===")
        
        return best_answer_in_cluster

    def _select_answer_by_similarity(self, cluster: List[Answer], indices: List[int], 
                                   similarity_matrix: np.ndarray) -> Answer:
        """
        Выбирает ответ с наивысшим средним сходством с другими ответами в кластере.
        """
        print(f"  Поиск ответа с максимальным средним сходством в кластере:")
        
        best_answer = None
        best_avg_similarity = -1
        
        for i, answer in enumerate(cluster):
            original_index = indices[i]
            similarities = []
            
            for j, other_answer in enumerate(cluster):
                if i != j:
                    other_original_index = indices[j]
                    similarity = similarity_matrix[original_index][other_original_index]
                    similarities.append(similarity)
            
            avg_similarity = np.mean(similarities) if similarities else 0.0
            chunk_score = getattr(answer, 'chunk_score', 0.0)
            
            print(f"    Ответ {i+1}: '{answer.text[:40]}...' - среднее сходство: {avg_similarity:.3f}, chunk_score: {chunk_score:.3f}")
            
            if avg_similarity > best_avg_similarity:
                best_avg_similarity = avg_similarity
                best_answer = answer
        
        print(f"  🎯 Выбран ответ со средним сходством: {best_avg_similarity:.3f}")
        return best_answer

    def _select_answer_by_combined_score(self, cluster: List[Answer], indices: List[int],
                                       similarity_matrix: np.ndarray) -> Answer:
        """
        Выбирает ответ на основе комбинации chunk_score и сходства.
        """
        print(f"  Поиск ответа по комбинированной оценке:")
        
        best_answer = None
        best_combined_score = -1
        
        for i, answer in enumerate(cluster):
            original_index = indices[i]
            
            # Вычисляем среднее сходство
            similarities = []
            for j, other_answer in enumerate(cluster):
                if i != j:
                    other_original_index = indices[j]
                    similarity = similarity_matrix[original_index][other_original_index]
                    similarities.append(similarity)
            
            avg_similarity = np.mean(similarities) if similarities else 0.0
            chunk_score = getattr(answer, 'chunk_score', 0.0)
            
            # Комбинированная оценка (50% chunk_score + 50% сходство)
            combined_score = 0.5 * chunk_score + 0.5 * avg_similarity
            
            print(f"    Ответ {i+1}: '{answer.text[:40]}...' - combined: {combined_score:.3f} "
                  f"(chunk: {chunk_score:.3f}, similarity: {avg_similarity:.3f})")
            
            if combined_score > best_combined_score:
                best_combined_score = combined_score
                best_answer = answer
        
        print(f"  🎯 Выбран ответ с комбинированной оценкой: {best_combined_score:.3f}")
        return best_answer

In [42]:
ans_con_finder = AnswerConsensusFinder()

In [43]:
con_ans1 = ans_con_finder.find_consensus_answer( 
                            answers = question_with_answers1.answers)

con_ans1

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [44]:
con_ans2 = ans_con_finder.find_consensus_with_clustering( 
                            answers = question_with_answers1.answers)

con_ans2

=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===
Количество ответов для анализа: 16
Порог сходства для кластеризации: 0.75

📊 Тексты ответов для анализа:
  1. 'Semantic image segmentation' (chunk_score: 4.263, confidence: 0.000)
  2. 'semantic segmentation' (chunk_score: 1.799, confidence: 0.001)
  3. 'segmentation' (chunk_score: 1.243, confidence: 0.000)
  4. 'assigning a set of predefined class labels to imag...' (chunk_score: 1.190, confidence: 0.000)
  5. 'computes a function F' (chunk_score: 0.882, confidence: 0.000)
  6. 'By using the two processing streams together' (chunk_score: 0.657, confidence: 0.000)
  7. 'stereo or optical flow' (chunk_score: 0.331, confidence: 0.011)
  8. 'state - of - the - art results even without pre - ...' (chunk_score: 0.292, confidence: 0.000)
  9. 'smoothing the network predictions' (chunk_score: 0.289, confidence: 0.001)
  10. 'bootstrapped cross - entropy loss' (chunk_score: 0.269, confidence: 0.003)
  11. 'FRRN B' (chunk_score: 0.223, confidence: 0.000)
  12. 'precise semantic segmentation' (chunk_score: 0.186, confidence: 0.001)
  13. 'computing the output x n directly' (chunk_score: 0.145, confidence: 0.000)
  14. 'Training FRRN B' (chunk_score: 0.086, confidence: 0.001)
  15. 'overfitting' (chunk_score: 0.053, confidence: 0.043)
  16. 'correct sidewalk boundary' (chunk_score: 0.053, confidence: 0.002)
✅ Получены эмбеддинги размерности: (16, 1024)

🔍 Результаты кластеризации:
Образовано кластеров: 15
Кластер 1: 2 ответов (индексы: [0, 1])
    1. 'Semantic image segmentation' (score: 4.263, conf: 0.000)
    2. 'semantic segmentation' (score: 1.799, conf: 0.001)
Кластер 2: 1 ответов (индексы: [2])
    1. 'segmentation' (score: 1.243, conf: 0.000)
Кластер 3: 1 ответов (индексы: [3])
    1. 'assigning a set of predefined class labels to image pixels' (score: 1.190, conf: 0.000)
Кластер 4: 1 ответов (индексы: [4])
    1. 'computes a function F' (score: 0.882, conf: 0.000)
Кластер 5: 1 ответов (индексы: [5])
    1. 'By using the two processing streams together' (score: 0.657, conf: 0.000)
Кластер 6: 1 ответов (индексы: [6])
    1. 'stereo or optical flow' (score: 0.331, conf: 0.011)
Кластер 7: 1 ответов (индексы: [7])
    1. 'state - of - the - art results even without pre - training' (score: 0.292, conf: 0.000)
Кластер 8: 1 ответов (индексы: [8])
    1. 'smoothing the network predictions' (score: 0.289, conf: 0.001)
Кластер 9: 1 ответов (индексы: [9])
    1. 'bootstrapped cross - entropy loss' (score: 0.269, conf: 0.003)
Кластер 10: 1 ответов (индексы: [10])
    1. 'FRRN B' (score: 0.223, conf: 0.000)
Кластер 11: 1 ответов (индексы: [11])
    1. 'precise semantic segmentation' (score: 0.186, conf: 0.001)
Кластер 12: 1 ответов (индексы: [12])
    1. 'computing the output x n directly' (score: 0.145, conf: 0.000)
Кластер 13: 1 ответов (индексы: [13])
    1. 'Training FRRN B' (score: 0.086, conf: 0.001)
Кластер 14: 1 ответов (индексы: [14])
    1. 'overfitting' (score: 0.053, conf: 0.043)
Кластер 15: 1 ответов (индексы: [15])
    1. 'correct sidewalk boundary' (score: 0.053, conf: 0.002)

📈 Самый большой кластер: 2 ответов

🎯 Выбор лучшего ответа в самом большом кластере:
✅ Лучший ответ в кластере: 'Semantic image segmentation'
   - Оценка фрагмента: 4.263
   - Уверенность модели: 0.000
   - Размер кластера: 2
   - Всего кластеров: 15

✅ ФИНАЛЬНЫЙ ВЫБОР: 'Semantic image segmentation'
=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [45]:
con_ans3 = ans_con_finder.find_consensus_simple( 
                            answers = question_with_answers1.answers)

con_ans3

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [46]:
# Сбалансированный подход (рекомендуется)
con_ans4 = ans_con_finder.extra_find_consensus_with_clustering(
    answers=question_with_answers1.answers,
    similarity_threshold=0.7,
    cluster_selection_strategy="weighted_score"
)
con_ans4

=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===
Количество ответов для анализа: 16
Порог сходства для кластеризации: 0.7
Стратегия выбора кластера: weighted_score
Стратегия выбора ответа: highest_chunk_score

📊 Тексты ответов для анализа:
  1. 'Semantic image segmentation' (chunk_score: 4.263, confidence: 0.000)
  2. 'semantic segmentation' (chunk_score: 1.799, confidence: 0.001)
  3. 'segmentation' (chunk_score: 1.243, confidence: 0.000)
  4. 'assigning a set of predefined class labels to imag...' (chunk_score: 1.190, confidence: 0.000)
  5. 'computes a function F' (chunk_score: 0.882, confidence: 0.000)
  6. 'By using the two processing streams together' (chunk_score: 0.657, confidence: 0.000)
  7. 'stereo or optical flow' (chunk_score: 0.331, confidence: 0.011)
  8. 'state - of - the - art results even without pre - ...' (chunk_score: 0.292, confidence: 0.000)
  9. 'smoothing the network predictions' (chunk_score: 0.289, confidence: 0.001)
  10. 'bootstrapped cross - entropy loss' (chunk_score: 0.269, confidence: 0.003)
  11. 'FRRN B' (chunk_score: 0.223, confidence: 0.000)
  12. 'precise semantic segmentation' (chunk_score: 0.186, confidence: 0.001)
  13. 'computing the output x n directly' (chunk_score: 0.145, confidence: 0.000)
  14. 'Training FRRN B' (chunk_score: 0.086, confidence: 0.001)
  15. 'overfitting' (chunk_score: 0.053, confidence: 0.043)
  16. 'correct sidewalk boundary' (chunk_score: 0.053, confidence: 0.002)
✅ Получены эмбеддинги размерности: (16, 1024)

🔬 Матрица сходств (первые 5x5):
  0: ['1.00', '0.93', '0.72', '0.71', '0.50']
  1: ['0.93', '1.00', '0.84', '0.58', '0.52']
  2: ['0.72', '0.84', '1.00', '0.44', '0.52']
  3: ['0.71', '0.58', '0.44', '1.00', '0.47']
  4: ['0.50', '0.52', '0.52', '0.47', '1.00']

🔍 Результаты кластеризации:
Образовано кластеров: 11

Кластер 1:
  Размер: 5 ответов
  Средний chunk_score: 1.736
  Средняя уверенность: 0.000
  Максимальный chunk_score: 4.263
  Среднее сходство внутри кластера: 0.700
  Взвешенная оценка: 8.681
  Индексы: [0, 1, 2, 3, 11]
    1. 'Semantic image segmentation' (score: 4.263, conf: 0.000)
    2. 'semantic segmentation' (score: 1.799, conf: 0.001)
    3. 'segmentation' (score: 1.243, conf: 0.000)
    4. 'assigning a set of predefined class labels to image pixels' (score: 1.190, conf: 0.000)
    5. 'precise semantic segmentation' (score: 0.186, conf: 0.001)

Кластер 2:
  Размер: 1 ответов
  Средний chunk_score: 0.882
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.882
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.882
  Индексы: [4]
    1. 'computes a function F' (score: 0.882, conf: 0.000)

Кластер 3:
  Размер: 1 ответов
  Средний chunk_score: 0.657
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.657
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.657
  Индексы: [5]
    1. 'By using the two processing streams together' (score: 0.657, conf: 0.000)

Кластер 4:
  Размер: 1 ответов
  Средний chunk_score: 0.331
  Средняя уверенность: 0.011
  Максимальный chunk_score: 0.331
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.331
  Индексы: [6]
    1. 'stereo or optical flow' (score: 0.331, conf: 0.011)

Кластер 5:
  Размер: 1 ответов
  Средний chunk_score: 0.292
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.292
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.292
  Индексы: [7]
    1. 'state - of - the - art results even without pre - training' (score: 0.292, conf: 0.000)

Кластер 6:
  Размер: 1 ответов
  Средний chunk_score: 0.289
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.289
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.289
  Индексы: [8]
    1. 'smoothing the network predictions' (score: 0.289, conf: 0.001)

Кластер 7:
  Размер: 1 ответов
  Средний chunk_score: 0.269
  Средняя уверенность: 0.003
  Максимальный chunk_score: 0.269
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.269
  Индексы: [9]
    1. 'bootstrapped cross - entropy loss' (score: 0.269, conf: 0.003)

Кластер 8:
  Размер: 2 ответов
  Средний chunk_score: 0.154
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.223
  Среднее сходство внутри кластера: 0.726
  Взвешенная оценка: 0.308
  Индексы: [10, 13]
    1. 'FRRN B' (score: 0.223, conf: 0.000)
    2. 'Training FRRN B' (score: 0.086, conf: 0.001)

Кластер 9:
  Размер: 1 ответов
  Средний chunk_score: 0.145
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.145
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.145
  Индексы: [12]
    1. 'computing the output x n directly' (score: 0.145, conf: 0.000)

Кластер 10:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.043
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [14]
    1. 'overfitting' (score: 0.053, conf: 0.043)

Кластер 11:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.002
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [15]
    1. 'correct sidewalk boundary' (score: 0.053, conf: 0.002)

📈 Стратегия 'weighted_score': выбран кластер с наивысшей взвешенной оценкой (8.681)

🎯 Выбор лучшего ответа в выбранном кластере (стратегия: highest_chunk_score):
  Использована стратегия 'highest_chunk_score'
✅ Лучший ответ в кластере: 'Semantic image segmentation'
   - Оценка фрагмента: 4.263
   - Уверенность модели: 0.000
   - Размер кластера: 5
   - Средний chunk_score кластера: 1.736
   - Среднее сходство в кластере: 0.700
   - Всего кластеров: 11
   - Стратегия выбора кластера: weighted_score
   - Стратегия выбора ответа: highest_chunk_score

✅ ФИНАЛЬНЫЙ ВЫБОР: 'Semantic image segmentation'
=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [47]:
# Акцент на качество
con_ans5 = ans_con_finder.extra_find_consensus_with_clustering(
    answers=question_with_answers1.answers,
    cluster_selection_strategy="highest_avg_score"
)
con_ans5

=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===
Количество ответов для анализа: 16
Порог сходства для кластеризации: 0.75
Стратегия выбора кластера: highest_avg_score
Стратегия выбора ответа: highest_chunk_score

📊 Тексты ответов для анализа:
  1. 'Semantic image segmentation' (chunk_score: 4.263, confidence: 0.000)
  2. 'semantic segmentation' (chunk_score: 1.799, confidence: 0.001)
  3. 'segmentation' (chunk_score: 1.243, confidence: 0.000)
  4. 'assigning a set of predefined class labels to imag...' (chunk_score: 1.190, confidence: 0.000)
  5. 'computes a function F' (chunk_score: 0.882, confidence: 0.000)
  6. 'By using the two processing streams together' (chunk_score: 0.657, confidence: 0.000)
  7. 'stereo or optical flow' (chunk_score: 0.331, confidence: 0.011)
  8. 'state - of - the - art results even without pre - ...' (chunk_score: 0.292, confidence: 0.000)
  9. 'smoothing the network predictions' (chunk_score: 0.289, confidence: 0.001)
  10. 'bootstrapped cross - entropy loss' (chunk_score: 0.269, confidence: 0.003)
  11. 'FRRN B' (chunk_score: 0.223, confidence: 0.000)
  12. 'precise semantic segmentation' (chunk_score: 0.186, confidence: 0.001)
  13. 'computing the output x n directly' (chunk_score: 0.145, confidence: 0.000)
  14. 'Training FRRN B' (chunk_score: 0.086, confidence: 0.001)
  15. 'overfitting' (chunk_score: 0.053, confidence: 0.043)
  16. 'correct sidewalk boundary' (chunk_score: 0.053, confidence: 0.002)
✅ Получены эмбеддинги размерности: (16, 1024)

🔬 Матрица сходств (первые 5x5):
  0: ['1.00', '0.93', '0.72', '0.71', '0.50']
  1: ['0.93', '1.00', '0.84', '0.58', '0.52']
  2: ['0.72', '0.84', '1.00', '0.44', '0.52']
  3: ['0.71', '0.58', '0.44', '1.00', '0.47']
  4: ['0.50', '0.52', '0.52', '0.47', '1.00']

🔍 Результаты кластеризации:
Образовано кластеров: 15

Кластер 1:
  Размер: 2 ответов
  Средний chunk_score: 3.031
  Средняя уверенность: 0.000
  Максимальный chunk_score: 4.263
  Среднее сходство внутри кластера: 0.927
  Взвешенная оценка: 6.063
  Индексы: [0, 1]
    1. 'Semantic image segmentation' (score: 4.263, conf: 0.000)
    2. 'semantic segmentation' (score: 1.799, conf: 0.001)

Кластер 2:
  Размер: 1 ответов
  Средний chunk_score: 1.243
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.243
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.243
  Индексы: [2]
    1. 'segmentation' (score: 1.243, conf: 0.000)

Кластер 3:
  Размер: 1 ответов
  Средний chunk_score: 1.190
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.190
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.190
  Индексы: [3]
    1. 'assigning a set of predefined class labels to image pixels' (score: 1.190, conf: 0.000)

Кластер 4:
  Размер: 1 ответов
  Средний chunk_score: 0.882
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.882
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.882
  Индексы: [4]
    1. 'computes a function F' (score: 0.882, conf: 0.000)

Кластер 5:
  Размер: 1 ответов
  Средний chunk_score: 0.657
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.657
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.657
  Индексы: [5]
    1. 'By using the two processing streams together' (score: 0.657, conf: 0.000)

Кластер 6:
  Размер: 1 ответов
  Средний chunk_score: 0.331
  Средняя уверенность: 0.011
  Максимальный chunk_score: 0.331
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.331
  Индексы: [6]
    1. 'stereo or optical flow' (score: 0.331, conf: 0.011)

Кластер 7:
  Размер: 1 ответов
  Средний chunk_score: 0.292
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.292
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.292
  Индексы: [7]
    1. 'state - of - the - art results even without pre - training' (score: 0.292, conf: 0.000)

Кластер 8:
  Размер: 1 ответов
  Средний chunk_score: 0.289
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.289
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.289
  Индексы: [8]
    1. 'smoothing the network predictions' (score: 0.289, conf: 0.001)

Кластер 9:
  Размер: 1 ответов
  Средний chunk_score: 0.269
  Средняя уверенность: 0.003
  Максимальный chunk_score: 0.269
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.269
  Индексы: [9]
    1. 'bootstrapped cross - entropy loss' (score: 0.269, conf: 0.003)

Кластер 10:
  Размер: 1 ответов
  Средний chunk_score: 0.223
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.223
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.223
  Индексы: [10]
    1. 'FRRN B' (score: 0.223, conf: 0.000)

Кластер 11:
  Размер: 1 ответов
  Средний chunk_score: 0.186
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.186
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.186
  Индексы: [11]
    1. 'precise semantic segmentation' (score: 0.186, conf: 0.001)

Кластер 12:
  Размер: 1 ответов
  Средний chunk_score: 0.145
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.145
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.145
  Индексы: [12]
    1. 'computing the output x n directly' (score: 0.145, conf: 0.000)

Кластер 13:
  Размер: 1 ответов
  Средний chunk_score: 0.086
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.086
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.086
  Индексы: [13]
    1. 'Training FRRN B' (score: 0.086, conf: 0.001)

Кластер 14:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.043
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [14]
    1. 'overfitting' (score: 0.053, conf: 0.043)

Кластер 15:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.002
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [15]
    1. 'correct sidewalk boundary' (score: 0.053, conf: 0.002)

📈 Стратегия 'highest_avg_score': выбран кластер с наивысшим средним score (3.031)

🎯 Выбор лучшего ответа в выбранном кластере (стратегия: highest_chunk_score):
  Использована стратегия 'highest_chunk_score'
✅ Лучший ответ в кластере: 'Semantic image segmentation'
   - Оценка фрагмента: 4.263
   - Уверенность модели: 0.000
   - Размер кластера: 2
   - Средний chunk_score кластера: 3.031
   - Среднее сходство в кластере: 0.927
   - Всего кластеров: 15
   - Стратегия выбора кластера: highest_avg_score
   - Стратегия выбора ответа: highest_chunk_score

✅ ФИНАЛЬНЫЙ ВЫБОР: 'Semantic image segmentation'
=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [48]:
# Ответ, который наиболее репрезентативен для кластера
con_ans6 = ans_con_finder.extra_find_consensus_with_clustering(
    answers=question_with_answers1.answers,
    cluster_selection_strategy="weighted_score",
    answer_selection_strategy="highest_similarity"
)
con_ans6

=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===
Количество ответов для анализа: 16
Порог сходства для кластеризации: 0.75
Стратегия выбора кластера: weighted_score
Стратегия выбора ответа: highest_similarity

📊 Тексты ответов для анализа:
  1. 'Semantic image segmentation' (chunk_score: 4.263, confidence: 0.000)
  2. 'semantic segmentation' (chunk_score: 1.799, confidence: 0.001)
  3. 'segmentation' (chunk_score: 1.243, confidence: 0.000)
  4. 'assigning a set of predefined class labels to imag...' (chunk_score: 1.190, confidence: 0.000)
  5. 'computes a function F' (chunk_score: 0.882, confidence: 0.000)
  6. 'By using the two processing streams together' (chunk_score: 0.657, confidence: 0.000)
  7. 'stereo or optical flow' (chunk_score: 0.331, confidence: 0.011)
  8. 'state - of - the - art results even without pre - ...' (chunk_score: 0.292, confidence: 0.000)
  9. 'smoothing the network predictions' (chunk_score: 0.289, confidence: 0.001)
  10. 'bootstrapped cross - entropy loss' (chunk_score: 0.269, confidence: 0.003)
  11. 'FRRN B' (chunk_score: 0.223, confidence: 0.000)
  12. 'precise semantic segmentation' (chunk_score: 0.186, confidence: 0.001)
  13. 'computing the output x n directly' (chunk_score: 0.145, confidence: 0.000)
  14. 'Training FRRN B' (chunk_score: 0.086, confidence: 0.001)
  15. 'overfitting' (chunk_score: 0.053, confidence: 0.043)
  16. 'correct sidewalk boundary' (chunk_score: 0.053, confidence: 0.002)
✅ Получены эмбеддинги размерности: (16, 1024)

🔬 Матрица сходств (первые 5x5):
  0: ['1.00', '0.93', '0.72', '0.71', '0.50']
  1: ['0.93', '1.00', '0.84', '0.58', '0.52']
  2: ['0.72', '0.84', '1.00', '0.44', '0.52']
  3: ['0.71', '0.58', '0.44', '1.00', '0.47']
  4: ['0.50', '0.52', '0.52', '0.47', '1.00']

🔍 Результаты кластеризации:
Образовано кластеров: 15

Кластер 1:
  Размер: 2 ответов
  Средний chunk_score: 3.031
  Средняя уверенность: 0.000
  Максимальный chunk_score: 4.263
  Среднее сходство внутри кластера: 0.927
  Взвешенная оценка: 6.063
  Индексы: [0, 1]
    1. 'Semantic image segmentation' (score: 4.263, conf: 0.000)
    2. 'semantic segmentation' (score: 1.799, conf: 0.001)

Кластер 2:
  Размер: 1 ответов
  Средний chunk_score: 1.243
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.243
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.243
  Индексы: [2]
    1. 'segmentation' (score: 1.243, conf: 0.000)

Кластер 3:
  Размер: 1 ответов
  Средний chunk_score: 1.190
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.190
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.190
  Индексы: [3]
    1. 'assigning a set of predefined class labels to image pixels' (score: 1.190, conf: 0.000)

Кластер 4:
  Размер: 1 ответов
  Средний chunk_score: 0.882
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.882
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.882
  Индексы: [4]
    1. 'computes a function F' (score: 0.882, conf: 0.000)

Кластер 5:
  Размер: 1 ответов
  Средний chunk_score: 0.657
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.657
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.657
  Индексы: [5]
    1. 'By using the two processing streams together' (score: 0.657, conf: 0.000)

Кластер 6:
  Размер: 1 ответов
  Средний chunk_score: 0.331
  Средняя уверенность: 0.011
  Максимальный chunk_score: 0.331
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.331
  Индексы: [6]
    1. 'stereo or optical flow' (score: 0.331, conf: 0.011)

Кластер 7:
  Размер: 1 ответов
  Средний chunk_score: 0.292
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.292
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.292
  Индексы: [7]
    1. 'state - of - the - art results even without pre - training' (score: 0.292, conf: 0.000)

Кластер 8:
  Размер: 1 ответов
  Средний chunk_score: 0.289
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.289
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.289
  Индексы: [8]
    1. 'smoothing the network predictions' (score: 0.289, conf: 0.001)

Кластер 9:
  Размер: 1 ответов
  Средний chunk_score: 0.269
  Средняя уверенность: 0.003
  Максимальный chunk_score: 0.269
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.269
  Индексы: [9]
    1. 'bootstrapped cross - entropy loss' (score: 0.269, conf: 0.003)

Кластер 10:
  Размер: 1 ответов
  Средний chunk_score: 0.223
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.223
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.223
  Индексы: [10]
    1. 'FRRN B' (score: 0.223, conf: 0.000)

Кластер 11:
  Размер: 1 ответов
  Средний chunk_score: 0.186
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.186
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.186
  Индексы: [11]
    1. 'precise semantic segmentation' (score: 0.186, conf: 0.001)

Кластер 12:
  Размер: 1 ответов
  Средний chunk_score: 0.145
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.145
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.145
  Индексы: [12]
    1. 'computing the output x n directly' (score: 0.145, conf: 0.000)

Кластер 13:
  Размер: 1 ответов
  Средний chunk_score: 0.086
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.086
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.086
  Индексы: [13]
    1. 'Training FRRN B' (score: 0.086, conf: 0.001)

Кластер 14:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.043
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [14]
    1. 'overfitting' (score: 0.053, conf: 0.043)

Кластер 15:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.002
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [15]
    1. 'correct sidewalk boundary' (score: 0.053, conf: 0.002)

📈 Стратегия 'weighted_score': выбран кластер с наивысшей взвешенной оценкой (6.063)

🎯 Выбор лучшего ответа в выбранном кластере (стратегия: highest_similarity):
  Поиск ответа с максимальным средним сходством в кластере:
    Ответ 1: 'Semantic image segmentation...' - среднее сходство: 0.927, chunk_score: 4.263
    Ответ 2: 'semantic segmentation...' - среднее сходство: 0.927, chunk_score: 1.799
  🎯 Выбран ответ со средним сходством: 0.927
  Использована стратегия 'highest_similarity'
✅ Лучший ответ в кластере: 'Semantic image segmentation'
   - Оценка фрагмента: 4.263
   - Уверенность модели: 0.000
   - Размер кластера: 2
   - Средний chunk_score кластера: 3.031
   - Среднее сходство в кластере: 0.927
   - Всего кластеров: 15
   - Стратегия выбора кластера: weighted_score
   - Стратегия выбора ответа: highest_similarity

✅ ФИНАЛЬНЫЙ ВЫБОР: 'Semantic image segmentation'
=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)

In [49]:
# Сбалансированный подход
con_ans7 = ans_con_finder.extra_find_consensus_with_clustering(
    answers=question_with_answers1.answers,
    cluster_selection_strategy="highest_cohesion",
    answer_selection_strategy="combined_score"
)
con_ans7

=== НАЧАЛО КЛАСТЕРИЗАЦИИ ОТВЕТОВ ===
Количество ответов для анализа: 16
Порог сходства для кластеризации: 0.75
Стратегия выбора кластера: highest_cohesion
Стратегия выбора ответа: combined_score

📊 Тексты ответов для анализа:
  1. 'Semantic image segmentation' (chunk_score: 4.263, confidence: 0.000)
  2. 'semantic segmentation' (chunk_score: 1.799, confidence: 0.001)
  3. 'segmentation' (chunk_score: 1.243, confidence: 0.000)
  4. 'assigning a set of predefined class labels to imag...' (chunk_score: 1.190, confidence: 0.000)
  5. 'computes a function F' (chunk_score: 0.882, confidence: 0.000)
  6. 'By using the two processing streams together' (chunk_score: 0.657, confidence: 0.000)
  7. 'stereo or optical flow' (chunk_score: 0.331, confidence: 0.011)
  8. 'state - of - the - art results even without pre - ...' (chunk_score: 0.292, confidence: 0.000)
  9. 'smoothing the network predictions' (chunk_score: 0.289, confidence: 0.001)
  10. 'bootstrapped cross - entropy loss' (chunk_score: 0.269, confidence: 0.003)
  11. 'FRRN B' (chunk_score: 0.223, confidence: 0.000)
  12. 'precise semantic segmentation' (chunk_score: 0.186, confidence: 0.001)
  13. 'computing the output x n directly' (chunk_score: 0.145, confidence: 0.000)
  14. 'Training FRRN B' (chunk_score: 0.086, confidence: 0.001)
  15. 'overfitting' (chunk_score: 0.053, confidence: 0.043)
  16. 'correct sidewalk boundary' (chunk_score: 0.053, confidence: 0.002)
✅ Получены эмбеддинги размерности: (16, 1024)

🔬 Матрица сходств (первые 5x5):
  0: ['1.00', '0.93', '0.72', '0.71', '0.50']
  1: ['0.93', '1.00', '0.84', '0.58', '0.52']
  2: ['0.72', '0.84', '1.00', '0.44', '0.52']
  3: ['0.71', '0.58', '0.44', '1.00', '0.47']
  4: ['0.50', '0.52', '0.52', '0.47', '1.00']

🔍 Результаты кластеризации:
Образовано кластеров: 15

Кластер 1:
  Размер: 2 ответов
  Средний chunk_score: 3.031
  Средняя уверенность: 0.000
  Максимальный chunk_score: 4.263
  Среднее сходство внутри кластера: 0.927
  Взвешенная оценка: 6.063
  Индексы: [0, 1]
    1. 'Semantic image segmentation' (score: 4.263, conf: 0.000)
    2. 'semantic segmentation' (score: 1.799, conf: 0.001)

Кластер 2:
  Размер: 1 ответов
  Средний chunk_score: 1.243
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.243
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.243
  Индексы: [2]
    1. 'segmentation' (score: 1.243, conf: 0.000)

Кластер 3:
  Размер: 1 ответов
  Средний chunk_score: 1.190
  Средняя уверенность: 0.000
  Максимальный chunk_score: 1.190
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 1.190
  Индексы: [3]
    1. 'assigning a set of predefined class labels to image pixels' (score: 1.190, conf: 0.000)

Кластер 4:
  Размер: 1 ответов
  Средний chunk_score: 0.882
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.882
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.882
  Индексы: [4]
    1. 'computes a function F' (score: 0.882, conf: 0.000)

Кластер 5:
  Размер: 1 ответов
  Средний chunk_score: 0.657
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.657
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.657
  Индексы: [5]
    1. 'By using the two processing streams together' (score: 0.657, conf: 0.000)

Кластер 6:
  Размер: 1 ответов
  Средний chunk_score: 0.331
  Средняя уверенность: 0.011
  Максимальный chunk_score: 0.331
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.331
  Индексы: [6]
    1. 'stereo or optical flow' (score: 0.331, conf: 0.011)

Кластер 7:
  Размер: 1 ответов
  Средний chunk_score: 0.292
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.292
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.292
  Индексы: [7]
    1. 'state - of - the - art results even without pre - training' (score: 0.292, conf: 0.000)

Кластер 8:
  Размер: 1 ответов
  Средний chunk_score: 0.289
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.289
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.289
  Индексы: [8]
    1. 'smoothing the network predictions' (score: 0.289, conf: 0.001)

Кластер 9:
  Размер: 1 ответов
  Средний chunk_score: 0.269
  Средняя уверенность: 0.003
  Максимальный chunk_score: 0.269
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.269
  Индексы: [9]
    1. 'bootstrapped cross - entropy loss' (score: 0.269, conf: 0.003)

Кластер 10:
  Размер: 1 ответов
  Средний chunk_score: 0.223
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.223
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.223
  Индексы: [10]
    1. 'FRRN B' (score: 0.223, conf: 0.000)

Кластер 11:
  Размер: 1 ответов
  Средний chunk_score: 0.186
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.186
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.186
  Индексы: [11]
    1. 'precise semantic segmentation' (score: 0.186, conf: 0.001)

Кластер 12:
  Размер: 1 ответов
  Средний chunk_score: 0.145
  Средняя уверенность: 0.000
  Максимальный chunk_score: 0.145
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.145
  Индексы: [12]
    1. 'computing the output x n directly' (score: 0.145, conf: 0.000)

Кластер 13:
  Размер: 1 ответов
  Средний chunk_score: 0.086
  Средняя уверенность: 0.001
  Максимальный chunk_score: 0.086
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.086
  Индексы: [13]
    1. 'Training FRRN B' (score: 0.086, conf: 0.001)

Кластер 14:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.043
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [14]
    1. 'overfitting' (score: 0.053, conf: 0.043)

Кластер 15:
  Размер: 1 ответов
  Средний chunk_score: 0.053
  Средняя уверенность: 0.002
  Максимальный chunk_score: 0.053
  Среднее сходство внутри кластера: 0.000
  Взвешенная оценка: 0.053
  Индексы: [15]
    1. 'correct sidewalk boundary' (score: 0.053, conf: 0.002)

📈 Стратегия 'highest_cohesion': выбран наиболее сплоченный кластер (сходство: 0.927)

🎯 Выбор лучшего ответа в выбранном кластере (стратегия: combined_score):
  Поиск ответа по комбинированной оценке:
    Ответ 1: 'Semantic image segmentation...' - combined: 2.595 (chunk: 4.263, similarity: 0.927)
    Ответ 2: 'semantic segmentation...' - combined: 1.363 (chunk: 1.799, similarity: 0.927)
  🎯 Выбран ответ с комбинированной оценкой: 2.595
  Использована стратегия 'combined_score'
✅ Лучший ответ в кластере: 'Semantic image segmentation'
   - Оценка фрагмента: 4.263
   - Уверенность модели: 0.000
   - Размер кластера: 2
   - Средний chunk_score кластера: 3.031
   - Среднее сходство в кластере: 0.927
   - Всего кластеров: 15
   - Стратегия выбора кластера: highest_cohesion
   - Стратегия выбора ответа: combined_score

✅ ФИНАЛЬНЫЙ ВЫБОР: 'Semantic image segmentation'
=== ЗАВЕРШЕНИЕ КЛАСТЕРИЗАЦИИ ===

Answer(text='Semantic image segmentation', chunk=ScoredChunk(chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), score=np.float32(4.2634473), matched_keywords=['auxiliary', 'application', 'employ', 'current', 'target', 'example', 'detection', 'task', 'pursue', 'require', 'class'], keyword_scores={'auxiliary': np.float32(0.16079235), 'application': np.float32(0.17649734), 'employ': np.float32(0.2867719), 'current': np.float32(0.04848516), 'target': np.float32(0.15338182), 'example': np.float32(0.041388273), 'detection': np.float32(0.123521805), 'task': np.float32(0.40358943), 'pursue': np.float32(0.1143105), 'require': np.float32(0.30358487), 'class': np.float32(0.07146126)}, original_weights={'auxiliary': {'weight': 0.0023717775475233793, 'score_diff': np.float32(0.16079235)}, 'application': {'weight': 0.0020525797735899687, 'score_diff': np.float32(0.17649734)}, 'employ': {'weight': 0.0030397071968764067, 'score_diff': np.float32(0.2867719)}, 'current': {'weight': 0.003179467748850584, 'score_diff': np.float32(0.04848516)}, 'target': {'weight': 0.0020016799680888653, 'score_diff': np.float32(0.15338182)}, 'example': {'weight': 0.0028540880884975195, 'score_diff': np.float32(0.041388273)}, 'detection': {'weight': 0.0024286305997520685, 'score_diff': np.float32(0.123521805)}, 'task': {'weight': 0.0036683217622339725, 'score_diff': np.float32(0.40358943)}, 'pursue': {'weight': 0.0022047029342502356, 'score_diff': np.float32(0.1143105)}, 'require': {'weight': 0.002683906350284815, 'score_diff': np.float32(0.30358487)}, 'class': {'weight': 0.0021746018901467323, 'score_diff': np.float32(0.07146126)}}), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)