In [1]:
from system_check import *
CUDA_state_print()

CUDA доступна: True
Количество GPU: 4

GPU #0:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #1:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #2:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

GPU #3:
Название: Tesla V100-SXM3-32GB
Вычислительная способность (CUDA Capability): (7, 0)
Объем памяти: 31.73 GB

In [2]:
import sys
sys.path.append("/global_functions")
from global_functions.global_functions import *

------------------------------------
---> Choosing resource
---> Result of torch.cuda.is_available():
True
---> Final resource
-----> CUDA: 1
-----> device: cuda:1
------------------------------------

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/config.json
Model config BertConfig {
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30522
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model/model.safetensors
All model checkpoint weights were used when initializing BertModel.

All the weights of BertModel were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/eng_sentence_transformer_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
loading file vocab.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/config.json
Model config RobertaConfig {
  "architectures": [
    "RobertaForQuestionAnswering"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "language": "english",
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "name": "Roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_attentions": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/model.safetensors
All model checkpoint weights were used when initializing RobertaForQuestionAnswering.

All the weights of RobertaForQuestionAnswering were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use RobertaForQuestionAnswering for predictions without further training.

In [3]:
name = "scirex_structured.json"
datasets_path = "../datasets"

df_loaded = load_dataframe_from_json(f"{datasets_path}/{name}")
df_loaded

,doc_id,methods,tasks,metrics,materials,score,original_text
0,000f90380d768a85e2316225854fc377c079b5c4,[FRRN],"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Frame__fps_, Mean_IoU, mIoU, Time__ms_]",[Cityscapes],"[2.1, 71.8%, 469]",Full - Resolution Residual Networks for Semant...
1,0012de6bec1f25599e4f02517637e531a71909b9,[V-Net___Dice-based_loss],[Volumetric_Medical_Image_Segmentation],[Dice_Score],[PROMISE_2012],[0.869],document: V - Net: Fully Convolutional Neural ...
2,007ab5528b3bd310a80d553cccad4b78dc496b02,"[BiDAF__single_model_, BiDAF, BiDAF__ensemble_...","[Question_Answering, Open-Domain_Question_Answ...","[METEOR, EM__Quasar-T_, F1__Quasar-T_, F1, EM,...","[NarrativeQA, MS_MARCO, SQuAD1_1, CNN___Daily_...","[33.45, 23.96, 15.69, 25.9, 79.6, 36.74, 76.9,...",document: Bi - Directional Attention Flow for ...
3,0095c269e7d0c990249312687fc43521019809c4,[50D_stacked_TC-LSTMs],[Natural_Language_Inference],"[Parameters, __Train_Accuracy, __Test_Accuracy]",[SNLI],"[190k, 86.7, 85.1]",document: Modelling Interaction of Sentence Pa...
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,"[AlphaZero, AlphaGo_Zero]","[Game_of_Go, Game_of_Shogi]",[ELO_Rating],[ELO_Ratings],"[4650, 5185]",document: Mastering Chess and Shogi by Self - ...
...,...,...,...,...,...,...,...
301,45b559e6271570598602fcf9777ed6f2f2d133e6,[Deep_CNN__10_conv__4_FC_layers___multi-scale_...,[Speech_Recognition],[Percentage_error],[Switchboard___Hub500],[],document: Very Deep Multilingual Convolutional...
302,45e8ef229fae18b0a2ab328037d8e520866c3c81,[Pyramid_Residual_Modules__PRMs_],[Pose_Estimation],"[PCKh-0_5, PCK]","[Leeds_Sports_Poses, MPII_Human_Pose]","[93.9%, 92.0%]",document: Learning Feature Pyramids for Human ...
303,45fdc73a239e9c6ea65e98c96f6a2d6dc35d6f72,[QCNN-10L-256FM],[Speech_Recognition],[Percentage_error],[TIMIT],[19.64],document: Quaternion Convolutional Neural Netw...
304,46018a894d533813d67322827ca51f78aed6d59e,[InputCascadeCNN],[Brain_Tumor_Segmentation],[Dice_Score],[BRATS-2013],[0.88],document: Brain Tumor Segmentation with Deep N...
305,462d4e265c9cbe9ad5feeb9a7736184a90b36fed,"[CRF___AutoEncoder, Neural-CRF_AE]",[Named_Entity_Recognition__NER_],[F1],[CoNLL_2003__English_],"[92.29, 91.87]",document: Evaluating the Utility of Hand - cra...

In [4]:
df_loaded = replace_underscores_in_array_column(df=df_loaded,
                                        column_name="tasks")
df_loaded.head()

,doc_id,methods,tasks,metrics,materials,score,original_text,tasks_cleaned
0,000f90380d768a85e2316225854fc377c079b5c4,[FRRN],"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Frame__fps_, Mean_IoU, mIoU, Time__ms_]",[Cityscapes],"[2.1, 71.8%, 469]",Full - Resolution Residual Networks for Semant...,"[Semantic Segmentation, Real-Time Semantic Seg..."
1,0012de6bec1f25599e4f02517637e531a71909b9,[V-Net___Dice-based_loss],[Volumetric_Medical_Image_Segmentation],[Dice_Score],[PROMISE_2012],[0.869],document: V - Net: Fully Convolutional Neural ...,[Volumetric Medical Image Segmentation]
2,007ab5528b3bd310a80d553cccad4b78dc496b02,"[BiDAF__single_model_, BiDAF, BiDAF__ensemble_...","[Question_Answering, Open-Domain_Question_Answ...","[METEOR, EM__Quasar-T_, F1__Quasar-T_, F1, EM,...","[NarrativeQA, MS_MARCO, SQuAD1_1, CNN___Daily_...","[33.45, 23.96, 15.69, 25.9, 79.6, 36.74, 76.9,...",document: Bi - Directional Attention Flow for ...,"[Question Answering, Open-Domain Question Answ..."
3,0095c269e7d0c990249312687fc43521019809c4,[50D_stacked_TC-LSTMs],[Natural_Language_Inference],"[Parameters, __Train_Accuracy, __Test_Accuracy]",[SNLI],"[190k, 86.7, 85.1]",document: Modelling Interaction of Sentence Pa...,[Natural Language Inference]
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,"[AlphaZero, AlphaGo_Zero]","[Game_of_Go, Game_of_Shogi]",[ELO_Rating],[ELO_Ratings],"[4650, 5185]",document: Mastering Chess and Shogi by Self - ...,"[Game of Go, Game of Shogi]"

In [5]:
model_name = "scart_init_model.json"
model_params_path = "../model_params"

df_model_params = pd.read_json(f"{model_params_path}/{model_name}")

df_model_params

,model_name,description,fields
0,ScArt Model,Модель для обработки научных статей на английс...,"{'field_id': 1, 'field_name': 'task', 'field_t..."

In [6]:
field_name = df_model_params["fields"][0]["field_name"]
questions = df_model_params["fields"][0]["questions"]
keywords = df_model_params["fields"][0]["keywords"]
text = df_model_params["fields"][0]["text"]

In [7]:
them_aspect = ThematicAspect(field_name, convert_into_question_class(questions))

In [8]:
num_of_sample = 0

In [9]:
text_of_doc = df_loaded["original_text"][num_of_sample]
text_of_doc

"Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible?), they lack localization accuracy (i.e., where precisely is something located?). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71.8% on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams. One stream undergoes a sequence of pooling operations and is responsible for understanding large - scale relationships of image elements; the other stream carries feature maps at the full image resolution, resulting in precise boundary adherence. This idea is visualized in Figure 1, where the two processing streams are shown in blue and red. The blue residual lane reflects the high - resolution stream. It can be combined with classical residual units (left and right), as well as with our new full - resolution residual units (FRRU). The FRRUs from the red pooling lane act as residual units for the blue stream, but also undergo pooling operations and carry high - level information through the network. This results in a network that successively combines and computes features at two resolutions. This paper makes the following contributions: (i) We propose a novel network architecture geared towards precise semantic segmentation in street scenes which is not limited to pre - trained architectures and achieves state - ofthe - art results. (ii) We propose to use two processing streams to realize strong recognition and strong localization performance: One stream undergoes a sequence of pooling operations while the other stream stays at the full image resolution. (iii) In order to foster further research in this area, we publish our code and the trained models in Theano / Lasagne [reference ][ reference] 1. 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures. Since the success of the AlexNet architecture [reference] in the ImageNet Large - Scale Visual Classification Challenge (ILSVRC) [reference], the vision community has seen several milestones with respect to CNN architectures. The network depth has been constantly increased, first with the popular VGG net [reference], then by using batch normalization with GoogleNet [reference]. Lately, many computer vision applications have adopted the ResNet architecture [reference], which often leads to signification performance boosts compared to earlier network architectures. All of these developments show how important a proper architecture is. However, so far most of these networks have been specifically tailored towards the task of classification, in many cases including a pre - training step on ILSVRC. As a result, some of their design choices may contribute to a suboptimal performance when performing pixel - to - pixel tasks such as semantic segmentation. In contrast, our proposed architecture has been specifically designed for segmentation tasks and reaches competitive performance on the Cityscapes dataset without requiring ILSVRC pre - training. section: Network Architectures for Segmentation Feed - Forward Networks. Until recently, the majority of feedforward networks, such as the VGG - variants [reference], were composed of a linear sequence of layers. Each layer in such a network computes a function F and the output x n of the n - th layer is computed as where W n are the parameters of the layer (see 2a). We refer to this class of network architectures as traditional feedforward networks. Residual Networks (ResNets). He et al. observed that deepening traditional feedforward networks often results in an increased training loss [reference]. In theory, however, the training loss of a shallow network should be an upper bound on the training loss of a corresponding deep network. This is due to the fact that increasing the depth by adding layers strictly increases the expressive power of the model. A deep network can express all functions that the original shallow network can express by using identity mappings for the added layers. Hence a deep network should perform at least as well as the shallower model on the training data. The violation of this principle implied that current training algorithms have difficulties optimizing very deep traditional feedforward networks. He et al. proposed residual networks (ResNets) that exhibit significantly improved training characteristics, allowing network depths that were previously unattainable. A ResNet is composed of a sequence of residual units (RUs). As depicted in Figure 2b, the output x n of the n - th RU in a ResNet is computed as where F (x n−1; W n) is the residual, which is parametrized by W n. Thus, instead of computing the output x n directly, F only computes a residual that is added to the input x n−1. One commonly refers to this design as skip connection, because there is a connection from the input x n−1 to the output x n that skips the actual computation F. It has been empirically observed that ResNets have superior training properties over traditional feedforward networks. This can be explained by an improved gradient flow within the network. In oder to understand this, consider the n - th and m - th residual units in a ResNet where m > n (i.e., the m - th unit is closer to the output layer of the network). By applying the recursion (2) several times, He et al. showed in [reference] that the output of the m - th residual unit admits a representation of the form Furthermore, if l is the loss that is used to train the network, we can use the chain rule of calculus and express the derivative of the loss l with respect to the output x n of the n - th RU as Thus, we find We see that the weight updates depend on two sources of information,. While the amount of information that is contained in the latter may depend crucially on the depth n, the former allows a gradient flow that is independent of the depth. Hence, gradients can flow unhindered from the deeper unit to the shallower unit. This makes training even extremely deep ResNets possible. section: Full - Resolution Residual Networks (FRRNs). In this paper, we unify the two above - mentioned principles of network design and propose full - resolution residual networks (FRRNs) that exhibit the same superior training properties as ResNets but have two processing streams. The features on one stream, the residual stream, are computed by adding successive residuals, while the features on the other stream, the pooling stream, are the direct result of a sequence of convolution and pooling operations applied to the input. Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively. If G ≡ 0, then an FRRU corresponds to an RU since it disregards the pooling input y n, and the network effectively becomes an ordinary ResNet. On the other hand, if H ≡ 0, then the output of an FRRU only depends on its input via the function G. Hence, no residuals are computed and we obtain a traditional feedforward network. By carefully constructing G and H, we can combine the two network principles. In order to show that FRRNs have similar training characteristics as ResNets, we adapt the analysis presented in [reference] to our case. Using the same recursive argument as before, we find that for m > n, z m has the representation We can then express the derivative of the loss l with respect to the weights W n as Hence, the weight updates depend on three sources of information. Analogous to the analysis of ResNets, the two sources ∂H (yi, zi;Wi + 1) ∂zn depend crucially on the depth n, while the term ∂l ∂zm is independent of the depth. Thus, we achieve a depth - independent gradient flow for all parameters that are used by the residual function H. If we use some of these weights in order to compute the output of G, all weights of the unit benefit from the improved gradient flow. This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation perfo

In [10]:
reference_answers = df_loaded["tasks_cleaned"][num_of_sample]
reference_answers

['Semantic Segmentation', 'Real-Time Semantic Segmentation']

In [11]:
text_proc = TextProcesser()
sents = text_proc.split_into_sentences(text_of_doc)

sentences = [Sentence(sents[i], i) for i in range(len(sents))]

print("---> Number of sentences:")
print(f"--> {len(sentences)}")

chunk_builder = ChunkBuilder()
text_chunks = chunk_builder.build_chunks(sentences)

print("---\n---> Number of chunks:")
print(f"--> {len(text_chunks)}")

---> Number of sentences:
--> 276
---
---> Number of chunks:
--> 22

In [12]:
RAG_model = SentenceTokenizerSingleton()

In [13]:
RAG_model.tokenizer

SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False, 'architecture': 'BertModel'})
  (1): Pooling({'word_embedding_dimension': 1024, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False, 'pooling_mode_weightedmean_tokens': False, 'pooling_mode_lasttoken': False, 'include_prompt': True})
)

In [14]:
len(text_chunks[0].full_text_embedding)

1024

In [15]:
len(them_aspect.questions[0].text_embedding)

1024

In [16]:
question_embedding = them_aspect.questions[0].text_embedding

In [17]:
chunk_embeddings = [chunk.full_text_embedding for chunk in text_chunks]

In [18]:
chunk_embeddings = torch.from_numpy(np.array(chunk_embeddings))

In [19]:
question_embedding = torch.from_numpy(np.array([question_embedding]))

In [20]:
question_embedding.shape

torch.Size([1, 1024])

In [21]:
if question_embedding.ndim == 1:
    question_embedding = question_embedding.reshape(1, -1)

In [22]:
question_embedding.shape

torch.Size([1, 1024])

In [23]:
# Вычисляем косинусное сходство
similarities = cosine_similarity(
            question_embedding, 
            chunk_embeddings
            )

In [24]:
len(similarities)

22

In [25]:
similarities

tensor([0.3318, 0.3862, 0.3318, 0.2756, 0.2009, 0.4389, 0.1818, 0.2943, 0.4229,
        0.4221, 0.3256, 0.4066, 0.2736, 0.2120, 0.3156, 0.2353, 0.2755, 0.2988,
        0.1658, 0.2456, 0.2786, 0.1426])

In [26]:
# Сортируем фрагменты по убыванию сходства
sorted_indices = np.argsort(np.array(similarities))[::-1]

/tmp/ipykernel_3737293/1323298583.py:2: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  sorted_indices = np.argsort(np.array(similarities))[::-1]

In [27]:
sorted_indices

array([ 5,  8,  9, 11,  1,  0,  2, 10, 14, 17,  7, 20,  3, 16, 12, 19, 15,
       13,  4,  6, 18, 21])

In [28]:
for ind in sorted_indices:
    print(text_chunks[ind].text)

To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
This can be explained by an improved gradient flow within the network. In oder to understand this, consider the n - th and m - th residual units in a ResNet where m > n (i.e., the m - th unit is closer to the output layer of the network). By applying the recursion (2) several times, He et al. showed in [reference] that the output of the m - th residual unit admits a representation of the form Furthermore, if l is the loss that is used to train the network, we can use the chain rule of calculus and express the derivative of the loss l with respect to the output x n of the n - th RU as Thus, we find We see that the weight updates depend on two sources of information,. While the amount of information that is contained in the latter may depend crucially on the depth n, the former allows a gradient flow that is independent of the depth. Hence, gradients can flow unhindered from the deeper unit to the shallower unit. This makes training even extremely deep ResNets possible. section: Full - Resolution Residual Networks (FRRNs). In this paper, we unify the two above - mentioned principles of network design and propose full - resolution residual networks (FRRNs) that exhibit the same superior training properties as ResNets but have two processing streams. The features on one stream, the residual stream, are computed by adding successive residuals, while the features on the other stream, the pooling stream, are the direct result of a sequence of convolution and pooling operations applied to the input. Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations.
Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.
This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation performance. The proposed architectures are based on several principles employed by other authors. We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations.
Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.
Full - Resolution Residual Networks for Semantic Segmentation in Street Scenes section: Abstract Semantic image segmentation is an essential component of modern autonomous driving systems, as an accurate understanding of the surrounding scene is crucial to navigation and action planning. Current state - of - the - art approaches in semantic image segmentation rely on pretrained networks that were initially developed for classifying images as a whole. While these networks exhibit outstanding recognition performance (i.e., what is visible? ), they lack localization accuracy (i.e., where precisely is something located? ). Therefore, additional processing steps have to be performed in order to obtain pixel - accurate segmentation masks at the full image resolution. To alleviate this problem we propose a novel ResNet - like architecture that exhibits strong localization and recognition performance. We combine multi - scale context with pixel - level accuracy by using two processing streams within our network: One stream carries information at the full image resolution, enabling precise adherence to segment boundaries. The other stream undergoes a sequence of pooling operations to obtain robust features for recognition. The two streams are coupled at the full image resolution using residuals. Without additional processing steps and without pretraining, our approach achieves an intersection - over - union score of 71. 8 % on the Cityscapes dataset. section: Introduction Recent years have seen an increasing interest in self driving cars and in driver assistance systems. A crucial aspect of autonomous driving is to acquire a comprehensive understanding of the surroundings in which a car is moving. Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.
Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application. However, a main limitation of using such pre - trained networks is that they severely restrict the design space of novel approaches, since new network elements such as batch normalization [reference] or new activation functions often can not be added into an existing architecture. When performing semantic segmentation using FCNs, a common strategy is to successively reduce the spatial size of the feature maps using pooling operations or strided convolutions. This is done for two reasons: First, it significantly increases the size of the receptive field and second, it makes the network robust against small translations in the image. While pooling operations are highly desirable for recognizing objects in images, they significantly deteriorate localization performance of the networks when applied to semantic image segmentation. Several approaches exist to overcome this problem and obtain pixel - accurate segmentations. Noh et al. [reference] learn a mirrored VGG network as a decoder, Yu and Koltun [reference] introduce dilated convolutions to reduce the pooling factor of their pre - trained network. Ghiasi et al. [reference] use multi - scale predictions to successively improve their boundary adherence. An alternative approach used by several methods is to apply post - processing steps such as CRF - smoothing [reference]. In this paper, we propose a novel network architecture that achieves state - of - the - art segmentation performance without the need for additional post - processing steps and without the limitations imposed by pre - trained architectures. Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams.
Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively. If G ≡ 0, then an FRRU corresponds to an RU since it disregards the pooling input y n, and the network effectively becomes an ordinary ResNet. On the other hand, if H ≡ 0, then the output of an FRRU only depends on its input via the function G. Hence, no residuals are computed and we obtain a traditional feedforward network. By carefully constructing G and H, we can combine the two network principles. In order to show that FRRNs have similar training characteristics as ResNets, we adapt the analysis presented in [reference] to our case. Using the same recursive argument as before, we find that for m > n, z m has the representation We can then express the derivative of the loss l with respect to the weights W n as Hence, the weight updates depend on three sources of information. Analogous to the analysis of ResNets, the two sources ∂H (yi, zi;Wi + 1) ∂zn depend crucially on the depth n, while the term ∂l ∂zm is independent of the depth. Thus, we achieve a depth - independent gradient flow for all parameters that are used by the residual function H. If we use some of these weights in order to compute the output of G, all weights of the unit benefit from the improved gradient flow. This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design.
We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne. In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation. The former method randomly translates an image and its annotations. In order to keep consistent image dimensions, we have to pad the translated images and annotations. To this end, we use reflection padding on the image and constant padding with void labels on the annotations. Our second method of data augmentation is gamma augmentation. We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities. This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively). The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation. Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server. We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images. We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels. Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design. However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.
Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores. To the best of our knowledge, we are the first to show that it is possible to obtain state - of - the - art results even without pre - training. This gives credibility to our claim that network architectures can have a crucial effect on a system 's overall performance. Subsampling Factor. An interesting observation that we made on the Cityscapes test set is a correlation between the subsampling factor and the test performance. This correlation can be seen in Figure 5 where we show the scores of several approaches currently listed on the leader board against their respective subsampling factors. Unsurprisingly, most of the best performers operate on the fullresolution input images. Throughout our experiments, we consistently outperformed other approaches who trained on Mean IoU Score (%) section: Subsampling factor Published Unpublished LRR [reference] Adelaide [reference] Dilation [reference] ENet [reference] SegNet [reference] DeepLab [reference] FRRN A / B Figure 5. Comparison of the mean IoU scores of all approaches on the leader board of the Cityscapes segmentation benchmark based on the subsampling factor of the images that they were trained on. Dilation [reference] LRR [reference] FRRN B Figure 6. The trimap evaluation on the validation set. The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions.

In [29]:
import copy

threshold = 0.0005
top_k = 100


# Отбираем фрагменты, превышающие порог
relevant_chunks = []
for idx in sorted_indices:
    if similarities[idx] >= threshold and len(relevant_chunks) < top_k:
        # Добавляем информацию о сходстве в фрагмент
        relevant_chunks.append(copy.deepcopy(text_chunks[idx]))

In [30]:
relevant_chunks

[TextChunk(sentences=[Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58), Sentence(text='Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance.', num=59), Sentence(text='However, they have the downside that the resulting network outputs are at a lower resolution.', num=60), Sentence(text='To overcome this, various strategies have been proposed.', num=61), Sentence(text='Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference].', num=62), Sentence(text='Noh et al.', num=63), Sentence(text='propose an encoder / decoder network [reference].', num=64), Sentence(text='The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations.', num=65), Sentence(text='The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference].', num=66), Sentence(text='Similarly, Badrinarayanan et al.', num=67), Sentence(text='[reference ][ reference] use convolutions instead of deconvolutions in the decoder network.', num=68), Sentence(text='In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream.', num=69), Sentence(text='Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions.', num=70), Sentence(text='Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference].', num=71), Sentence(text='More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference].', num=72), Sentence(text='Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference].', num=73), Sentence(text='Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions.', num=74), Sentence(text='Experiments with additional CRF smoothing therefore did not result in significant performance improvements.', num=75), Sentence(text='Network architectures.', num=76)], text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.', word_token_count=382),
 TextChunk(sentences=[Sentence(text='This can be explained by an improved gradient flow within the network.', num=101), Sentence(text='In oder to understand this, consider the n - th and m - th residual units in a ResNet where m > n (i.e., the m - th unit is closer to the output layer of the network).', num=102), Sentence(text='By applying the recursion (2) several times, He et al.', num=103), Sentence(text='showed in [reference] that the output of the m - th residual unit admits a representation of the form Furthermore, if l is the loss that is used to train the network, we can use the chain rule of calculus and express the derivative of the loss l with respect to the output x n of the n - th RU as Thus, we find We see that the weight updates depend on two sources of information,.', num=104), Sentence(text='While the amount of information that is contained in the latter may depend crucially on the depth n, the former allows a gradient flow that is independent of the depth.', num=105), Sentence(text='Hence, gradients can flow unhindered from the deeper unit to the shallower unit.', num=106), Sentence(text='This makes training even extremely deep ResNets possible.', num=107), Sentence(text='section: Full - Resolution Residual Networks (FRRNs).', num=108), Sentence(text='In this paper, we unify the two above - mentioned principles of network design and propose full - resolution residual networks (FRRNs) that exhibit the same superior training properties as ResNets but have two processing streams.', num=109), Sentence(text='The features on one stream, the residual stream, are computed by adding successive residuals, while the features on the other stream, the pooling stream, are the direct result of a sequence of convolution and pooling operations applied to the input.', num=110), Sentence(text='Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization.', num=111), Sentence(text='Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations.', num=112)], text='This can be explained by an improved gradient flow within the network. In oder to understand this, consider the n - th and m - th residual units in a ResNet where m > n (i.e., the m - th unit is closer to the output layer of the network). By applying the recursion (2) several times, He et al. showed in [reference] that the output of the m - th residual unit admits a representation of the form Furthermore, if l is the loss that is used to train the network, we can use the chain rule of calculus and express the derivative of the loss l with respect to the output x n of the n - th RU as Thus, we find We see that the weight updates depend on two sources of information,. While the amount of information that is contained in the latter may depend crucially on the depth n, the former allows a gradient flow that is independent of the depth. Hence, gradients can flow unhindered from the deeper unit to the shallower unit. This makes training even extremely deep ResNets possible. section: Full - Resolution Residual Networks (FRRNs). In this paper, we unify the two above - mentioned principles of network design and propose full - resolution residual networks (FRRNs) that exhibit the same superior training properties as ResNets but have two processing streams. The features on one stream, the residual stream, are computed by adding successive residuals, while the features on the other stream, the pooling stream, are the direct result of a sequence of convolution and pooling operations applied to the input. Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations.', word_token_count=381),
 TextChunk(sentences=[Sentence(text='Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization.', num=111), Sentence(text='Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations.', num=112), Sentence(text="The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image.", num=113), Sentence(text='While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers.', num=114), Sentence(text='This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy.', num=115), Sentence(text='On the other hand, a network that does not employ any pooling operations behaves the opposite way.', num=116), Sentence(text='It is good at localizing object boundaries, but performs poorly at recognizing the actual objects.', num=117), Sentence(text='By using the two processing streams together, we are able to compute both kinds of features simultaneously.', num=118), Sentence(text='While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features.', num=119), Sentence(text='Figure 1 visualizes the concept of having two distinct processing streams.', num=120), Sentence(text='An FRRN is composed of a sequence of full - resolution residual units (FRRUs).', num=121), Sentence(text='Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams.', num=122), Sentence(text='Figure 2c shows the structure of an FRRU.', num=123), Sentence(text='Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input.', num=124), Sentence(text='Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.', num=125)], text="Our design is motivated by the need to have networks that can jointly compute good high - level features for recognition and good low - level features for localization. Regardless of the specific network design, obtaining good highlevel features requires a sequence of pooling operations. The pooling operations reduce the size of the feature maps and increase the network 's receptive field, as well as its robustness against small translations in the image. While this is crucial to obtaining robust high - level features, networks that employ a deep pooling hierarchy have difficulties tracking low - level features, such as edges and boundaries, in deeper layers. This makes them good at recognizing the elements in a scene but bad at localizing them to pixel accuracy. On the other hand, a network that does not employ any pooling operations behaves the opposite way. It is good at localizing object boundaries, but performs poorly at recognizing the actual objects. By using the two processing streams together, we are able to compute both kinds of features simultaneously. While the residual stream of an FRRN computes successive residuals at the full image resolution, allowing low level features to propagate effortlessly through the network, the pooling stream undergoes a sequence of pooling and unpooling operations resulting in good high - level features. Figure 1 visualizes the concept of having two distinct processing streams. An FRRN is composed of a sequence of full - resolution residual units (FRRUs). Each FRRU has two inputs and two outputs, because it simultaneously operates on both streams. Figure 2c shows the structure of an FRRU. Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively.", word_token_count=366),
 TextChunk(sentences=[Sentence(text='This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible.', num=133), Sentence(text='Figure 3 shows our proposed FRRU design.', num=134), Sentence(text='The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream.', num=135), Sentence(text='Then the concatenated features are fed through two convolution units.', num=136), Sentence(text='Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function.', num=137), Sentence(text='The result of the second convolution unit is used in two ways.', num=138), Sentence(text='First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual.', num=139), Sentence(text='To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer.', num=140), Sentence(text='Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation.', num=141), Sentence(text='In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box.', num=142), Sentence(text='As shown above, this design choice results in superior gradient flow properties for all weights of the unit.', num=143), Sentence(text="Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation performance.", num=144), Sentence(text='The proposed architectures are based on several principles employed by other authors.', num=145), Sentence(text='We follow Noh et al.', num=146), Sentence(text='[reference] and use an encoder / decoder formulation.', num=147), Sentence(text='In the encoder, we reduce the size of the pooling stream using max pooling operations.', num=148)], text="This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation performance. The proposed architectures are based on several principles employed by other authors. We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations.", word_token_count=377),

In [31]:
simp_ans_finder = SimpleAnswerFinder()


question_with_answers = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        chunks = relevant_chunks
        )

Device set to use cuda:1
Disabling tokenizer parallelism, we're using DataLoader multithreading already
RobertaSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

In [32]:
question_with_answers

Question(text='Which task was solved?', answers=[Answer(text='overfitting', chunk=TextChunk(sentences=[Sentence(text='We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne.', num=176), Sentence(text='In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation.', num=177), Sentence(text='The former method randomly translates an image and its annotations.', num=178), Sentence(text='In order to keep consistent image dimensions, we have to pad the translated images and annotations.', num=179), Sentence(text='To this end, we use reflection padding on the image and constant padding with void labels on the annotations.', num=180), Sentence(text='Our second method of data augmentation is gamma augmentation.', num=181), Sentence(text='We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities.', num=182), Sentence(text='This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively).', num=183), Sentence(text='The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation.', num=184), Sentence(text='Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server.', num=185), Sentence(text='We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images.', num=186), Sentence(text='We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels.', num=187), Sentence(text='Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design.', num=188), Sentence(text="However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.", num=189)], text="We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne. In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation. The former method randomly translates an image and its annotations. In order to keep consistent image dimensions, we have to pad the translated images and annotations. To this end, we use reflection padding on the image and constant padding with void labels on the annotations. Our second method of data augmentation is gamma augmentation. We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities. This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively). The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation. Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server. We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images. We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels. Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design. However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.", word_token_count=369), confidence=0.04313625767827034, start_pos=129, end_pos=140), Answer(text='stereo or optical flow', chunk=TextChunk(sentences=[Sentence(text='We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries.', num=240), Sentence(text='Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training.', num=241), Sentence(text='Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step.', num=242), Sentence(text='We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference].', num=243), Sentence(text='We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference].', num=244), Sentence(text='Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero.', num=245), Sentence(text='This indicates that the appearance kernel would only smooth labels across pixels with very similar colors.', num=246), Sentence(text='Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set.', num=247), Sentence(text='Given the high computation time we decided against any post - processing steps.', num=248), Sentence(text='section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes.', num=249), Sentence(text='Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark.', num=250), Sentence(text='We will provide code and all trained models.', num=251), Sentence(text='Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel.', num=252), Sentence(text='Our goal is to find γ such that E U [U] = 0. 5 .', num=253), Sentence(text='The key idea to solving this problem is to look at the deviation of U from 0. 5 .', num=254)], text='We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .', word_token_count=379), confidence=0.010819800023455173, start_pos=1767, end_pos=1789), Answer(text='look at the deviation of U from 0. 5 .', chunk=TextChunk(sentences=[Sentence(text='Our goal is to find γ such that E U [U] = 0. 5 .', num=253), Sentence(text='The key idea to solving this problem is to look at the deviation of U from 0. 5 .', num=254), Sentence(text='Let Z be this deviation.', num=255), Sentence(text='Then (11) is equivalent to Hence, without solving for the implicitly defined variable U explicitly, we found a transformation of a zero - mean random variable Z such that γ has the desired properties.', num=256), Sentence(text='Because Z was defined to be the offset from 0. 5  and U ∈ [0, 1], it follows Z ∈ [−0. 5 , 0. 5 ].', num=257), Sentence(text='We are free to choose any distribution such that Z has zero mean and falls into the range [−0. 5 , 0. 5 ].', num=258), Sentence(text='For simplicity reasons, we choose Z to be uniformly distributed over [−a, a] where a ∈ [0, 0. 5 ] determines the strength of the augmentation.', num=259), Sentence(text='Figure 8b illustrates the obvious bias reduction.', num=260), Sentence(text='section: B. Baseline Evaluation In Section 5. 2  of the main paper, we describe the setting of our baseline method (Residual Network Baseline) and compare it to our FRRN A network.', num=261), Sentence(text='To emphasize on a proper training procedure of both baselines, Figure 9 shows the mean IoU score on the validation set over time.', num=262), Sentence(text='We can see that our model outperforms the baseline with a significant margin and both methods are trained until convergence.', num=263), Sentence(text='Figure 10 shows and compares addtional output labelings of our method.', num=264), Sentence(text='Please also consult our labeled video sequence [reference] to gain a better sense of the quality of our method.', num=265), Sentence(text='We all know Latex is a pain.', num=266), Sentence(text='section: C. Qualitative Results section: Image Ground Truth Ours LRR [reference] Figure 10.', num=267), Sentence(text='Additional qualitative results on the Cityscapes validation set.', num=268)], text='Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 . Let Z be this deviation. Then (11) is equivalent to Hence, without solving for the implicitly defined variable U explicitly, we found a transformation of a zero - mean random variable Z such that γ has the desired properties. Because Z was defined to be the offset from 0. 5  and U ∈ [0, 1], it follows Z ∈ [−0. 5 , 0. 5 ]. We are free to choose any distribution such that Z has zero mean and falls into the range [−0. 5 , 0. 5 ]. For simplicity reasons, we choose Z to be uniformly distributed over [−a, a] where a ∈ [0, 0. 5 ] determines the strength of the augmentation. Figure 8b illustrates the obvious bias reduction. section: B. Baseline Evaluation In Section 5. 2  of the main paper, we describe the setting of our baseline method (Residual Network Baseline) and compare it to our FRRN A network. To emphasize on a proper training procedure of both baselines, Figure 9 shows the mean IoU score on the validation set over time. We can see that our model outperforms the baseline with a significant margin and both methods are trained until convergence. Figure 10 shows and compares addtional output labelings of our method. Please also consult our labeled video sequence [reference] to gain a better sense of the quality of our method. We all know Latex is a pain. section: C. Qualitative Results section: Image Ground Truth Ours LRR [reference] Figure 10. Additional qualitative results on the Cityscapes validation set.', word_token_count=368), confidence=0.010365484282374382, start_pos=92, end_pos=130), Answer(text='bootstrapped cross - entropy loss', chunk=TextChunk(sentences=[Sentence(text='We follow Noh et al.', num=146), Sentence(text='[reference] and use an encoder / decoder formulation.', num=147), Sentence(text='In the encoder, we reduce the size of the pooling stream using max pooling operations.', num=148), Sentence(text='The pooled feature maps are then successively upscaled using bilinear interpolation in the decoder.', num=149), Sentence(text='Furthermore, similar to Simonyan and Zisserman [reference], we define a number of base channels that we double after each pooling operation (up to a certain upper limit).', num=150), Sentence(text='Instead of choosing 64 base channels as in VGG net, we use 48 channels in order to have a manageable number of trainable parameters.', num=151), Sentence(text='Depending on the input image resolution, we use FRRN A or FRRN B to keep the relative size of the receptive fields consistent.', num=152), Sentence(text='section: Training Procedure Following Wu et al.', num=153), Sentence(text=', we train our network by minimizing a bootstrapped cross - entropy loss [reference].', num=154), Sentence(text='Let c be the number of classes, y 1,.', num=155), Sentence(text=', y N ∈ {1,.', num=156), Sentence(text=', c} be the target class labels for the pixels 1,.', num=157), Sentence(text=', N, and let p i, j be the posterior class + Bias Softmax probability for class j and pixel i. Then, the bootstrapped cross - entropy loss over K pixels is defined as where 1 [x] = 1 iff x is true and t k ∈ R is chosen such that |{i ∈ {1,.', num=158), Sentence(text=', N}: p i, yi < t k} | = K. The threshold parameter t k can easily be determined by sorting the predicted log probabilities and choosing the K + 1 - th one as threshold.', num=159), Sentence(text='Figure 4 visualizes the concept.', num=160), Sentence(text='Depending on the number of pixels K that we consider, we select misclassified pixels or pixels where we predict the correct label with a small probability.', num=161), Sentence(text='We minimize the loss using ADAM [reference].', num=162)], text='We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations. The pooled feature maps are then successively upscaled using bilinear interpolation in the decoder. Furthermore, similar to Simonyan and Zisserman [reference], we define a number of base channels that we double after each pooling operation (up to a certain upper limit). Instead of choosing 64 base channels as in VGG net, we use 48 channels in order to have a manageable number of trainable parameters. Depending on the input image resolution, we use FRRN A or FRRN B to keep the relative size of the receptive fields consistent. section: Training Procedure Following Wu et al. , we train our network by minimizing a bootstrapped cross - entropy loss [reference]. Let c be the number of classes, y 1,. , y N ∈ {1,. , c} be the target class labels for the pixels 1,. , N, and let p i, j be the posterior class + Bias Softmax probability for class j and pixel i. Then, the bootstrapped cross - entropy loss over K pixels is defined as where 1 [x] = 1 iff x is true and t k ∈ R is chosen such that |{i ∈ {1,. , N}: p i, yi < t k} | = K. The threshold parameter t k can easily be determined by sorting the predicted log probabilities and choosing the K + 1 - th one as threshold. Figure 4 visualizes the concept. Depending on the number of pixels K that we consider, we select misclassified pixels or pixels where we predict the correct label with a small probability. We minimize the loss using ADAM [reference].', word_token_count=374), confidence=0.0026516092475503683, start_pos=780, end_pos=813), Answer(text='correct sidewalk boundary', chunk=TextChunk(sentences=[Sentence(text='The solid lines show the mean IoU score of our approach and two top performing methods that released their code.', num=227), Sentence(text='The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods.', num=228), Sentence(text='the same image resolutions.', num=229), Sentence(text='Even though we only train on half - resolution images, Figure 5 clearly shows we can match the current published state - of - the - art (LRR [reference] Figure 7.', num=230), Sentence(text='Qualitative comparison on the Cityscapes validation set.', num=231), Sentence(text='Interesting cases are the fence in the first row, the truck in the second row, or the street light poles in the last row.', num=232), Sentence(text='An interesting failure case is shown in the third row: all methods struggle to find the correct sidewalk boundary, however our network makes a clean and reasonable prediction.', num=233), Sentence(text="section: Boundary Adherence Due to several pooling operations (and subsequent upsampling) in many of today 's FCN architectures, boundaries are often overly smooth, resulting in lost details and edge - bleeding.", num=234), Sentence(text='This leads to suboptimal scores, but it also makes the output of a semantic segmentation approach harder to use without further post - processing.', num=235), Sentence(text='Since inaccurate boundaries are often not apparent from the standard evaluation metric scores, a typical approach is a trimap evaluation in order to quantify detailed boundary adherence [reference ][ reference ][ reference].', num=236), Sentence(text='During trimap evaluation, all predictions are ignored if they do not fall within a certain radius r of a ground truth label boundary.', num=237), Sentence(text='Figure 6 visualizes our trimap evaluation performed on the validation set for varying trimap widths r between 1 and 80 pixels.', num=238), Sentence(text='We compare to LRR [reference] and Dilation [reference], who made code and pre - trained models available.', num=239), Sentence(text='We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries.', num=240)], text="The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions. Even though we only train on half - resolution images, Figure 5 clearly shows we can match the current published state - of - the - art (LRR [reference] Figure 7. Qualitative comparison on the Cityscapes validation set. Interesting cases are the fence in the first row, the truck in the second row, or the street light poles in the last row. An interesting failure case is shown in the third row: all methods struggle to find the correct sidewalk boundary, however our network makes a clean and reasonable prediction. section: Boundary Adherence Due to several pooling operations (and subsequent upsampling) in many of today 's FCN architectures, boundaries are often overly smooth, resulting in lost details and edge - bleeding. This leads to suboptimal scores, but it also makes the output of a semantic segmentation approach harder to use without further post - processing. Since inaccurate boundaries are often not apparent from the standard evaluation metric scores, a typical approach is

In [33]:
print("\n---\n---> Founded answers:")
for ans in question_with_answers.answers:
    print(ans.text)
    print(ans.confidence)
    print(ans.chunk.text)
    print("----------------------\n")

---
---> Founded answers:
overfitting
0.04313625767827034
We will make code for the gradient computation for arbitrary networks publicly available in Theano / Lasagne. In order to reduce overfitting, we used two methods of data augmentation: translation augmentation and gamma augmentation. The former method randomly translates an image and its annotations. In order to keep consistent image dimensions, we have to pad the translated images and annotations. To this end, we use reflection padding on the image and constant padding with void labels on the annotations. Our second method of data augmentation is gamma augmentation. We use a slightly modified gamma augmentation method detailed in Appendix A. section: Experimental Evaluation We evaluate our approach on the recently released Cityscapes benchmark [reference] containing images recorded in 50 different cities. This benchmark provides 5, 000 images with high - quality annotations split up into a training, validation, and test set (2, 975, 500, and 1, 525 images, respectively). The dense pixel annotations span 30 classes frequently occurring in urban street scenes, out of which 19 are used for actual training and evaluation. Annotations for the test set remain private and comparison to other methods is performed via a dedicated evaluation server. We report the results of our FRRNs for two settings: FRRN A trained on quarter - resolution (256 × 512) Cityscapes images; and FRRN B trained on half - resolution (512 × 1024) images. We then upsample our predictions using bilinear interpolation in order to report scores at the full image resolution of 1024 × 2048 pixels. Directly training at the full Cityscapes resolution turned out to be too memory intensive with our current design. However, as our experimental results will show, even when trained only on halfresolution images, our FRRN B 's results are competitive with the best published methods trained on full - resolution data.
----------------------

stereo or optical flow
0.010819800023455173
We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries. Our method achieves better boundary adherence, both numerically and qualitatively (see Figure 7), with a much simpler architecture and without ImageNet pre - training. Often one can boost both the numerical score and the boundary adherence by using a fully connected CRF as post - processing step. We tried to apply a fully connected CRF with Gaussian kernel, as introduced by Krähenbühl and Kolton [reference]. We used the standard appearance and smoothness kernels and tuned parameters on the validation set by running several thousand Hyperopt iterations [reference]. Surprisingly the color standard deviation for the appearance kernel tended towards very small values, while the weight did not go to zero. This indicates that the appearance kernel would only smooth labels across pixels with very similar colors. Nevertheless, with the best parameters we only obtained an IoU boost of ∼ 0. 5 % on the validation set. Given the high computation time we decided against any post - processing steps. section: Conclusion In this paper we propose a novel network architecture for semantic segmentation in street scenes. Our architecture is clean, does not require additional post - processing, can be trained from scratch, shows superior boundary adherence, and reaches state - of - the - art results on the Cityscapes benchmark. We will provide code and all trained models. Since we do not incorporate design choices specifically tailored towards semantic segmentation, we believe that our architecture will also be applicable to other tasks such as stereo or optical flow where predictions are performed per pixel. Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 .
----------------------

look at the deviation of U from 0. 5 .
0.010365484282374382
Our goal is to find γ such that E U [U] = 0. 5 . The key idea to solving this problem is to look at the deviation of U from 0. 5 . Let Z be this deviation. Then (11) is equivalent to Hence, without solving for the implicitly defined variable U explicitly, we found a transformation of a zero - mean random variable Z such that γ has the desired properties. Because Z was defined to be the offset from 0. 5  and U ∈ [0, 1], it follows Z ∈ [−0. 5 , 0. 5 ]. We are free to choose any distribution such that Z has zero mean and falls into the range [−0. 5 , 0. 5 ]. For simplicity reasons, we choose Z to be uniformly distributed over [−a, a] where a ∈ [0, 0. 5 ] determines the strength of the augmentation. Figure 8b illustrates the obvious bias reduction. section: B. Baseline Evaluation In Section 5. 2  of the main paper, we describe the setting of our baseline method (Residual Network Baseline) and compare it to our FRRN A network. To emphasize on a proper training procedure of both baselines, Figure 9 shows the mean IoU score on the validation set over time. We can see that our model outperforms the baseline with a significant margin and both methods are trained until convergence. Figure 10 shows and compares addtional output labelings of our method. Please also consult our labeled video sequence [reference] to gain a better sense of the quality of our method. We all know Latex is a pain. section: C. Qualitative Results section: Image Ground Truth Ours LRR [reference] Figure 10. Additional qualitative results on the Cityscapes validation set.
----------------------

bootstrapped cross - entropy loss
0.0026516092475503683
We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations. The pooled feature maps are then successively upscaled using bilinear interpolation in the decoder. Furthermore, similar to Simonyan and Zisserman [reference], we define a number of base channels that we double after each pooling operation (up to a certain upper limit). Instead of choosing 64 base channels as in VGG net, we use 48 channels in order to have a manageable number of trainable parameters. Depending on the input image resolution, we use FRRN A or FRRN B to keep the relative size of the receptive fields consistent. section: Training Procedure Following Wu et al. , we train our network by minimizing a bootstrapped cross - entropy loss [reference]. Let c be the number of classes, y 1,. , y N ∈ {1,. , c} be the target class labels for the pixels 1,. , N, and let p i, j be the posterior class + Bias Softmax probability for class j and pixel i. Then, the bootstrapped cross - entropy loss over K pixels is defined as where 1 [x] = 1 iff x is true and t k ∈ R is chosen such that |{i ∈ {1,. , N}: p i, yi < t k} | = K. The threshold parameter t k can easily be determined by sorting the predicted log probabilities and choosing the K + 1 - th one as threshold. Figure 4 visualizes the concept. Depending on the number of pixels K that we consider, we select misclassified pixels or pixels where we predict the correct label with a small probability. We minimize the loss using ADAM [reference].
----------------------

correct sidewalk boundary
0.0023512907791882753
The solid lines show the mean IoU score of our approach and two top performing methods that released their code. The dashed lines show the mean IoU score when using the 7 Cityscapes category labels for the same methods. the same image resolutions. Even though we only train on half - resolution images, Figure 5 clearly shows we can match the current published state - of - the - art (LRR [reference] Figure 7. Qualitative comparison on the Cityscapes validation set. Interesting cases are the fence in the first row, the truck in the second row, or the street light poles in the last row. An interesting failure case is shown in the third row: all methods struggle to find the correct sidewalk boundary, however our network makes a clean and reasonable prediction. section: Boundary Adherence Due to several pooling operations (and subsequent upsampling) in many of today 's FCN architectures, boundaries are often overly smooth, resulting in lost details and edge - bleeding. This leads to suboptimal scores, but it also makes the output of a semantic segmentation approach harder to use without further post - processing. Since inaccurate boundaries are often not apparent from the standard evaluation metric scores, a typical approach is a trimap evaluation in order to quantify detailed boundary adherence [reference ][ reference ][ reference]. During trimap evaluation, all predictions are ignored if they do not fall within a certain radius r of a ground truth label boundary. Figure 6 visualizes our trimap evaluation performed on the validation set for varying trimap widths r between 1 and 80 pixels. We compare to LRR [reference] and Dilation [reference], who made code and pre - trained models available. We see that our approach outperforms the competition consistently for all radii r. Furthermore, it shall be noted that the method of [reference] is based on an architecture specifically designed for clean boundaries.
----------------------

upscaling by repeating the entries along the spatial dimensions
0.0022367131896317005
This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design. The unit first concatenates the two incoming streams by using a pooling layer in order to reduce the size of the residual stream. Then the concatenated features are fed through two convolution units. Each convolution unit consists of a 3 × 3 convolution layer followed by a batch normalization layer [reference] and a ReLU activation function. The result of the second convolution unit is used in two ways. First, it forms the pooling stream input of the next FRRU in the network and second it is the basis for the computed residual. To this end, we first adjust the number of feature channels using a 1 × 1 convolution and then upscale the spatial dimensions using an unpooling layer. Because the features might have to be upscaled significantly (e.g., by a factor of 16), we found that simply upscaling by repeating the entries along the spatial dimensions performed superior to bilinear interpolation. In Figure 3, the inner red box corresponds to the function G while the outer blue box corresponds to the function H. We can see that the output of G is used in order to compute H, because the red box is entirely contained within the blue box. As shown above, this design choice results in superior gradient flow properties for all weights of the unit. Table 1 shows the two network architectures that we used in order to assess our approach 's segmentation performance. The proposed architectures are based on several principles employed by other authors. We follow Noh et al. [reference] and use an encoder / decoder formulation. In the encoder, we reduce the size of the pooling stream using max pooling operations.
----------------------

no residuals are computed
0.0014246442588046193
Let z n−1 be the residual input to the n - th FRRU and let y n−1 be its pooling input. Then the outputs are computed as where W n are the parameters of the functions G and H, respectively. If G ≡ 0, then an FRRU corresponds to an RU since it disregards the pooling input y n, and the network effectively becomes an ordinary ResNet. On the other hand, if H ≡ 0, then the output of an FRRU only depends on its input via the function G. Hence, no residuals are computed and we obtain a traditional feedforward network. By carefully constructing G and H, we can combine the two network principles. In order to show that FRRNs have similar training characteristics as ResNets, we adapt the analysis presented in [reference] to our case. Using the same recursive argument as before, we find that for m > n, z m has the representation We can then express the derivative of the loss l with respect to the weights W n as Hence, the weight updates depend on three sources of information. Analogous to the analysis of ResNets, the two sources ∂H (yi, zi;Wi + 1) ∂zn depend crucially on the depth n, while the term ∂l ∂zm is independent of the depth. Thus, we achieve a depth - independent gradient flow for all parameters that are used by the residual function H. If we use some of these weights in order to compute the output of G, all weights of the unit benefit from the improved gradient flow. This is most easily achieved by reusing the output of G in order to compute H. However, we note that other designs are possible. Figure 3 shows our proposed FRRU design.
----------------------

precise semantic segmentation
0.0009385889861732721
Our proposed ResNet - like architecture unites strong recognition performance with precise localization capabilities by combining two distinct processing streams. One stream undergoes a sequence of pooling operations and is responsible for understanding large - scale relationships of image elements; the other stream carries feature maps at the full image resolution, resulting in precise boundary adherence. This idea is visualized in Figure 1, where the two processing streams are shown in blue and red. The blue residual lane reflects the high - resolution stream. It can be combined with classical residual units (left and right), as well as with our new full - resolution residual units (FRRU). The FRRUs from the red pooling lane act as residual units for the blue stream, but also undergo pooling operations and carry high - level information through the network. This results in a network that successively combines and computes features at two resolutions. This paper makes the following contributions: (i) We propose a novel network architecture geared towards precise semantic segmentation in street scenes which is not limited to pre - trained architectures and achieves state - ofthe - art results. (ii) We propose to use two processing streams to realize strong recognition and strong localization performance: One stream undergoes a sequence of pooling operations while the other stream stays at the full image resolution. (iii) In order to foster further research in this area, we publish our code and the trained models in Theano / Lasagne [reference ][ reference] 1. 1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.
----------------------

smoothing the network predictions
0.0007261462160386145
To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers. Pooling layers in FCNs fulfill a crucial role in order to increase the receptive field size of later units and with it the classification performance. However, they have the downside that the resulting network outputs are at a lower resolution. To overcome this, various strategies have been proposed. Some approaches extract features from intermediate layers via some sort of skip connections [reference ][ reference ][ reference ][ reference]. Noh et al. propose an encoder / decoder network [reference]. The encoder computes low - dimensional feature representations via a sequence of pooling and convolution operations. The decoder, which is stacked on top of the encoder, then learns an upscaling of these low - dimensional features via subsequent unpooling and deconvolution operations [reference]. Similarly, Badrinarayanan et al. [reference ][ reference] use convolutions instead of deconvolutions in the decoder network. In contrast, our approach preserves high - resolution information throughout the entire network by keeping a separate high - resolution processing stream. Many approaches apply smoothing operations to the output of a CNN in order to obtain more consistent predictions. Most commonly, conditional random fields (CRFs) [reference] are applied on the network output [reference ][ reference ][ reference ][ reference ][ reference]. More recently, some papers approximate the mean - field inference of CRFs using specialized network architectures [reference ][ reference ][ reference]. Other approaches to smoothing the network predictions include domain transform [reference ][ reference] and superpixel - based smoothing [reference ][ reference]. Our approach is able to swiftly combine high - and low - resolution information, resulting in already smooth output predictions. Experiments with additional CRF smoothing therefore did not result in significant performance improvements. Network architectures.
----------------------

Training FRRN B
0.0007058468763716519
The resulting ResNet has slightly fewer parameters than the original FRRN (16. 7  × 10 6 vs. 17. 7  × 10 6). This is due to the fact that RUs lack the 1 × 1 convolutions that connect the pooling to the residual Table 2. IoU scores from the cityscapes test set. We highlight the best published baselines for the different sampling rates. (Additional anonymous submissions exist as concurrent work. ) Bold numbers represent the best, italic numbers the second best score for a class. We also indicate the subsampling factor used on the input images, whether additional coarsely annotated data was used, and whether the model was initialized with pre - trained weights. stream. section: Method We train both networks on the quarter - resolution Cityscapes dataset for 45, 000 iterations at a batch size of 3. We use a learning rate of 10 −3 for the first 35, 000 iterations and then reduce it to 10 −4 for the following 10, 000 iterations. Both networks converged within these iterations. The FRRN A resulted in a validation set mean IoU score of 65. 7 % while the ResNet baseline only achieved 62. 8 %, showing a significant advantage of our FRRNs. Training FRRN B is performed in a similar fashion. Detailed training curves are shown in Appendix B. section: Quantitative Evaluation Overview In Table 2 we compare our method to the best (published) performers on the Cityscapes leader board, namely LRR [reference], Adelaide [reference], and Dilation [reference]. Note that our network performs on par with the very complex and well engineered system by [reference]. Among the top performers on Cityscapes, only ENet refrain from using a pre - trained network. However, they design their network for real time performance and thus do not obtain top scores.
----------------------

semantic segmentation
0.0005423750844784081

In [34]:
validator = AnswerValidator()
result = validator.process(question_with_answers.answers, reference_answers[0])

In [35]:
result

{'reference_answer': 'Semantic Segmentation',
 'valid_answers_count': 2,
 'valid_answers': [Answer(text='semantic segmentation', chunk=TextChunk(sentences=[Sentence(text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.', num=45), Sentence(text='As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference].', num=46), Sentence(text='In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations.', num=47), Sentence(text='Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures.', num=48), Sentence(text='Semantic Segmentation Approaches.', num=49), Sentence(text='Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs).', num=50), Sentence(text='Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference].', num=51), Sentence(text='Rather than classifying entire regions in the first place, the approach by Farabet et al.', num=52), Sentence(text='performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference].', num=53), Sentence(text='The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al.', num=54), Sentence(text='[reference] opened a wide range of semantic segmentation research using end - to - end training [reference].', num=55), Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58)], text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', word_token_count=371), confidence=0.0005423750844784081, start_pos=120, end_pos=141),
  Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)],
 'analysis': {'keywords': ['aggregation',
   'pretraine',
   'drive',
   'layerreference',
   'early',
   'algorithm',
   'propagate',
   'neural',
   'current',
   'add',
   'year',
   'open',
   'resnet',
   'reformulate',
   'recent',
   'new',
   'increase',
   'fullresolution',
   'superpixel',
   'cnn'],
  'chunks': [TextChunk(sentences=[Sentence(text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.', num=45), Sentence(text='As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference].', num=46), Sentence(text='In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations.', num=47), Sentence(text='Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures.', num=48), Sentence(text='Semantic Segmentation Approaches.', num=49), Sentence(text='Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs).', num=50), Sentence(text='Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference].', num=51), Sentence(text='Rather than classifying entire regions in the first place, the approach by Farabet et al.', num=52), Sentence(text='performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference].', num=53), Sentence(text='The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al.', num=54), Sentence(text='[reference] opened a wide range of semantic segmentation research using end - to - end training [reference].', num=55), Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58)], text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', word_token_count=371),
   TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362)]}}

In [36]:
def get_qa_attention_weights(question, context):
    """
    Визуализирует веса внимания модели RoBERTa для QA между вопросом и контекстом.
    
    Args:
        question (str): Текст вопроса
        context (str): Текст контекста для поиска ответа
        model_name (str): Название предобученной модели (по умолчанию 'deepset/roberta-base-squad2')
    
    Returns:
        dict: Словарь с токенами и их весами внимания
    """
    
    # Загрузка модели и токенизатора
    model = BERTEngQASingleton()

    tokenizer = model.tokenizer
    model = model.model
    
    # Токенизация
    inputs = tokenizer(question, context, return_tensors='pt', truncation=True, max_length=512)
    inputs = {key: value.to(device) for key, value in inputs.items()}
    input_ids = inputs['input_ids']
    
    # Получение предсказаний модели с вниманием
    with torch.no_grad():
        outputs = model(**inputs)
        attentions = outputs.attentions  # Все слои внимания
    
    # Среднее внимание по всем головам и слоям
    all_attentions = torch.stack(attentions)  # [layers, batch, heads, seq_len, seq_len]
    averaged_attention = all_attentions.mean(dim=(0, 1, 2))  # [seq_len, seq_len]
    
    # Индексы токенов контекста (после [SEP])
    sep_index = torch.where(input_ids[0] == tokenizer.sep_token_id)[0][0].item()
    context_start = sep_index + 1
    context_end = len(input_ids[0]) - 1  # Исключаем конечный [SEP]
    
    # Извлекаем внимание к токенам контекста
    context_attention = averaged_attention[context_start:context_end+1, context_start:context_end+1]
    
    # Агрегируем внимание по строкам (входящие связи)
    token_importance = context_attention.mean(dim=0)
    
    # Нормализация
    token_importance = token_importance / token_importance.sum()
    
    # Сопоставление с токенами
    context_tokens = tokenizer.convert_ids_to_tokens(input_ids[0][context_start:context_end+1])
    
    return {
        'tokens': context_tokens,
        'attention_weights': token_importance.cpu().numpy(),
        'question': question,
        'context': context
    }

In [37]:
def clean_token(token):
    """Очищает токен от специальных символов RoBERTa"""
    # Убираем символ пробела Ġ
    cleaned = token.replace('Ġ', ' ')
    # Убираем лишние пробелы
    cleaned = cleaned.strip()
    # Убираем точки, которые являются частью токенизации (но не в середине слова)
    if cleaned.endswith('.') and len(cleaned) > 1:
        cleaned = cleaned[:-1]
    # Приводим к нижнему регистру
    cleaned = cleaned.lower()
    return cleaned

def reconstruct_words(tokens, weights):
    """Восстанавливает полные слова из субтокенов"""
    words = []
    word_weights = []
    current_word = ""
    current_weight = 0
    count = 0
    
    for token, weight in zip(tokens, weights):
        cleaned_token = clean_token(token)
        
        # Пропускаем пустые токены после очистки
        if not cleaned_token:
            continue
            
        # Если токен начинается с пробела - это новое слово
        if token.startswith('Ġ') and current_word:
            # Убираем возможную точку в конце слова
            if current_word.endswith('.'):
                current_word = current_word[:-1]
            words.append(current_word)
            word_weights.append(current_weight / count if count > 0 else 0)
            current_word = cleaned_token
            current_weight = weight
            count = 1
        else:
            # Продолжение текущего слова (субтокен)
            current_word += cleaned_token
            current_weight += weight
            count += 1
    
    # Добавляем последнее слово
    if current_word:
        # Убираем возможную точку в конце последнего слова
        if current_word.endswith('.'):
            current_word = current_word[:-1]
        words.append(current_word)
        word_weights.append(current_weight / count if count > 0 else 0)
    
    return words, np.array(word_weights)

def filter_special_tokens(tokens, weights):
    """Фильтрует специальные токены"""
    valid_tokens = []
    valid_weights = []
    
    special_tokens = ['<s>', '</s>', '<pad>', '[CLS]', '[SEP]', '.', '?', '!', ',', '/', '//', '][']
    
    for token, weight in zip(tokens, weights):
        # Пропускаем специальные токены и знаки препинания
        if (token not in special_tokens and 
            not token.startswith('<') and 
            not token.endswith('>') and
            len(token.strip('.')) > 0):  # Исключаем токены, состоящие только из точек
            valid_tokens.append(token)
            valid_weights.append(weight)
    
    return valid_tokens, np.array(valid_weights)

In [38]:
def visualize_top_attention_clean(tokens, weights, top_k=10):
    """Визуализация с очищенными токенами"""
    # Фильтруем специальные токены
    filtered_tokens, filtered_weights = filter_special_tokens(tokens, weights)
    
    # Восстанавливаем полные слова
    words, word_weights = reconstruct_words(filtered_tokens, filtered_weights)
    
    # Нормализуем веса после восстановления
    # if len(word_weights) > 0:
    #    word_weights = word_weights / word_weights.sum()
    
    indices = np.argsort(word_weights)[::-1][:top_k]
    
    print("Топ-%d наиболее важных слов:" % top_k)
    for i, idx in enumerate(indices):
        if i < len(words):
            print(f"{i+1}. '{words[idx]}': {word_weights[idx]:.4f}")

In [50]:
def keywords_top_attention_clean(tokens, weights, top_k=10):
    """Визуализация с очищенными токенами"""
    # Фильтруем специальные токены
    filtered_tokens, filtered_weights = filter_special_tokens(tokens, weights)
    
    # Восстанавливаем полные слова
    words, word_weights = reconstruct_words(filtered_tokens, filtered_weights)
    
    # Нормализуем веса после восстановления
    # if len(word_weights) > 0:
    #    word_weights = word_weights / word_weights.sum()
    
    indices = np.argsort(word_weights)[::-1][:top_k]

    keywords = []

    for i, idx in enumerate(indices):
        if i < len(words):
            keywords.append({
                'word': words[idx],
                'weight': word_weights[idx]
            })

    return keywords

In [39]:
question = "What is the capital of France?"
context = "The capital of France is Paris, which is located in the north-central part of the country."
    
result = get_qa_attention_weights(question, context)
visualize_top_attention_clean(result['tokens'], result['attention_weights'], top_k=100)

Топ-100 наиболее важных слов:
1. 'paris': 0.0578
2. 'capital': 0.0430
3. 'is': 0.0401
4. 'which': 0.0336
5. 'located': 0.0308
6. 'france': 0.0297
7. 'country': 0.0293
8. 'in': 0.0278
9. 'the': 0.0268
10. 'the': 0.0265
11. 'is': 0.0261
12. 'north-central': 0.0257
13. 'part': 0.0241
14. 'of': 0.0194
15. 'the': 0.0186
16. 'of': 0.0184

In [40]:
validator = AnswerValidator()
result = validator.process(question_with_answers.answers, reference_answers[0])
result

{'reference_answer': 'Semantic Segmentation',
 'valid_answers_count': 2,
 'valid_answers': [Answer(text='semantic segmentation', chunk=TextChunk(sentences=[Sentence(text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.', num=45), Sentence(text='As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference].', num=46), Sentence(text='In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations.', num=47), Sentence(text='Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures.', num=48), Sentence(text='Semantic Segmentation Approaches.', num=49), Sentence(text='Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs).', num=50), Sentence(text='Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference].', num=51), Sentence(text='Rather than classifying entire regions in the first place, the approach by Farabet et al.', num=52), Sentence(text='performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference].', num=53), Sentence(text='The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al.', num=54), Sentence(text='[reference] opened a wide range of semantic segmentation research using end - to - end training [reference].', num=55), Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58)], text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', word_token_count=371), confidence=0.0005423750844784081, start_pos=120, end_pos=141),
  Answer(text='Semantic image segmentation', chunk=TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362), confidence=3.913524415111169e-05, start_pos=0, end_pos=27)],
 'analysis': {'keywords': ['aggregation',
   'pretraine',
   'drive',
   'layerreference',
   'early',
   'algorithm',
   'propagate',
   'neural',
   'current',
   'add',
   'year',
   'open',
   'resnet',
   'reformulate',
   'recent',
   'new',
   'increase',
   'fullresolution',
   'superpixel',
   'cnn'],
  'chunks': [TextChunk(sentences=[Sentence(text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios.', num=45), Sentence(text='As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference].', num=46), Sentence(text='In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations.', num=47), Sentence(text='Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures.', num=48), Sentence(text='Semantic Segmentation Approaches.', num=49), Sentence(text='Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs).', num=50), Sentence(text='Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference].', num=51), Sentence(text='Rather than classifying entire regions in the first place, the approach by Farabet et al.', num=52), Sentence(text='performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference].', num=53), Sentence(text='The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al.', num=54), Sentence(text='[reference] opened a wide range of semantic segmentation research using end - to - end training [reference].', num=55), Sentence(text='Long et al.', num=56), Sentence(text='further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture.', num=57), Sentence(text='To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', num=58)], text='1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', word_token_count=371),
   TextChunk(sentences=[Sentence(text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks.', num=13), Sentence(text='In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference].', num=14), Sentence(text='Example output and the abstract structure of our fullresolution residual network.', num=15), Sentence(text='The network has two processing streams.', num=16), Sentence(text='The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations.', num=17), Sentence(text='The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference].', num=18), Sentence(text='Many of those applications require precise region boundaries [reference].', num=19), Sentence(text='In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence.', num=20), Sentence(text='Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class.', num=21), Sentence(text='Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference].', num=22), Sentence(text='Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', num=23)], text='Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.', word_token_count=362)]}}

In [41]:
valid_chunks = [ans.chunk.text for ans in result['valid_answers']]
valid_chunks

['1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.',
 'Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.']

In [42]:
result1 = get_qa_attention_weights(question = questions[0], context = valid_chunks[0])

In [44]:
visualize_top_attention_clean(result1['tokens'], result1['attention_weights'], top_k=100)

Топ-100 наиболее важных слов:
1. 'the': 0.0042
2. 'the': 0.0039
3. 'performs': 0.0039
4. 'on': 0.0034
5. 'training': 0.0032
6. 'constrained': 0.0032
7. 'opened': 0.0032
8. 'we': 0.0032
9. 'classification': 0.0031
10. 'research': 0.0029
11. 'classification': 0.0028
12. 'early': 0.0028
13. 'train': 0.0028
14. 'to': 0.0027
15. 'the': 0.0027
16. 'dataset': 0.0027
17. 'work': 0.0027
18. 'as': 0.0026
19. 'rather': 0.0026
20. 'using': 0.0025
21. 'by': 0.0025
22. 'neural': 0.0025
23. 'introduction': 0.0025
24. 'further': 0.0025
25. 'algorithms': 0.0024
26. 'including': 0.0024
27. 'for': 0.0024
28. 'to': 0.0024
29. 'work': 0.0024
30. 'using': 0.0024
31. 'we': 0.0023
32. 'were': 0.0023
33. '//': 0.0023
34. 'datasets': 0.0023
35. 'by': 0.0023
36. 'have': 0.0023
37. 'crucial': 0.0023
38. 'and': 0.0023
39. 'improvements': 0.0023
40. 'approaches': 0.0023
41. '1': 0.0023
42. 'enabling': 0.0023
43. 'and': 0.0022
44. 'networks': 0.0022
45. 'section:': 0.0022
46. 'reformulated': 0.0022
47. 'approaches': 0.0022
48. 'aggregation': 0.0022
49. 'this': 0.0022
50. 'followed': 0.0022
51. 'research': 0.0022
52. 'annotations': 0.0022
53. 'using': 0.0022
54. 'will': 0.0022
55. 'imagery': 0.0022
56. 'success': 0.0022
57. 'approach': 0.0022
58. 'cityscapes': 0.0022
59. 'improve': 0.0021
60. '/': 0.0021
61. 'architecture': 0.0021
62. 'githubcom': 0.0021
63. 'the': 0.0021
64. 'cnn': 0.0021
65. 'for': 0.0021
66. 'our': 0.0021
67. 'long': 0.0021
68. 'autonomous': 0.0021
69. 'as': 0.0021
70. 'followed': 0.0021
71. 'over': 0.0020
72. 'semantic': 0.0020
73. 'pixel': 0.0020
74. 'from': 0.0020
75. 'architectures': 0.0020
76. '/': 0.0020
77. 'network': 0.0020
78. 'which': 0.0020
79. 'semantic': 0.0020
80. 'a': 0.0020
81. 'image': 0.0020
82. 'on': 0.0020
83. 'focus': 0.0020
84. 'given': 0.0020
85. 'their': 0.0020
86. 'successful': 0.0020
87. 'at': 0.0020
88. 'learning': 0.0019
89. 'classifying': 0.0019
90. 'virtual': 0.0019
91. 'approaches': 0.0019
92. 'such': 0.0019
93. 'predictions': 0.0019
94. 'the': 0.0019
95. 'fully': 0.0019
96. 'this': 0.0019
97. 'is': 0.0019
98. 'models': 0.0019
99. 'in': 0.0019
100. 'multiple': 0.0019

In [45]:
result2 = get_qa_attention_weights(question = questions[0], context = valid_chunks[1])
visualize_top_attention_clean(result2['tokens'], result2['attention_weights'], top_k=100)

Топ-100 наиболее важных слов:
1. 'modeling': 0.0037
2. 'task': 0.0037
3. 'it': 0.0036
4. 'the': 0.0035
5. 'we': 0.0034
6. 'the': 0.0033
7. 'current': 0.0032
8. 'approaches': 0.0031
9. 'employ': 0.0030
10. 'assigning': 0.0030
11. 'classification': 0.0029
12. 'the': 0.0029
13. 'example': 0.0029
14. 'discard': 0.0028
15. 'all': 0.0028
16. 'work': 0.0028
17. 'is': 0.0028
18. 'that': 0.0028
19. 'training': 0.0027
20. 'starting': 0.0027
21. 'require': 0.0027
22. 'the': 0.0027
23. 'our': 0.0027
24. 'operations': 0.0026
25. 'achieving': 0.0026
26. 'automotive': 0.0026
27. 'using': 0.0026
28. 'papers': 0.0026
29. 'or': 0.0025
30. 'network': 0.0025
31. 'architectures': 0.0025
32. 'of': 0.0025
33. 'task': 0.0025
34. 'where': 0.0025
35. 'to': 0.0025
36. 'semantic': 0.0025
37. 'many': 0.0025
38. 'applications': 0.0024
39. 'and': 0.0024
40. 'detection': 0.0024
41. 'data': 0.0024
42. 'pixels': 0.0024
43. 'can': 0.0024
44. 'auxiliary': 0.0024
45. 'reduces': 0.0024
46. 'segmentation': 0.0024
47. 'task': 0.0024
48. 'or': 0.0023
49. 'some': 0.0023
50. 'takes': 0.0023
51. 'for': 0.0023
52. 'are': 0.0023
53. 'network': 0.0023
54. 'used': 0.0023
55. 'using': 0.0023
56. 'improve': 0.0023
57. 'semantic': 0.0023
58. 'coupled': 0.0022
59. 'this': 0.0022
60. 'weights': 0.0022
61. 'such': 0.0022
62. 'pursue': 0.0022
63. 'classification': 0.0022
64. 'has': 0.0022
65. 'class': 0.0022
66. 'stays': 0.0022
67. 'in': 0.0021
68. '][': 0.0021
69. 'reference],': 0.0021
70. 'network': 0.0021
71. '][': 0.0021
72. 'many': 0.0021
73. 'image': 0.0021
74. 'usually': 0.0021
75. '][': 0.0021
76. 'image': 0.0021
77. 'application': 0.0021
78. 'network': 0.0020
79. 'semantic': 0.0020
80. 'therefore': 0.0020
81. 'nets': 0.0020
82. '][': 0.0020
83. 'target': 0.0020
84. '][': 0.0020
85. 'geometry': 0.0020
86. 'boundaries': 0.0020
87. 'variants': 0.0020
88. 'by': 0.0019
89. 'network': 0.0019
90. 'to': 0.0019
91. '][': 0.0019
92. 'segmentation': 0.0019
93. '][': 0.0019
94. 'unlikely': 0.0019
95. 'reference],': 0.0019
96. 'and': 0.0019
97. 'often': 0.0019
98. 'for': 0.0019
99. 'architecture': 0.0019
100. 'from': 0.0019

# -----------------------------

In [46]:
print(f"chunk_texts до фильтрации IDF:\n '{valid_chunks}'")

#chunk_texts = filter_uniform_words(chunk_texts, IDF_THRESHOLD)
valid_chunks = dymamic_filter_uniform_words(valid_chunks, IDF_THRESHOLD)[0]

chunk_texts до фильтрации IDF:
 '['1 https: // github.com / TobyPDE / FRRN section: Related Work The dramatic performance improvements from using CNNs for semantic segmentation have brought about an increasing demand for such algorithms in the context of autonomous driving scenarios. As a large amount of annotated data is crucial in order to train such deep networks, multiple new datasets have been released to encourage further research in this area, including Synthia [reference], Virtual KITTI [reference], and Cityscapes [reference]. In this work, we focus on Cityscapes, a recent large - scale dataset consisting of real - world imagery with well - curated annotations. Given their success, we will constrain our literature review to deep learning based semantic segmentation approaches and deep learning network architectures. Semantic Segmentation Approaches. Over the last years, the most successful semantic segmentation approaches have been based on convolutional neural networks (CNNs). Early approaches constrained their output to a bottom - up segmentation followed by a CNN based region classification [reference]. Rather than classifying entire regions in the first place, the approach by Farabet et al. performs pixel - wise classification using CNN features originating from multiple scales, followed by aggregation of these noisy pixel predictions over superpixel regions [reference]. The introduction of so - called fully convolutional networks (FCNs) for semantic image segmentation by Long et al. [reference] opened a wide range of semantic segmentation research using end - to - end training [reference]. Long et al. further reformulated the popular VGG architecture [reference] as a fully convolutional network (FCN), enabling the use of pretrained models for this architecture. To improve segmentation performance at object boundaries, skip connections were added which allow information to propagate directly from early, high - resolution layers to deeper layers.', 'Semantic image segmentation [reference ][ reference ][ reference ][ reference ][ reference], the task of assigning a set of predefined class labels to image pixels, is an important tool for modeling the complex relationships of the semantic entities usually found in street scenes, such as cars, pedestrians, road, or sidewalks. In automotive scenarios it is used in various ways, e.g. as a pre - processing step to discard image regions that are unlikely to contain objects of interest [reference ][ reference], to improve object detection [reference ][ reference ][ reference ][ reference]. Example output and the abstract structure of our fullresolution residual network. The network has two processing streams. The residual stream (blue) stays at the full image resolution, the pooling stream (red) undergoes a sequence of pooling and unpooling operations. The two processing streams are coupled using full - resolution residual units [reference] or in combination with 3D scene geometry [reference ][ reference ][ reference]. Many of those applications require precise region boundaries [reference]. In this work, we therefore pursue the goal of achieving high - quality semantic segmentation with precise boundary adherence. Current state - of - the - art approaches for image segmentation all employ some form of fully convolutional network (FCNs) [reference] that takes the image as input and outputs a probability map for each class. Many papers rely on network architectures that have already been proven successful for image classification such as variants of the ResNet [reference] or the VGG architecture [reference]. Starting from pre - trained nets, where a large number of weights for the target task can be pre - set by an auxiliary classification task, reduces training time and often yields superior performance compared to training a network from scratch using the (possibly limited amount of) data of the target application.']'

In [47]:
print(f"chunk_texts после фильтрации IDF:\n '{valid_chunks}'")

chunk_texts после фильтрации IDF:
 '['https frrn section relate dramatic improvement cnn bring about increase demand algorithm context autonomous drive annotate crucial order deep multiple new dataset release encourage far research area include virtual cityscape focus cityscape recent scale dataset consist real world imagery well curate annotation give their success will constrain literature review deep learn base deep learn over last year most base neural early constrain their bottom up follow base rather than classify entire first place et al perform wise feature originate multiple scale follow aggregation these noisy prediction over superpixel introduction so call long et al open wide range research end end long et al far reformulate popular enable pretraine skip connection add which allow information propagate directly early layer deeply layer', 'reference reference reference reference task assign set predefine class label important tool complex relationship entity usually find street scene car pedestrian road or sidewalk automotive it various way pre process step discard that unlikely contain interest reference detection reference reference reference example abstract structure fullresolution residual two process stream residual stream stay full pool stream undergoe sequence pool unpoole operation two process stream couple full residual unit or combination 3d scene geometry reference reference many those application require precise therefore pursue goal achieve quality precise adherence current state art all employ some form that take input probability map each class many paper rely that already prove variant resnet or start pre net where number weight target task can pre set auxiliary task reduce time often yield superior compare scratch limit target application']'

In [48]:
len(valid_chunks)

2

In [51]:
result1_m = keywords_top_attention_clean(result1['tokens'], 
        result1['attention_weights'], top_k=100)

result1_m

[{'word': 'the', 'weight': np.float32(0.004204311)},
 {'word': 'the', 'weight': np.float32(0.003936652)},
 {'word': 'performs', 'weight': np.float32(0.0039064568)},
 {'word': 'on', 'weight': np.float32(0.003398265)},
 {'word': 'training', 'weight': np.float32(0.003206912)},
 {'word': 'constrained', 'weight': np.float32(0.0031933999)},
 {'word': 'opened', 'weight': np.float32(0.0031924634)},
 {'word': 'we', 'weight': np.float32(0.0031579488)},
 {'word': 'classification', 'weight': np.float32(0.0030524763)},
 {'word': 'research', 'weight': np.float32(0.0028580574)},
 {'word': 'classification', 'weight': np.float32(0.002821498)},
 {'word': 'early', 'weight': np.float32(0.0028180352)},
 {'word': 'train', 'weight': np.float32(0.0027581344)},
 {'word': 'to', 'weight': np.float32(0.0027053903)},
 {'word': 'the', 'weight': np.float32(0.0027015836)},
 {'word': 'dataset', 'weight': np.float32(0.0026851872)},
 {'word': 'work', 'weight': np.float32(0.002657178)},
 {'word': 'as', 'weight': np.float32(0.0026388536)},
 {'word': 'rather', 'weight': np.float32(0.002575087)},
 {'word': 'using', 'weight': np.float32(0.0024733632)},
 {'word': 'by', 'weight': np.float32(0.0024637934)},
 {'word': 'neural', 'weight': np.float32(0.002452692)},
 {'word': 'introduction', 'weight': np.float32(0.0024521477)},
 {'word': 'further', 'weight': np.float32(0.00245028)},
 {'word': 'algorithms', 'weight': np.float32(0.002443442)},
 {'word': 'including', 'weight': np.float32(0.0024395096)},
 {'word': 'for', 'weight': np.float32(0.002422047)},
 {'word': 'to', 'weight': np.float32(0.0024176657)},
 {'word': 'work', 'weight': np.float32(0.0023948597)},
 {'word': 'using', 'weight': np.float32(0.002385697)},
 {'word': 'we', 'weight': np.float32(0.0023268245)},
 {'word': 'were', 'weight': np.float32(0.0023222636)},
 {'word': '//', 'weight': np.float32(0.0023085217)},
 {'word': 'datasets', 'weight': np.float32(0.002302439)},
 {'word': 'by', 'weight': np.float32(0.002299812)},
 {'word': 'have', 'weight': np.float32(0.0022869303)},
 {'word': 'crucial', 'weight': np.float32(0.002284828)},
 {'word': 'and', 'weight': np.float32(0.0022716094)},
 {'word': 'improvements', 'weight': np.float32(0.0022660573)},
 {'word': 'approaches', 'weight': np.float32(0.0022625262)},
 {'word': '1', 'weight': np.float32(0.0022619213)},
 {'word': 'enabling', 'weight': np.float32(0.002261162)},
 {'word': 'and', 'weight': np.float32(0.0022496923)},
 {'word': 'networks', 'weight': np.float32(0.0022369754)},
 {'word': 'section:', 'weight': np.float32(0.0022323062)},
 {'word': 'reformulated', 'weight': np.float32(0.0022301082)},
 {'word': 'approaches', 'weight': np.float32(0.0022270824)},
 {'word': 'aggregation', 'weight': np.float32(0.0022236684)},
 {'word': 'this', 'weight': np.float32(0.0022221862)},
 {'word': 'followed', 'weight': np.float32(0.002219202)},
 {'word': 'research', 'weight': np.float32(0.0022175685)},
 {'word': 'annotations', 'weight': np.float32(0.0022060808)},
 {'word': 'using', 'weight': np.float32(0.0021972165)},
 {'word': 'will', 'weight': np.float32(0.0021956167)},
 {'word': 'imagery', 'weight': np.float32(0.0021955133)},
 {'word': 'success', 'weight': np.float32(0.0021803232)},
 {'word': 'approach', 'weight': np.float32(0.0021746128)},
 {'word': 'cityscapes', 'weight': np.float32(0.002155279)},
 {'word': 'improve', 'weight': np.float32(0.0021489174)},
 {'word': '/', 'weight': np.float32(0.0021328982)},
 {'word': 'architecture', 'weight': np.float32(0.0021213377)},
 {'word': 'githubcom', 'weight': np.float32(0.002102536)},
 {'word': 'the', 'weight': np.float32(0.0021012886)},
 {'word': 'cnn', 'weight': np.float32(0.0020930015)},
 {'word': 'for', 'weight': np.float32(0.002083044)},
 {'word': 'our', 'weight': np.float32(0.002078545)},
 {'word': 'long', 'weight': np.float32(0.0020724086)},
 {'word': 'autonomous', 'weight': np.float32(0.00206999)},
 {'word': 'as', 'weight': np.float32(0.002059422)},
 {'word': 'followed', 'weight': np.float32(0.002050034)},
 {'word': 'over', 'weight': np.float32(0.00203886)},
 {'word': 'semantic', 'weight': np.float32(0.002034304)},
 {'word': 'pixel', 'weight': np.float32(0.0020287503)},
 {'word': 'from', 'weight': np.float32(0.0020182382)},
 {'word': 'architectures', 'weight': np.float32(0.0020094835)},
 {'word': '/', 'weight': np.float32(0.0020070109)},
 {'word': 'network', 'weight': np.float32(0.0020058032)},
 {'word': 'which', 'weight': np.float32(0.0019957756)},
 {'word': 'semantic', 'weight': np.float32(0.0019932906)},
 {'word': 'a', 'weight': np.float32(0.0019886235)},
 {'word': 'image', 'weight': np.float32(0.0019860913)},
 {'word': 'on', 'weight': np.float32(0.0019799187)},
 {'word': 'focus', 'weight': np.float32(0.001978835)},
 {'word': 'given', 'weight': np.float32(0.0019556037)},
 {'word': 'their', 'weight': np.float32(0.0019550854)},
 {'word': 'successful', 'weight': np.float32(0.001952219)},
 {'word': 'at', 'weight': np.float32(0.0019510459)},
 {'word': 'learning', 'weight': np.float32(0.0019487985)},
 {'word': 'classifying', 'weight': np.float32(0.0019448819)},
 {'word': 'virtual', 'weight': np.float32(0.0019432703)},
 {'word': 'approaches', 'weight': np.float32(0.0019363195)},
 {'word': 'such', 'weight': np.float32(0.0019351019)},
 {'word': 'predictions', 'weight': np.float32(0.0019271597)},
 {'word': 'the', 'weight': np.float32(0.001925978)},
 {'word': 'fully', 'weight': np.float32(0.0019225173)},
 {'word': 'this', 'weight': np.float32(0.0019218962)},
 {'word': 'is', 'weight': np.float32(0.0019205874)},
 {'word': 'models', 'weight': np.float32(0.0019194022)},
 {'word': 'in', 'weight': np.float32(0.0019132466)},
 {'word': 'multiple', 'weight': np.float32(0.0019005021)}]

In [52]:
def filter_words_by_text(words_dicts: list, text: str) -> list:
    """
    Оставляет в массиве словарей только те слова, которые присутствуют в тексте.
    """
    text_words = set(text.lower().split())
    return [word_dict for word_dict in words_dicts if word_dict['word'].lower() in text_words]

In [53]:
words = filter_words_by_text(result1_m, valid_chunks[0])
words

[{'word': 'research', 'weight': np.float32(0.0028580574)},
 {'word': 'early', 'weight': np.float32(0.0028180352)},
 {'word': 'dataset', 'weight': np.float32(0.0026851872)},
 {'word': 'rather', 'weight': np.float32(0.002575087)},
 {'word': 'neural', 'weight': np.float32(0.002452692)},
 {'word': 'introduction', 'weight': np.float32(0.0024521477)},
 {'word': 'crucial', 'weight': np.float32(0.002284828)},
 {'word': 'aggregation', 'weight': np.float32(0.0022236684)},
 {'word': 'research', 'weight': np.float32(0.0022175685)},
 {'word': 'will', 'weight': np.float32(0.0021956167)},
 {'word': 'imagery', 'weight': np.float32(0.0021955133)},
 {'word': 'success', 'weight': np.float32(0.0021803232)},
 {'word': 'cnn', 'weight': np.float32(0.0020930015)},
 {'word': 'long', 'weight': np.float32(0.0020724086)},
 {'word': 'autonomous', 'weight': np.float32(0.00206999)},
 {'word': 'over', 'weight': np.float32(0.00203886)},
 {'word': 'which', 'weight': np.float32(0.0019957756)},
 {'word': 'focus', 'weight': np.float32(0.001978835)},
 {'word': 'their', 'weight': np.float32(0.0019550854)},
 {'word': 'virtual', 'weight': np.float32(0.0019432703)},
 {'word': 'multiple', 'weight': np.float32(0.0019005021)}]

In [54]:
result2_m = keywords_top_attention_clean(result2['tokens'], 
        result2['attention_weights'], top_k=100)

result2_m

[{'word': 'modeling', 'weight': np.float32(0.003719972)},
 {'word': 'task', 'weight': np.float32(0.0036683218)},
 {'word': 'it', 'weight': np.float32(0.0036394533)},
 {'word': 'the', 'weight': np.float32(0.0034667244)},
 {'word': 'we', 'weight': np.float32(0.00337801)},
 {'word': 'the', 'weight': np.float32(0.003310318)},
 {'word': 'current', 'weight': np.float32(0.0031794677)},
 {'word': 'approaches', 'weight': np.float32(0.0031493956)},
 {'word': 'employ', 'weight': np.float32(0.0030397072)},
 {'word': 'assigning', 'weight': np.float32(0.0030230973)},
 {'word': 'classification', 'weight': np.float32(0.0029087598)},
 {'word': 'the', 'weight': np.float32(0.0028830364)},
 {'word': 'example', 'weight': np.float32(0.002854088)},
 {'word': 'discard', 'weight': np.float32(0.002842721)},
 {'word': 'all', 'weight': np.float32(0.0028261032)},
 {'word': 'work', 'weight': np.float32(0.002824873)},
 {'word': 'is', 'weight': np.float32(0.0027812968)},
 {'word': 'that', 'weight': np.float32(0.0027597568)},
 {'word': 'training', 'weight': np.float32(0.0027447492)},
 {'word': 'starting', 'weight': np.float32(0.002693846)},
 {'word': 'require', 'weight': np.float32(0.0026839064)},
 {'word': 'the', 'weight': np.float32(0.0026715458)},
 {'word': 'our', 'weight': np.float32(0.002650516)},
 {'word': 'operations', 'weight': np.float32(0.0026250305)},
 {'word': 'achieving', 'weight': np.float32(0.002588118)},
 {'word': 'automotive', 'weight': np.float32(0.0025584828)},
 {'word': 'using', 'weight': np.float32(0.0025576688)},
 {'word': 'papers', 'weight': np.float32(0.0025516045)},
 {'word': 'or', 'weight': np.float32(0.0025317275)},
 {'word': 'network', 'weight': np.float32(0.0025115798)},
 {'word': 'architectures', 'weight': np.float32(0.0025084075)},
 {'word': 'of', 'weight': np.float32(0.0025036833)},
 {'word': 'task', 'weight': np.float32(0.0025007876)},
 {'word': 'where', 'weight': np.float32(0.002497729)},
 {'word': 'to', 'weight': np.float32(0.0024741418)},
 {'word': 'semantic', 'weight': np.float32(0.0024689632)},
 {'word': 'many', 'weight': np.float32(0.0024618274)},
 {'word': 'applications', 'weight': np.float32(0.0024365503)},
 {'word': 'and', 'weight': np.float32(0.0024338628)},
 {'word': 'detection', 'weight': np.float32(0.0024286306)},
 {'word': 'data', 'weight': np.float32(0.0023897432)},
 {'word': 'pixels', 'weight': np.float32(0.002388696)},
 {'word': 'can', 'weight': np.float32(0.002377504)},
 {'word': 'auxiliary', 'weight': np.float32(0.0023717775)},
 {'word': 'reduces', 'weight': np.float32(0.0023702073)},
 {'word': 'segmentation', 'weight': np.float32(0.0023657253)},
 {'word': 'task', 'weight': np.float32(0.002350516)},
 {'word': 'or', 'weight': np.float32(0.0023276596)},
 {'word': 'some', 'weight': np.float32(0.0023256189)},
 {'word': 'takes', 'weight': np.float32(0.0023225148)},
 {'word': 'for', 'weight': np.float32(0.002300015)},
 {'word': 'are', 'weight': np.float32(0.0022877338)},
 {'word': 'network', 'weight': np.float32(0.0022726888)},
 {'word': 'used', 'weight': np.float32(0.0022661726)},
 {'word': 'using', 'weight': np.float32(0.0022616168)},
 {'word': 'improve', 'weight': np.float32(0.00225945)},
 {'word': 'semantic', 'weight': np.float32(0.0022567553)},
 {'word': 'coupled', 'weight': np.float32(0.0022433184)},
 {'word': 'this', 'weight': np.float32(0.002221039)},
 {'word': 'weights', 'weight': np.float32(0.002218139)},
 {'word': 'such', 'weight': np.float32(0.0022065556)},
 {'word': 'pursue', 'weight': np.float32(0.002204703)},
 {'word': 'classification', 'weight': np.float32(0.0022037975)},
 {'word': 'has', 'weight': np.float32(0.0021773744)},
 {'word': 'class', 'weight': np.float32(0.002174602)},
 {'word': 'stays', 'weight': np.float32(0.0021679413)},
 {'word': 'in', 'weight': np.float32(0.00214011)},
 {'word': '][', 'weight': np.float32(0.0021184813)},
 {'word': 'reference],', 'weight': np.float32(0.0021173486)},
 {'word': 'network', 'weight': np.float32(0.0021094864)},
 {'word': '][', 'weight': np.float32(0.0021073478)},
 {'word': 'many', 'weight': np.float32(0.0020964416)},
 {'word': 'image', 'weight': np.float32(0.0020895097)},
 {'word': 'usually', 'weight': np.float32(0.0020834235)},
 {'word': '][', 'weight': np.float32(0.0020803376)},
 {'word': 'image', 'weight': np.float32(0.0020789295)},
 {'word': 'application', 'weight': np.float32(0.0020525798)},
 {'word': 'network', 'weight': np.float32(0.002049728)},
 {'word': 'semantic', 'weight': np.float32(0.0020469143)},
 {'word': 'therefore', 'weight': np.float32(0.0020386574)},
 {'word': 'nets', 'weight': np.float32(0.0020314546)},
 {'word': '][', 'weight': np.float32(0.002006839)},
 {'word': 'target', 'weight': np.float32(0.00200168)},
 {'word': '][', 'weight': np.float32(0.0019979437)},
 {'word': 'geometry', 'weight': np.float32(0.001991266)},
 {'word': 'boundaries', 'weight': np.float32(0.0019832544)},
 {'word': 'variants', 'weight': np.float32(0.001959779)},
 {'word': 'by', 'weight': np.float32(0.0019494471)},
 {'word': 'network', 'weight': np.float32(0.001947615)},
 {'word': 'to', 'weight': np.float32(0.0019463887)},
 {'word': '][', 'weight': np.float32(0.0019456911)},
 {'word': 'segmentation', 'weight': np.float32(0.0019368466)},
 {'word': '][', 'weight': np.float32(0.001936137)},
 {'word': 'unlikely', 'weight': np.float32(0.0019270518)},
 {'word': 'reference],', 'weight': np.float32(0.0019263604)},
 {'word': 'and', 'weight': np.float32(0.0019196671)},
 {'word': 'often', 'weight': np.float32(0.0019116271)},
 {'word': 'for', 'weight': np.float32(0.0019110851)},
 {'word': 'architecture', 'weight': np.float32(0.001908165)},
 {'word': 'from', 'weight': np.float32(0.0019069443)}]

In [55]:
words = filter_words_by_text(result2_m, valid_chunks[1])
words

[{'word': 'task', 'weight': np.float32(0.0036683218)},
 {'word': 'it', 'weight': np.float32(0.0036394533)},
 {'word': 'current', 'weight': np.float32(0.0031794677)},
 {'word': 'employ', 'weight': np.float32(0.0030397072)},
 {'word': 'example', 'weight': np.float32(0.002854088)},
 {'word': 'discard', 'weight': np.float32(0.002842721)},
 {'word': 'all', 'weight': np.float32(0.0028261032)},
 {'word': 'that', 'weight': np.float32(0.0027597568)},
 {'word': 'require', 'weight': np.float32(0.0026839064)},
 {'word': 'automotive', 'weight': np.float32(0.0025584828)},
 {'word': 'or', 'weight': np.float32(0.0025317275)},
 {'word': 'task', 'weight': np.float32(0.0025007876)},
 {'word': 'where', 'weight': np.float32(0.002497729)},
 {'word': 'many', 'weight': np.float32(0.0024618274)},
 {'word': 'detection', 'weight': np.float32(0.0024286306)},
 {'word': 'can', 'weight': np.float32(0.002377504)},
 {'word': 'auxiliary', 'weight': np.float32(0.0023717775)},
 {'word': 'task', 'weight': np.float32(0.002350516)},
 {'word': 'or', 'weight': np.float32(0.0023276596)},
 {'word': 'some', 'weight': np.float32(0.0023256189)},
 {'word': 'pursue', 'weight': np.float32(0.002204703)},
 {'word': 'class', 'weight': np.float32(0.002174602)},
 {'word': 'many', 'weight': np.float32(0.0020964416)},
 {'word': 'usually', 'weight': np.float32(0.0020834235)},
 {'word': 'application', 'weight': np.float32(0.0020525798)},
 {'word': 'therefore', 'weight': np.float32(0.0020386574)},
 {'word': 'target', 'weight': np.float32(0.00200168)},
 {'word': 'geometry', 'weight': np.float32(0.001991266)},
 {'word': 'unlikely', 'weight': np.float32(0.0019270518)},
 {'word': 'often', 'weight': np.float32(0.0019116271)}]

In [58]:
def postprocess_words_array(words_dicts: list) -> list:
    """
    Постобработка массива слов: удаление дубликатов (оставляем слово с наивысшим весом)
    и удаление стоп-слов английского языка.
    """
    # Загружаем стоп-слова
    stop_words = {
        'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by',
        'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'do', 'does',
        'did', 'will', 'would', 'could', 'should', 'may', 'might', 'must', 'can', 'i', 'you',
        'he', 'she', 'it', 'we', 'they', 'me', 'him', 'her', 'us', 'them', 'this', 'that',
        'these', 'those', 'my', 'your', 'his', 'her', 'its', 'our', 'their', 'as', 'from'
    }
    
    # Словарь для хранения максимального веса для каждого слова
    word_max_weight = {}
    
    # Находим максимальный вес для каждого слова
    for word_dict in words_dicts:
        word = word_dict['word'].lower()
        weight = word_dict['weight']
        
        if word not in word_max_weight or weight > word_max_weight[word]:
            word_max_weight[word] = weight
    
    # Создаем новый массив без дубликатов и стоп-слов
    result = []
    for word, max_weight in word_max_weight.items():
        if word not in stop_words and len(word) > 1:  # исключаем стоп-слова и одиночные символы
            result.append({"word": word, "weight": max_weight})
    
    # Сортируем по весу в убывающем порядке
    result.sort(key=lambda x: x['weight'], reverse=True)
    
    return result

In [59]:
processed = postprocess_words_array(words)
processed

[{'word': 'task', 'weight': np.float32(0.0036683218)},
 {'word': 'current', 'weight': np.float32(0.0031794677)},
 {'word': 'employ', 'weight': np.float32(0.0030397072)},
 {'word': 'example', 'weight': np.float32(0.002854088)},
 {'word': 'discard', 'weight': np.float32(0.002842721)},
 {'word': 'all', 'weight': np.float32(0.0028261032)},
 {'word': 'require', 'weight': np.float32(0.0026839064)},
 {'word': 'automotive', 'weight': np.float32(0.0025584828)},
 {'word': 'where', 'weight': np.float32(0.002497729)},
 {'word': 'many', 'weight': np.float32(0.0024618274)},
 {'word': 'detection', 'weight': np.float32(0.0024286306)},
 {'word': 'auxiliary', 'weight': np.float32(0.0023717775)},
 {'word': 'some', 'weight': np.float32(0.0023256189)},
 {'word': 'pursue', 'weight': np.float32(0.002204703)},
 {'word': 'class', 'weight': np.float32(0.002174602)},
 {'word': 'usually', 'weight': np.float32(0.0020834235)},
 {'word': 'application', 'weight': np.float32(0.0020525798)},
 {'word': 'therefore', 'weight': np.float32(0.0020386574)},
 {'word': 'target', 'weight': np.float32(0.00200168)},
 {'word': 'geometry', 'weight': np.float32(0.001991266)},
 {'word': 'unlikely', 'weight': np.float32(0.0019270518)},
 {'word': 'often', 'weight': np.float32(0.0019116271)}]

In [ ]:
result = get_qa_attention_weights(question = questions[0], context = valid_chunks[0])
visualize_top_attention_clean(result['tokens'], result['attention_weights'], top_k=100)

In [ ]:
result = get_qa_attention_weights(question = questions[0], context = valid_chunks[1])
visualize_top_attention_clean(result['tokens'], result['attention_weights'], top_k=100)

In [ ]:
filtered_keywords = filter_keywords(result=result, 
                    them_asp=them_aspect,
                    similarity_threshold=0.1,
                    dissimilarity_threshold=0.55)
filtered_keywords

In [ ]:
words_with_score = [{'word': word, 'score': float(score)} for word, score in filtered_keywords]
words_with_score

In [ ]:
filtered_keywords = [key[0] for key in filtered_keywords]
filtered_keywords

In [ ]:
len(text_chunks)

In [ ]:
from typing import List, Dict
import re
from dataclasses import dataclass
import numpy as np



def score_chunks_by_keywords(
    chunks: List[TextChunk], 
    keywords: List[dict],
    case_sensitive: bool = False,
    use_tfidf_weights: bool = True,
    min_matches: int = 1
) -> List[ScoredChunk]:
    """
    Оценивает фрагменты на основе количества и важности ключевых слов.
    Чем больше ключевых слов и чем они важнее, тем выше оценка фрагмента.
    
    Параметры:
        chunks: Список объектов TextChunk для оценки
        keywords: Список словарей формата [{"word": str, "lemma": str, "stem": str, "score": float}, ...]
        case_sensitive: Учитывать регистр при поиске
        use_tfidf_weights: Использовать веса ключевых слов из поля 'score'
        min_matches: Минимальное количество совпадений для включения фрагмента в результат
    
    Возвращает:
        Список объектов ScoredChunk с оценками и информацией о совпадениях
    """
    if not keywords or not chunks:
        return []
    
    # Подготавливаем ключевые слова и их веса
    keyword_weights = {}
    search_terms = set()
    term_to_keyword = {}
    
    for keyword in keywords:
        word = keyword['word']
        weight = keyword.get('score', 1.0) if use_tfidf_weights else 1.0
        
        keyword_weights[word] = weight
        
        # Добавляем лемму и стем для поиска
        lemma = keyword.get('lemma', word)
        stem = keyword.get('stem', word)
        
        search_terms.add(lemma)
        search_terms.add(stem)
        
        term_to_keyword[lemma.lower()] = word
        term_to_keyword[stem.lower()] = word
    
    # Создаем regex-паттерн для поиска
    pattern = re.compile(
        r'\b(?:{})\b'.format('|'.join(map(re.escape, search_terms))),
        flags=0 if case_sensitive else re.IGNORECASE
    )
    
    scored_chunks = []
    
    for chunk in chunks:
        # Находим все совпадения терминов в тексте
        text_to_search = chunk.text if case_sensitive else chunk.text.lower()
        found_terms = pattern.findall(text_to_search)
        
        # Собираем уникальные найденные ключевые слова и их веса
        matched_keywords = set()
        total_score = 0.0
        
        for term in found_terms:
            normalized_term = term if case_sensitive else term.lower()
            if normalized_term in term_to_keyword:
                keyword_word = term_to_keyword[normalized_term]
                if keyword_word not in matched_keywords:
                    matched_keywords.add(keyword_word)
                    total_score += keyword_weights.get(keyword_word, 1.0)
        
        # Применяем дополнительные факторы для улучшения оценки
        if matched_keywords:
            # Нормализуем по количеству слов в фрагменте (чтобы избежать bias к длинным текстам)
            normalization_factor = 1.0 + (len(matched_keywords) / max(1, chunk.word_token_count / 10))
            
            # Учитываем плотность ключевых слов
            density_bonus = min(2.0, 1.0 + (len(matched_keywords) / max(1, len(chunk.text.split()) / 20)))
            
            final_score = total_score * normalization_factor * density_bonus
            
            if len(matched_keywords) >= min_matches:
                scored_chunks.append(ScoredChunk(
                    chunk=chunk,
                    score=final_score,
                    matched_keywords=list(matched_keywords),
                    keyword_scores={kw: keyword_weights.get(kw, 1.0) for kw in matched_keywords}
                ))
    
    # Сортируем по убыванию оценки
    scored_chunks.sort(key=lambda x: x.score, reverse=True)
    
    return scored_chunks

# Альтернативная версия с более сложной системой оценки
def score_chunks_advanced(
    chunks: List[TextChunk], 
    keywords: List[dict],
    case_sensitive: bool = False,
    min_matches: int = 1,
    position_weight: float = 0.3,
    frequency_weight: float = 0.7
) -> List[ScoredChunk]:
    """
    Расширенная версия оценки фрагментов с учетом позиции и частоты ключевых слов.
    """
    if not keywords or not chunks:
        return []
    
    # Подготавливаем ключевые слова
    keyword_weights = {}
    search_terms = set()
    term_to_keyword = {}
    
    for keyword in keywords:
        word = keyword['word']
        weight = keyword.get('score', 1.0)
        
        keyword_weights[word] = weight
        
        lemma = keyword.get('lemma', word)
        stem = keyword.get('stem', word)
        
        search_terms.add(lemma)
        search_terms.add(stem)
        
        term_to_keyword[lemma.lower()] = word
        term_to_keyword[stem.lower()] = word
    
    pattern = re.compile(
        r'\b(?:{})\b'.format('|'.join(map(re.escape, search_terms))),
        flags=0 if case_sensitive else re.IGNORECASE
    )
    
    scored_chunks = []
    
    for chunk in chunks:
        text_to_search = chunk.text if case_sensitive else chunk.text.lower()
        found_matches = list(pattern.finditer(text_to_search))
        
        if not found_matches:
            continue
        
        # Анализируем совпадения
        matched_keywords = set()
        position_scores = []
        keyword_frequencies = {}
        
        for match in found_matches:
            term = match.group()
            normalized_term = term if case_sensitive else term.lower()
            
            if normalized_term in term_to_keyword:
                keyword_word = term_to_keyword[normalized_term]
                matched_keywords.add(keyword_word)
                
                # Оценка позиции (слова в начале текста более важны)
                position = match.start() / max(1, len(text_to_search))
                position_score = 1.0 - position  # чем раньше, тем выше оценка
                position_scores.append(position_score)
                
                # Подсчет частоты
                keyword_frequencies[keyword_word] = keyword_frequencies.get(keyword_word, 0) + 1
        
        if len(matched_keywords) >= min_matches:
            # Вычисляем общую оценку
            base_score = sum(keyword_weights.get(kw, 1.0) for kw in matched_keywords)
            
            # Учитываем позицию (средняя оценка позиций)
            avg_position_score = np.mean(position_scores) if position_scores else 0.5
            position_contribution = 1.0 + position_weight * avg_position_score
            
            # Учитываем частоту (логарифмическая шкала для избежания перекоса)
            freq_contribution = 1.0 + frequency_weight * np.log1p(sum(keyword_frequencies.values()))
            
            # Учитываем уникальность (количество разных ключевых слов)
            uniqueness_bonus = 1.0 + (len(matched_keywords) / len(keywords)) * 0.5
            
            final_score = base_score * position_contribution * freq_contribution * uniqueness_bonus
            
            scored_chunks.append(ScoredChunk(
                chunk=chunk,
                score=final_score,
                matched_keywords=list(matched_keywords),
                keyword_scores=keyword_frequencies
            ))
    
    scored_chunks.sort(key=lambda x: x.score, reverse=True)
    return scored_chunks

# Функция для комбинированной фильтрации и оценки
def filter_and_score_chunks(
    chunks: List[TextChunk], 
    keywords: List[dict],
    min_keywords: int = 1,
    case_sensitive: bool = False,
    score_threshold: float = 0.0
) -> List[ScoredChunk]:
    """
    Комбинированная функция: сначала фильтрует, затем оценивает фрагменты.
    """
    # Сначала фильтруем по минимальному количеству ключевых слов
    filtered_chunks = filter_chunks_by_keywords_lemm_stemm(
        chunks, keywords, min_keywords, case_sensitive
    )
    
    # Затем оцениваем отфильтрованные фрагменты
    scored_chunks = score_chunks_by_keywords(
        filtered_chunks, keywords, case_sensitive
    )
    
    # Применяем порог оценки
    if score_threshold > 0:
        scored_chunks = [sc for sc in scored_chunks if sc.score >= score_threshold]
    
    return scored_chunks

In [ ]:
lemm_stemm_keywords = get_lemm_stemm_words(filtered_keywords)
lemm_stemm_keywords

In [ ]:
lemma_dict = {item['word']: item for item in lemm_stemm_keywords}
result_keys = [{**item, **lemma_dict[item['word']]} for item in words_with_score if item['word'] in lemma_dict]
result_keys

In [ ]:
 # Оценка фрагментов
scored_chunks = score_chunks_by_keywords(text_chunks, 
                                        get_lemm_stemm_words(filtered_keywords), 
                                        min_matches=0)
    
print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(scored_chunks[:10]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

In [ ]:
simp_ans_finder = SimpleAnswerFinder()


question_with_answers = simp_ans_finder.find_answers(
        question = convert_into_question_class(questions)[0],
        chunks = [s_chunk.chunk for s_chunk in scored_chunks[:5]]
        )


print("\n---\n---> Founded answers:")
for ans in question_with_answers.answers:
    print(ans.text)
    print(ans.confidence)
    print(ans.chunk.text)
    print("----------------------\n")

In [ ]:
finder = ScoredAnswerFinder()

result1 = finder.find_answers(
    question = convert_into_question_class(questions)[0], 
    scored_chunks = scored_chunks
    )

# Ответы будут отсортированы по score фрагментов
for answer in result1.answers:
    print(f"Ответ: {answer.text}")
    print(f"Confidence QA: {answer.confidence}")
    print(f"Score фрагмента: {answer.chunk_score:.3f}")
    print(f"Ключевые слова: {answer.matched_keywords}")
    print(f"Chunk: {answer.chunk.text}")
    print("\n")

In [ ]:
 # Оценка фрагментов
extra_scored_chunks = score_chunks_by_keywords(text_chunks, result_keys, min_matches=0)
    
print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(extra_scored_chunks[:10]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

In [ ]:
finder = ScoredAnswerFinder()

result2 = finder.find_answers(
    question = convert_into_question_class(questions)[0], 
    scored_chunks = extra_scored_chunks
    )

# Ответы будут отсортированы по score фрагментов
for answer in result2.answers:
    print(f"Ответ: {answer.text}")
    print(f"Confidence QA: {answer.confidence}")
    print(f"Score фрагмента: {answer.chunk_score:.3f}")
    print(f"Ключевые слова: {answer.matched_keywords}")
    print(f"Chunk: {answer.chunk.text}")
    print("\n")

In [ ]:
# Оценка фрагментов
extra_sup_scored_chunks = score_chunks_advanced(text_chunks, result_keys, min_matches=0)
    
print("Топ-5 фрагментов по оценке:")
for i, scored_chunk in enumerate(extra_sup_scored_chunks[:10]):
    print(f"{i+1}. Оценка: {scored_chunk.score:.2f}")
    print(f"   Совпадения: {', '.join(scored_chunk.matched_keywords)}")
    print(f"   Текст: {scored_chunk.chunk.text[:100]}...")
    print()

In [ ]:
finder = ScoredAnswerFinder()

result3 = finder.find_answers(
    question = convert_into_question_class(questions)[0], 
    scored_chunks = extra_sup_scored_chunks
    )

# Ответы будут отсортированы по score фрагментов
for answer in result3.answers:
    print(f"Ответ: {answer.text}")
    print(f"Confidence QA: {answer.confidence}")
    print(f"Score фрагмента: {answer.chunk_score:.3f}")
    print(f"Ключевые слова: {answer.matched_keywords}")
    print(f"Chunk: {answer.chunk.text}")
    print("\n")

In [ ]:
from typing import List, Dict, Tuple, Union
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.cluster import DBSCAN, OPTICS
from sklearn.metrics import pairwise_distances
from collections import defaultdict

class AnswerGrouper:
    def __init__(self):
        self.model = SentenceTokenizerSingleton()
    
    def get_embeddings(self, answers):
        """Получает эмбеддинги для всех ответов"""
        texts = [answer.text for answer in answers]
        return self.model.tokenizer.encode(texts)
    
    def adaptive_clustering(self, embeddings, answers, min_samples=2, eps=0.5):
        """
        Адаптивная кластеризация ответов с использованием DBSCAN
        Возвращает словарь кластеров
        """
        # Вычисляем попарные расстояния
        distances = pairwise_distances(embeddings, metric='cosine')
        
        # Используем DBSCAN для кластеризации
        clustering = DBSCAN(eps=eps, min_samples=min_samples, metric='precomputed').fit(distances)
        labels = clustering.labels_
        
        # Группируем ответы по кластерам
        clusters = defaultdict(list)
        for i, label in enumerate(labels):
            if label != -1:  # Игнорируем выбросы
                clusters[label].append((answers[i], embeddings[i]))
        
        return dict(clusters)
    
    def hierarchical_grouping(self, embeddings, answers, threshold_percentile=75):
        """
        Иерархическая группировка с динамическим определением порога
        Возвращает список групп
        """
        # Вычисляем косинусные расстояния
        distances = pairwise_distances(embeddings, metric='cosine')
        
        # Определяем порог на основе процентиля расстояний
        flat_distances = distances[np.triu_indices_from(distances, k=1)]
        threshold = np.percentile(flat_distances, threshold_percentile)
        
        # Создаем группы на основе порога
        groups = []
        used_indices = set()
        
        for i in range(len(embeddings)):
            if i in used_indices:
                continue
                
            # Находим все похожие ответы
            group_indices = np.where(distances[i] <= threshold)[0]
            group_answers = [answers[j] for j in group_indices]
            group_embeddings = embeddings[group_indices]
            
            groups.append({
                'answers': group_answers,
                'embeddings': group_embeddings,
                'size': len(group_answers)
            })
            used_indices.update(group_indices)
        
        return groups
    
    def cluster_with_quality_assessment(self, embeddings, answers, min_cluster_size=2):
        """
        Кластеризация с оценкой качества кластеров
        Возвращает словарь кластеров и словарь качеств
        """
        # Используем OPTICS для кластеризации с автоматическим определением параметров
        clustering = OPTICS(min_samples=min_cluster_size, metric='cosine').fit(embeddings)
        labels = clustering.labels_
        
        # Оцениваем качество каждого кластера
        clusters = defaultdict(list)
        cluster_qualities = {}
        
        for i, label in enumerate(labels):
            if label != -1:
                clusters[label].append((answers[i], embeddings[i]))
        
        # Вычисляем качество кластера на основе когерентности
        for label, cluster_data in clusters.items():
            answers_in_cluster, embeddings_in_cluster = zip(*cluster_data)
            
            # Вычисляем когерентность кластера (среднее попарное сходство)
            if len(embeddings_in_cluster) > 1:
                cluster_distances = pairwise_distances(embeddings_in_cluster, metric='cosine')
                coherence = 1 - np.mean(cluster_distances)
                cluster_qualities[label] = coherence
            else:
                cluster_qualities[label] = 0
        
        return dict(clusters), cluster_qualities
    
    def group_answers(self, answers, method='adaptive', **kwargs):
        """
        Основная функция для группировки ответов и вычисления средних оценок
        """
        # Получаем эмбеддинги для ответов
        embeddings = self.get_embeddings(answers)
        
        if method == 'adaptive':
            clusters_dict = self.adaptive_clustering(embeddings, answers, **kwargs)
            clusters = self._process_cluster_dict(clusters_dict)
        elif method == 'hierarchical':
            clusters = self.hierarchical_grouping(embeddings, answers, **kwargs)
        elif method == 'quality':
            clusters_dict, qualities = self.cluster_with_quality_assessment(embeddings, answers, **kwargs)
            clusters = self._process_cluster_dict_with_quality(clusters_dict, qualities)
        else:
            raise ValueError("Неизвестный метод группировки")
        
        # Вычисляем средние оценки для каждого кластера
        cluster_results = []
        for i, cluster in enumerate(clusters):
            answers_in_cluster = cluster['answers']
            embeddings_in_cluster = cluster.get('embeddings', [])
            
            # Вычисляем средние оценки
            avg_confidence = np.mean([a.confidence for a in answers_in_cluster])
            avg_chunk_score = np.mean([a.chunk_score for a in answers_in_cluster])
            combined_score = avg_confidence * avg_chunk_score
            
            # Вычисляем когерентность кластера
            if len(embeddings_in_cluster) > 1:
                cluster_distances = pairwise_distances(embeddings_in_cluster, metric='cosine')
                coherence = 1 - np.mean(cluster_distances)
            else:
                coherence = cluster.get('coherence', 1.0)
            
            cluster_results.append({
                'cluster_id': i,
                'answers': answers_in_cluster,
                'avg_confidence': avg_confidence,
                'avg_chunk_score': avg_chunk_score,
                'combined_score': combined_score,
                'coherence': coherence,
                'size': len(answers_in_cluster)
            })
        
        # Сортируем кластеры по комбинированной оценке
        cluster_results.sort(key=lambda x: x['combined_score'] * x['coherence'], reverse=True)
        
        return cluster_results
    
    def _process_cluster_dict(self, clusters_dict):
        """Преобразует словарь кластеров в унифицированный формат"""
        clusters = []
        for cluster_id, cluster_data in clusters_dict.items():
            answers_in_cluster, embeddings_in_cluster = zip(*cluster_data)
            clusters.append({
                'answers': list(answers_in_cluster),
                'embeddings': list(embeddings_in_cluster),
                'size': len(answers_in_cluster)
            })
        return clusters
    
    def _process_cluster_dict_with_quality(self, clusters_dict, qualities):
        """Преобразует словарь кластеров с учетом качества"""
        clusters = []
        for cluster_id, cluster_data in clusters_dict.items():
            answers_in_cluster, embeddings_in_cluster = zip(*cluster_data)
            clusters.append({
                'answers': list(answers_in_cluster),
                'embeddings': list(embeddings_in_cluster),
                'coherence': qualities.get(cluster_id, 0),
                'size': len(answers_in_cluster)
            })
        return clusters
    
    def select_final_answer(self, cluster_results, strategy='best_cluster'):
        """
        Выбор итогового ответа на основе группировки
        """
        if not cluster_results:
            return None
        
        if strategy == 'best_cluster':
            # Выбираем лучший ответ из лучшего кластера
            best_cluster = cluster_results[0]
            best_answer = max(best_cluster['answers'], 
                             key=lambda a: a.confidence * a.chunk_score)
            return best_answer
        
        elif strategy == 'weighted_combination':
            # Взвешенная комбинация ответов из топовых кластеры
            top_answers = []
            weights = []
            
            for cluster in cluster_results[:3]:  # Рассматриваем топ-3 кластера
                for answer in cluster['answers']:
                    weight = answer.confidence * answer.chunk_score * cluster['coherence']
                    top_answers.append(answer)
                    weights.append(weight)
            
            if not weights:
                return None
                
            # Нормализуем веса
            weights = np.array(weights) / sum(weights)
            
            # Выбираем ответ с максимальным весом
            best_idx = np.argmax(weights)
            return top_answers[best_idx]
        
        elif strategy == 'ensemble':
            # Ансамблевый подход
            answer_scores = defaultdict(float)
            
            for cluster in cluster_results:
                cluster_weight = cluster['combined_score'] * cluster['coherence']
                
                for answer in cluster['answers']:
                    answer_scores[answer.text] += cluster_weight * answer.confidence * answer.chunk_score
            
            if not answer_scores:
                return None
                
            # Выбираем ответ с наивысшей совокупной оценкой
            best_answer_text = max(answer_scores.items(), key=lambda x: x[1])[0]
            
            # Находим оригинальный объект ответа
            for cluster in cluster_results:
                for answer in cluster['answers']:
                    if answer.text == best_answer_text:
                        return answer
            
            return None

def process_answers_with_grouping(answers, grouping_method='adaptive', selection_strategy='best_cluster'):
    """
    Полный процесс обработки ответов с группировкой
    """
    # Инициализируем группер
    grouper = AnswerGrouper()
    
    # Группируем ответы
    clusters = grouper.group_answers(answers, method=grouping_method)
    
    # Выбираем итоговый ответ
    final_answer = grouper.select_final_answer(clusters, strategy=selection_strategy)
    
    # Дополнительная информация для анализа
    cluster_info = []
    for cluster in clusters:
        cluster_info.append({
            'cluster_id': cluster['cluster_id'],
            'size': cluster['size'],
            'avg_confidence': cluster['avg_confidence'],
            'avg_chunk_score': cluster['avg_chunk_score'],
            'combined_score': cluster['combined_score'],
            'coherence': cluster['coherence'],
            'answers': [answer.text for answer in cluster['answers']],
            'sample_answer': cluster['answers'][0].text[:100] + '...' if cluster['answers'] else ''
        })
    
    return final_answer, cluster_info

In [ ]:
# Обрабатываем ответы с группировкой
final_answer, cluster_info = process_answers_with_grouping(
    result2.answers, 
    grouping_method='quality',
    selection_strategy='best_cluster'
)

print("Итоговый ответ:", final_answer.text)
print("Confidence:", final_answer.confidence)
print("Chunk score:", final_answer.chunk_score)

print("\nИнформация о кластерах:")
for info in cluster_info:
    print(f"Кластер {info['cluster_id']}: размер={info['size']}, "
          f"согласованность={info['coherence']:.3f}, "
          f"средняя оценка={info['combined_score']:.7f}",
          f"ответы={info['answers']}",
          )

In [ ]:
len(result2.answers)