In [1]:
from system_check import *
CUDA_state_print_limited()

CUDA доступна: True
Количество GPU: 4

In [2]:
import torch

def get_device() -> str:
    """
    Возвращает 'cuda' если GPU доступен, иначе 'cpu'.
    """
    return "cuda:1" if torch.cuda.is_available() else "cpu"

In [3]:
device = get_device()
print(f"Используемое устройство: {device}")

Используемое устройство: cuda:1

# **Анализ токенов**

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch, gc

# Очистка памяти от предыдущих моделей
gc.collect()
torch.cuda.empty_cache()

# Загрузка ТОЛЬКО на CPU (без accelerate/device_map)
model_id = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token  # критически важно для Qwen

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,      # экономия памяти
    low_cpu_mem_usage=True,         # загрузка без переполнения ОЗУ
    trust_remote_code=False         # не требуется для Qwen2.5
).to(device)  # ← ЯВНОЕ перемещение на CPU

print("✅ Модель загружена. Память:", sum(p.numel() for p in model.parameters()) / 1e9, "B параметров")

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 2/2 [00:01<00:00,  1.60it/s]

✅ Модель загружена. Память: 3.085938688 B параметров

In [12]:
def answer_question_qwen(
    context: str, 
    question: str, 
    max_new_tokens: int = 150,
    max_context_tokens: int = 16384  # ← НАСТРОЙКА: лимит контекста
) -> str:
    """
    Получает ответ от Qwen2.5-3B с поддержкой длинного контекста.
    
    Args:
        context: Текст для анализа (до 128K токенов)
        question: Вопрос к тексту
        max_new_tokens: Макс. длина генерируемого ответа
        max_context_tokens: Лимит токенов контекста (рекомендуется 8192–16384 для ваших данных)
    """
    # === 1. Обрезка контекста ДО формирования промпта ===
    tokens = tokenizer.encode(context, add_special_tokens=False)
    if len(tokens) > max_context_tokens:
        # Сохраняем КОНЕЦ текста (часто содержит выводы/ответы)
        tokens = tokens[-max_context_tokens:]
        context = tokenizer.decode(tokens, skip_special_tokens=True)
    
    # === 2. Формирование промпта ===
    messages = [{
        "role": "user",
        "content": (
            "Ответь строго по тексту ниже. Если информации нет — напиши 'Не указано в тексте'.\n\n"
            f"Текст:\n{context}\n\n"
            f"Вопрос: {question}"
        )
    }]
    
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    # === 3. Токенизация с расширенным лимитом ===
    # Важно: max_length должен быть >= max_context_tokens + длина вопроса + системные токены
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_context_tokens + 512  # +512 на вопрос и системные токены
    ).to(device)
    
    # === 4. Генерация ===
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.3,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            use_cache=False
        )
    
    # === 5. Извлечение ответа ===
    response_tokens = outputs[0][inputs.input_ids.shape[1]:]
    response = tokenizer.decode(response_tokens, skip_special_tokens=True)
    
    return response.strip()

In [4]:
import pandas as pd
def load_dataframe_from_json(file_path: str, 
                   orient: str = 'records') -> pd.DataFrame:
    """
    Простая загрузка JSON в DataFrame без дополнительных проверок
    
    Параметры:
        file_path: путь к JSON файлу
        orient: формат JSON ('records', 'split', 'index', 'columns', 'values')
    
    Возвращает:
        Загруженный DataFrame
    
    Исключения:
        FileNotFoundError: если файл не существует
        ValueError: если JSON невалидный
    """
    try:
        return pd.read_json(file_path, orient=orient, lines=True)
    except FileNotFoundError:
        raise FileNotFoundError(f"File {file_path} not found")
    except ValueError as e:
        try: 
            return pd.read_json(file_path)
        except Exception as e:
            raise ValueError(f"Error while loading JSON: {str(e)}")

In [5]:
datasets_results_path = "../datasets_results"
res_name = "results_2.json"

df_res = load_dataframe_from_json(f"{datasets_results_path}/{res_name}")

df_res.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}"
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],"classification, segmentation and object detect...",--None--,--None--,"{'cosine_sim': 0.5885287523269653, 'lev_dist':...","{'cosine_sim': 0.5885287523269653, 'lev_dist':..."
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}"
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],determine the semantic relationship between tw...,--None--,--None--,"{'cosine_sim': 0.6914587616920471, 'lev_dist':...","{'cosine_sim': 0.6914587616920471, 'lev_dist':..."
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",search is focused on promising variations,--None--,--None--,"{'cosine_sim': 0.5607925653457642, 'lev_dist':...","{'cosine_sim': 0.5607925653457642, 'lev_dist':..."

In [15]:
import pandas as pd
import time
from tqdm import tqdm

# Создаём колонку для ответов, если её нет
if 'qwen2.5-3B_answer' not in df_res.columns:
    df_res['qwen2.5-3B_answer'] = pd.NA

# Вопрос для всех текстов
question = "Which task was solved? Give a short answer without explanation"

# Прогресс-бар
pbar = tqdm(
    total=len(df_res),
    desc="Обработка текстов Qwen2.5-3B",
    unit="текст",
    ncols=80
)

# Счётчики
success_count = 0
error_count = 0

try:
    for idx in range(len(df_res)):
        # Пропускаем уже обработанные строки
        if pd.notna(df_res.loc[idx, 'qwen2.5-3B_answer']) and df_res.loc[idx, 'qwen2.5-3B_answer'] != '':
            success_count += 1
            pbar.update(1)
            continue
        
        context = df_res.loc[idx, 'original_text']
        
        try:
            # Получаем ответ через вашу функцию
            start_time = time.time()
            answer = answer_question_qwen(
                context=context,
                question=question,
                max_new_tokens=100,        # короткий ответ как в примере
                max_context_tokens=16384   # полный контекст для ваших длинных текстов
            )
            elapsed = time.time() - start_time
            
            # Сохраняем ответ
            df_res.loc[idx, 'qwen2.5-3B_answer'] = answer
            success_count += 1
            
            # Обновляем прогресс-бар
            pbar.set_postfix({
                'успех': success_count,
                'ошибок': error_count,
                'время': f"{elapsed:.1f}с"
            })
            
        except Exception as e:
            error_count += 1
            error_msg = f"[ERROR] {str(e)[:60]}"
            df_res.loc[idx, 'qwen2.5-3B_answer'] = error_msg
            pbar.set_postfix({'ошибок': error_count})
            print(f"\n⚠️ Строка {idx}: {error_msg}")
        
        pbar.update(1)
        
        # Пауза для стабильности на CPU
        time.sleep(0.3)
        
        # Промежуточное сохранение каждые 10 строк
        if (idx + 1) % 10 == 0:
            df_res.to_csv('df_res_with_qwen_answers.csv', index=False)
            pbar.write(f" 💾 Сохранено {idx + 1}/{len(df_res)} строк")

except KeyboardInterrupt:
    pbar.close()
    print("\n\n🛑 Обработка прервана. Сохраняем результаты...")
    df_res.to_csv('df_res_with_qwen_answers.csv', index=False)
    print("✅ Промежуточные результаты сохранены в 'df_res_with_qwen_answers.csv'")
    raise

finally:
    pbar.close()

# Финальное сохранение
df_res.to_csv('df_res_with_qwen_answers.csv', index=False)

# Итоговая статистика
print("\n" + "="*70)
print("✅ ОБРАБОТКА ЗАВЕРШЕНА")
print(f"   Всего строк:    {len(df_res)}")
print(f"   Успешно:        {success_count} ({success_count/len(df_res)*100:.1f}%)")
print(f"   Ошибок:         {error_count} ({error_count/len(df_res)*100:.1f}%)")
print(f"   Результаты:     df_res_with_qwen_answers.csv")
print("="*70)

# Показать примеры ответов
print("\n🔍 Примеры ответов:")
for i in range(min(5, len(df_res))):
    print(f"\nСтрока {i}:")
    print(f"   Ответ: {df_res.loc[i, 'qwen2.5-3B_answer'][:100]}...")

Обработка текстов Qwen2.5-3B:   0%|                  | 0/306 [00:00<?, ?текст/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   0%| | 1/306 [00:03<15:34,  3.06s/текст, успех=1,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   1%| | 2/306 [00:05<13:41,  2.70s/текст, успех=2,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   1%| | 3/306 [00:08<14:34,  2.88s/текст, успех=3,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   1%| | 4/306 [00:11<14:15,  2.83s/текст, успех=4,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   2%| | 5/306 [00:15<16:37,  3.31s/текст, успех=5,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   2%| | 6/306 [00:18<16:24,  3.28s/текст, успех=6,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   2%| | 7/306 [00:23<18:54,  3.80s/текст, успех=7,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   3%| | 8/306 [00:28<20:12,  4.07s/текст, успех=8,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   3%| | 9/306 [00:49<45:56,  9.28s/текст, успех=9,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   3%| | 10/306 [00:51<34:36,  7.02s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 10/306 строк

Обработка текстов Qwen2.5-3B:   4%| | 11/306 [00:55<30:32,  6.21s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   4%| | 12/306 [00:59<26:45,  5.46s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   4%| | 13/306 [01:05<28:36,  5.86s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   5%| | 14/306 [01:07<21:36,  4.44s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   5%| | 15/306 [01:12<22:41,  4.68s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   5%| | 16/306 [01:22<30:33,  6.32s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   6%| | 17/306 [01:33<37:15,  7.73s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   6%| | 18/306 [01:37<32:23,  6.75s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   6%| | 19/306 [01:39<24:59,  5.22s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   7%| | 20/306 [01:44<23:15,  4.88s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 20/306 строк

Обработка текстов Qwen2.5-3B:   7%| | 21/306 [01:45<18:52,  3.97s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   7%| | 22/306 [01:50<20:03,  4.24s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 23/306 [01:52<17:34,  3.73s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 24/306 [01:56<17:17,  3.68s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 25/306 [02:01<18:37,  3.98s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 26/306 [02:03<15:50,  3.40s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   9%| | 27/306 [02:07<17:41,  3.81s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   9%| | 28/306 [02:12<18:13,  3.93s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   9%| | 29/306 [02:16<18:59,  4.11s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  10%| | 30/306 [02:24<23:43,  5.16s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 30/306 строк

Обработка текстов Qwen2.5-3B:  10%| | 31/306 [02:28<22:04,  4.82s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  10%| | 32/306 [02:48<43:07,  9.44s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  11%| | 33/306 [02:52<35:12,  7.74s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  11%| | 34/306 [02:54<27:14,  6.01s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  11%| | 35/306 [02:56<22:20,  4.95s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  12%| | 36/306 [02:58<17:31,  3.89s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  12%| | 37/306 [03:00<16:00,  3.57s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  12%| | 38/306 [03:05<17:16,  3.87s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  13%|▏| 39/306 [03:09<17:46,  3.99s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  13%|▏| 40/306 [03:12<15:46,  3.56s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 40/306 строк

Обработка текстов Qwen2.5-3B:  13%|▏| 41/306 [03:15<14:32,  3.29s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  14%|▏| 42/306 [03:42<46:38, 10.60s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  14%|▏| 43/306 [03:44<35:04,  8.00s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  14%|▏| 44/306 [03:46<27:11,  6.23s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  15%|▏| 45/306 [03:51<24:36,  5.66s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  15%|▏| 46/306 [03:55<23:25,  5.41s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  15%|▏| 47/306 [03:59<20:25,  4.73s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  16%|▏| 48/306 [04:03<20:31,  4.77s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  16%|▏| 49/306 [04:14<27:51,  6.50s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  16%|▏| 50/306 [04:17<22:42,  5.32s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 50/306 строк

Обработка текстов Qwen2.5-3B:  17%|▏| 51/306 [04:19<18:56,  4.46s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  17%|▏| 52/306 [04:23<18:11,  4.30s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  17%|▏| 53/306 [04:33<25:26,  6.03s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  18%|▏| 54/306 [04:35<20:27,  4.87s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  18%|▏| 55/306 [04:40<20:32,  4.91s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  18%|▏| 56/306 [04:43<18:14,  4.38s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  19%|▏| 57/306 [04:45<15:30,  3.74s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  19%|▏| 58/306 [04:51<17:51,  4.32s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  19%|▏| 59/306 [04:53<14:25,  3.50s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  20%|▏| 60/306 [04:56<13:04,  3.19s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 60/306 строк

Обработка текстов Qwen2.5-3B:  20%|▏| 61/306 [04:59<13:36,  3.33s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  20%|▏| 62/306 [05:04<15:13,  3.74s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  21%|▏| 63/306 [05:08<15:45,  3.89s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  21%|▏| 64/306 [05:17<22:16,  5.52s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  21%|▏| 65/306 [05:22<21:23,  5.33s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  22%|▏| 66/306 [05:33<28:15,  7.06s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  22%|▏| 67/306 [05:34<21:05,  5.29s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  22%|▏| 68/306 [05:36<17:16,  4.35s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  23%|▏| 69/306 [05:40<16:34,  4.20s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  23%|▏| 70/306 [05:49<21:45,  5.53s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 70/306 строк

Обработка текстов Qwen2.5-3B:  23%|▏| 71/306 [06:00<28:17,  7.22s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  24%|▏| 72/306 [06:02<21:52,  5.61s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  24%|▏| 73/306 [06:05<18:54,  4.87s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  24%|▏| 74/306 [06:11<20:08,  5.21s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  25%|▏| 75/306 [06:15<18:43,  4.86s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  25%|▏| 76/306 [06:18<15:59,  4.17s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  25%|▎| 77/306 [06:24<18:00,  4.72s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  25%|▎| 78/306 [06:26<14:51,  3.91s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  26%|▎| 79/306 [06:28<12:50,  3.40s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  26%|▎| 80/306 [06:30<11:14,  2.98s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 80/306 строк

Обработка текстов Qwen2.5-3B:  26%|▎| 81/306 [06:36<14:48,  3.95s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  27%|▎| 82/306 [06:40<14:50,  3.97s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  27%|▎| 83/306 [06:43<13:16,  3.57s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  27%|▎| 84/306 [06:47<14:14,  3.85s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  28%|▎| 85/306 [06:50<13:10,  3.58s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  28%|▎| 86/306 [06:54<13:15,  3.62s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  28%|▎| 87/306 [06:56<11:53,  3.26s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  29%|▎| 88/306 [07:01<12:47,  3.52s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  29%|▎| 89/306 [07:05<13:56,  3.86s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  29%|▎| 90/306 [07:13<17:55,  4.98s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 90/306 строк

Обработка текстов Qwen2.5-3B:  30%|▎| 91/306 [07:15<14:36,  4.08s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  30%|▎| 92/306 [07:17<12:51,  3.61s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  30%|▎| 93/306 [07:19<11:11,  3.15s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  31%|▎| 94/306 [07:30<18:41,  5.29s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  31%|▎| 95/306 [07:31<14:51,  4.22s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  31%|▎| 96/306 [07:33<12:16,  3.51s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  32%|▎| 97/306 [07:37<12:55,  3.71s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  32%|▎| 98/306 [07:40<11:23,  3.29s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  32%|▎| 99/306 [07:55<24:13,  7.02s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  33%|▎| 100/306 [07:57<18:33,  5.40s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 100/306 строк

Обработка текстов Qwen2.5-3B:  33%|▎| 101/306 [07:58<14:04,  4.12s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  33%|▎| 102/306 [08:00<12:08,  3.57s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  34%|▎| 103/306 [08:04<11:34,  3.42s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  34%|▎| 104/306 [08:05<09:40,  2.87s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  34%|▎| 105/306 [08:11<13:03,  3.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  35%|▎| 106/306 [08:15<12:21,  3.71s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  35%|▎| 107/306 [08:16<09:46,  2.95s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  35%|▎| 108/306 [08:20<11:15,  3.41s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  36%|▎| 109/306 [08:27<14:16,  4.35s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  36%|▎| 110/306 [08:33<15:26,  4.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 110/306 строк

Обработка текстов Qwen2.5-3B:  36%|▎| 111/306 [08:37<15:34,  4.79s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  37%|▎| 112/306 [08:45<18:01,  5.57s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  37%|▎| 113/306 [08:47<14:27,  4.49s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  37%|▎| 114/306 [08:50<13:10,  4.12s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  38%|▍| 115/306 [08:53<12:27,  3.91s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  38%|▍| 116/306 [08:57<12:26,  3.93s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  38%|▍| 117/306 [09:14<24:27,  7.77s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  39%|▍| 118/306 [09:17<19:30,  6.23s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  39%|▍| 119/306 [09:24<20:12,  6.48s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  39%|▍| 120/306 [09:29<18:08,  5.85s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 120/306 строк

Обработка текстов Qwen2.5-3B:  40%|▍| 121/306 [09:31<14:54,  4.83s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  40%|▍| 122/306 [09:34<13:09,  4.29s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  40%|▍| 123/306 [09:40<14:30,  4.76s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  41%|▍| 124/306 [09:42<12:28,  4.11s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  41%|▍| 125/306 [09:45<11:17,  3.74s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  41%|▍| 126/306 [09:48<10:04,  3.36s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  42%|▍| 127/306 [09:55<13:32,  4.54s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  42%|▍| 128/306 [09:59<13:14,  4.46s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  42%|▍| 129/306 [10:01<11:03,  3.75s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  42%|▍| 130/306 [10:06<11:48,  4.03s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 130/306 строк

Обработка текстов Qwen2.5-3B:  43%|▍| 131/306 [10:11<12:57,  4.44s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  43%|▍| 132/306 [10:16<13:17,  4.58s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  43%|▍| 133/306 [10:19<11:48,  4.10s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  44%|▍| 134/306 [10:23<11:35,  4.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  44%|▍| 135/306 [10:26<10:59,  3.86s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  44%|▍| 136/306 [10:42<20:53,  7.38s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  45%|▍| 137/306 [10:44<16:15,  5.77s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  45%|▍| 138/306 [10:48<14:38,  5.23s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  45%|▍| 139/306 [10:50<11:55,  4.29s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  46%|▍| 140/306 [10:52<09:50,  3.56s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 140/306 строк

Обработка текстов Qwen2.5-3B:  46%|▍| 141/306 [10:59<12:14,  4.45s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  46%|▍| 142/306 [11:01<10:31,  3.85s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  47%|▍| 143/306 [11:06<11:16,  4.15s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  47%|▍| 144/306 [11:13<13:59,  5.18s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  47%|▍| 145/306 [11:20<15:00,  5.59s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  48%|▍| 146/306 [11:24<13:56,  5.23s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  48%|▍| 147/306 [11:26<11:14,  4.24s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  48%|▍| 148/306 [11:30<10:31,  4.00s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  49%|▍| 149/306 [11:32<09:10,  3.50s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  49%|▍| 150/306 [11:34<07:48,  3.00s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 150/306 строк

Обработка текстов Qwen2.5-3B:  49%|▍| 151/306 [11:40<10:04,  3.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  50%|▍| 152/306 [11:43<09:29,  3.70s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  50%|▌| 153/306 [11:46<09:02,  3.55s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  50%|▌| 154/306 [11:50<08:44,  3.45s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  51%|▌| 155/306 [12:14<24:14,  9.63s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  51%|▌| 156/306 [12:17<19:18,  7.72s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  51%|▌| 157/306 [12:21<16:28,  6.63s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  52%|▌| 158/306 [12:36<22:46,  9.24s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  52%|▌| 159/306 [12:42<20:22,  8.32s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  52%|▌| 160/306 [12:46<16:33,  6.80s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 160/306 строк

Обработка текстов Qwen2.5-3B:  53%|▌| 161/306 [12:50<14:51,  6.15s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  53%|▌| 162/306 [12:54<13:16,  5.53s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  53%|▌| 163/306 [12:59<12:35,  5.28s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  54%|▌| 164/306 [13:04<12:10,  5.15s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  54%|▌| 165/306 [13:06<09:52,  4.21s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  54%|▌| 166/306 [13:16<14:07,  6.05s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  55%|▌| 167/306 [13:55<36:41, 15.84s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  55%|▌| 168/306 [13:57<27:04, 11.77s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  55%|▌| 169/306 [14:02<21:52,  9.58s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  56%|▌| 170/306 [14:16<24:26, 10.78s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 170/306 строк

Обработка текстов Qwen2.5-3B:  56%|▌| 171/306 [14:18<19:04,  8.48s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  56%|▌| 172/306 [14:23<16:18,  7.31s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  57%|▌| 173/306 [14:29<15:07,  6.82s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  57%|▌| 174/306 [14:37<16:08,  7.34s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  57%|▌| 175/306 [15:08<31:14, 14.31s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 176/306 [15:09<22:45, 10.51s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 177/306 [15:12<17:17,  8.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 178/306 [15:19<16:28,  7.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 179/306 [15:22<13:15,  6.26s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  59%|▌| 180/306 [15:25<10:50,  5.16s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 180/306 строк

Обработка текстов Qwen2.5-3B:  59%|▌| 181/306 [15:33<12:51,  6.17s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  59%|▌| 182/306 [15:35<10:25,  5.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  60%|▌| 183/306 [15:39<09:27,  4.62s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  60%|▌| 184/306 [15:44<09:47,  4.82s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  60%|▌| 185/306 [15:46<08:12,  4.07s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  61%|▌| 186/306 [15:51<08:46,  4.39s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  61%|▌| 187/306 [15:56<08:53,  4.48s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  61%|▌| 188/306 [15:59<07:53,  4.01s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  62%|▌| 189/306 [16:02<06:54,  3.54s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  62%|▌| 190/306 [16:05<06:45,  3.50s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 190/306 строк

Обработка текстов Qwen2.5-3B:  62%|▌| 191/306 [16:09<07:08,  3.72s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  63%|▋| 192/306 [16:16<08:48,  4.64s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  63%|▋| 193/306 [16:18<07:29,  3.98s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  63%|▋| 194/306 [16:26<09:16,  4.97s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  64%|▋| 195/306 [16:30<08:43,  4.71s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  64%|▋| 196/306 [16:33<07:42,  4.21s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  64%|▋| 197/306 [16:35<06:20,  3.49s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  65%|▋| 198/306 [16:36<05:20,  2.96s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  65%|▋| 199/306 [16:39<05:02,  2.83s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  65%|▋| 200/306 [16:45<06:17,  3.56s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 200/306 строк

Обработка текстов Qwen2.5-3B:  66%|▋| 201/306 [16:48<06:31,  3.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  66%|▋| 202/306 [16:52<06:36,  3.81s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  66%|▋| 203/306 [16:55<05:45,  3.35s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  67%|▋| 204/306 [16:59<06:03,  3.56s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  67%|▋| 205/306 [17:02<05:44,  3.41s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  67%|▋| 206/306 [17:03<04:49,  2.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  68%|▋| 207/306 [17:10<06:28,  3.93s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  68%|▋| 208/306 [17:14<06:47,  4.16s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  68%|▋| 209/306 [17:16<05:22,  3.32s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  69%|▋| 210/306 [17:19<04:57,  3.10s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 210/306 строк

Обработка текстов Qwen2.5-3B:  69%|▋| 211/306 [17:23<05:43,  3.62s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  69%|▋| 212/306 [17:28<06:11,  3.95s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  70%|▋| 213/306 [17:29<04:44,  3.06s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  70%|▋| 214/306 [17:35<06:06,  3.99s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  70%|▋| 215/306 [17:41<06:51,  4.52s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  71%|▋| 216/306 [17:47<07:36,  5.07s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  71%|▋| 217/306 [17:50<06:36,  4.46s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  71%|▋| 218/306 [17:55<06:28,  4.42s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  72%|▋| 219/306 [18:00<06:57,  4.80s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  72%|▋| 220/306 [18:03<05:50,  4.08s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 220/306 строк

Обработка текстов Qwen2.5-3B:  72%|▋| 221/306 [18:07<05:45,  4.06s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  73%|▋| 222/306 [18:10<05:14,  3.75s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  73%|▋| 223/306 [18:14<05:33,  4.02s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  73%|▋| 224/306 [18:17<04:55,  3.60s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  74%|▋| 225/306 [18:19<04:21,  3.22s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  74%|▋| 226/306 [18:22<04:06,  3.08s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  74%|▋| 227/306 [18:28<05:01,  3.81s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  75%|▋| 228/306 [18:30<04:32,  3.49s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  75%|▋| 229/306 [18:32<03:41,  2.87s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  75%|▊| 230/306 [18:39<05:07,  4.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 230/306 строк

Обработка текстов Qwen2.5-3B:  75%|▊| 231/306 [18:41<04:21,  3.49s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  76%|▊| 232/306 [18:42<03:38,  2.95s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  76%|▊| 233/306 [18:46<03:40,  3.02s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  76%|▊| 234/306 [19:06<09:59,  8.33s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  77%|▊| 235/306 [19:09<08:01,  6.78s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  77%|▊| 236/306 [19:14<07:06,  6.09s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  77%|▊| 237/306 [19:16<05:42,  4.96s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  78%|▊| 238/306 [19:18<04:27,  3.93s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  78%|▊| 239/306 [19:21<04:10,  3.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  78%|▊| 240/306 [19:25<03:55,  3.56s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 240/306 строк

Обработка текстов Qwen2.5-3B:  79%|▊| 241/306 [19:32<05:15,  4.85s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  79%|▊| 242/306 [19:33<04:01,  3.77s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  79%|▊| 243/306 [19:37<04:02,  3.85s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  80%|▊| 244/306 [19:43<04:40,  4.52s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  80%|▊| 245/306 [19:45<03:44,  3.68s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  80%|▊| 246/306 [19:47<03:14,  3.25s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  81%|▊| 247/306 [19:52<03:34,  3.64s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  81%|▊| 248/306 [20:11<07:59,  8.27s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  81%|▊| 249/306 [20:15<06:39,  7.02s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  82%|▊| 250/306 [20:21<05:59,  6.43s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 250/306 строк

Обработка текстов Qwen2.5-3B:  82%|▊| 251/306 [20:21<04:24,  4.80s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  82%|▊| 252/306 [20:31<05:41,  6.32s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  83%|▊| 253/306 [20:33<04:30,  5.11s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  83%|▊| 254/306 [20:38<04:11,  4.84s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  83%|▊| 255/306 [20:41<03:43,  4.38s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  84%|▊| 256/306 [20:44<03:23,  4.07s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  84%|▊| 257/306 [20:50<03:51,  4.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  84%|▊| 258/306 [20:55<03:39,  4.58s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  85%|▊| 259/306 [21:00<03:38,  4.65s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  85%|▊| 260/306 [21:07<04:06,  5.35s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 260/306 строк

Обработка текстов Qwen2.5-3B:  85%|▊| 261/306 [21:10<03:35,  4.78s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  86%|▊| 262/306 [21:23<05:20,  7.28s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  86%|▊| 263/306 [21:29<04:54,  6.84s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  86%|▊| 264/306 [21:33<04:07,  5.88s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  87%|▊| 265/306 [21:37<03:41,  5.40s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  87%|▊| 266/306 [21:39<02:52,  4.32s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  87%|▊| 267/306 [21:41<02:21,  3.63s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  88%|▉| 268/306 [21:44<02:11,  3.46s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  88%|▉| 269/306 [21:47<02:07,  3.46s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  88%|▉| 270/306 [21:50<01:54,  3.17s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 270/306 строк

Обработка текстов Qwen2.5-3B:  89%|▉| 271/306 [21:57<02:30,  4.29s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  89%|▉| 272/306 [22:02<02:42,  4.77s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  89%|▉| 273/306 [22:10<03:07,  5.68s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  90%|▉| 274/306 [22:14<02:45,  5.17s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  90%|▉| 275/306 [22:20<02:42,  5.25s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  90%|▉| 276/306 [22:28<03:06,  6.20s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  91%|▉| 277/306 [22:30<02:23,  4.95s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  91%|▉| 278/306 [22:32<01:55,  4.14s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  91%|▉| 279/306 [22:35<01:36,  3.57s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  92%|▉| 280/306 [22:41<01:51,  4.30s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 280/306 строк

Обработка текстов Qwen2.5-3B:  92%|▉| 281/306 [22:45<01:44,  4.19s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  92%|▉| 282/306 [22:46<01:22,  3.44s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  92%|▉| 283/306 [22:48<01:07,  2.94s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  93%|▉| 284/306 [22:54<01:26,  3.92s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  93%|▉| 285/306 [22:56<01:10,  3.35s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  93%|▉| 286/306 [23:00<01:09,  3.47s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  94%|▉| 287/306 [23:02<00:58,  3.09s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  94%|▉| 288/306 [23:06<01:00,  3.36s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  94%|▉| 289/306 [23:10<01:00,  3.54s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  95%|▉| 290/306 [23:17<01:09,  4.37s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 290/306 строк

Обработка текстов Qwen2.5-3B:  95%|▉| 291/306 [23:19<00:56,  3.79s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  95%|▉| 292/306 [23:22<00:50,  3.64s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  96%|▉| 293/306 [23:25<00:45,  3.47s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  96%|▉| 294/306 [23:37<01:10,  5.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  96%|▉| 295/306 [23:39<00:51,  4.71s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  97%|▉| 296/306 [23:41<00:41,  4.11s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  97%|▉| 297/306 [23:44<00:32,  3.62s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  97%|▉| 298/306 [23:48<00:29,  3.72s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  98%|▉| 299/306 [23:56<00:34,  4.95s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  98%|▉| 300/306 [23:59<00:25,  4.29s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 300/306 строк

Обработка текстов Qwen2.5-3B:  98%|▉| 301/306 [24:06<00:25,  5.15s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  99%|▉| 302/306 [24:07<00:16,  4.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  99%|▉| 303/306 [24:10<00:10,  3.64s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  99%|▉| 304/306 [24:12<00:06,  3.19s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B: 100%|▉| 305/306 [24:17<00:03,  3.86s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B: 100%|█| 306/306 [24:21<00:00,  4.78s/текст, успех=

======================================================================
✅ ОБРАБОТКА ЗАВЕРШЕНА
   Всего строк:    306
   Успешно:        306 (100.0%)
   Ошибок:         0 (0.0%)
   Результаты:     df_res_with_qwen_answers.csv
======================================================================

🔍 Примеры ответов:

Строка 0:
   Ответ: Semantic image segmentation...

Строка 1:
   Ответ: Volumetric medical image segmentation...

Строка 2:
   Ответ: Question Answering...

Строка 3:
   Ответ: Matching question and answer...

Строка 4:
   Ответ: Mastering chess and shogi...

In [16]:
df_res.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new,qwen2.5-3B_answer
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}",Semantic image segmentation
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],"classification, segmentation and object detect...",--None--,--None--,"{'cosine_sim': 0.5885287523269653, 'lev_dist':...","{'cosine_sim': 0.5885287523269653, 'lev_dist':...",Volumetric medical image segmentation
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}",Question Answering
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],determine the semantic relationship between tw...,--None--,--None--,"{'cosine_sim': 0.6914587616920471, 'lev_dist':...","{'cosine_sim': 0.6914587616920471, 'lev_dist':...",Matching question and answer
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",search is focused on promising variations,--None--,--None--,"{'cosine_sim': 0.5607925653457642, 'lev_dist':...","{'cosine_sim': 0.5607925653457642, 'lev_dist':...",Mastering chess and shogi

In [17]:
df_res11 = pd.read_csv('df_res_with_qwen_answers.csv')
df_res11.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new,qwen2.5-3B_answer
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"['Semantic_Segmentation', 'Real-Time_Semantic_...","['Semantic Segmentation', 'Real-Time Semantic ...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}",Semantic image segmentation
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,['Volumetric_Medical_Image_Segmentation'],['Volumetric Medical Image Segmentation'],"classification, segmentation and object detect...",--None--,--None--,"{'cosine_sim': 0.5885287523269653, 'lev_dist':...","{'cosine_sim': 0.5885287523269653, 'lev_dist':...",Volumetric medical image segmentation
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"['Question_Answering', 'Open-Domain_Question_A...","['Question Answering', 'Open-Domain Question A...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}",Question Answering
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,['Natural_Language_Inference'],['Natural Language Inference'],determine the semantic relationship between tw...,--None--,--None--,"{'cosine_sim': 0.6914587616920471, 'lev_dist':...","{'cosine_sim': 0.6914587616920471, 'lev_dist':...",Matching question and answer
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"['Game_of_Go', 'Game_of_Shogi']","['Game of Go', 'Game of Shogi']",search is focused on promising variations,--None--,--None--,"{'cosine_sim': 0.5607925653457642, 'lev_dist':...","{'cosine_sim': 0.5607925653457642, 'lev_dist':...",Mastering chess and shogi

In [14]:
# Пример применения к вашему датафрейму
context = df_res.iloc[0]['original_text']
question = "Which task was solved? Give a short answer without explanation"

print("📄 Длина текста:", len(tokenizer.encode(context, add_special_tokens=False)), "токенов")
print("\n❓ Вопрос:", question)
print("\n✅ Ответ:")
print(answer_question_qwen(context, question))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

📄 Длина текста: 7067 токенов

❓ Вопрос: Which task was solved? Give a short answer without explanation

✅ Ответ:
Semantic image segmentation

In [6]:
from transformers import *
roberta_qa_dir = "/home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model"

model = AutoModelForQuestionAnswering.from_pretrained(roberta_qa_dir, output_attentions=True).to(device)
concrete_tokenizer = AutoTokenizer.from_pretrained(roberta_qa_dir)

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/config.json
Model config RobertaConfig {
  "architectures": [
    "RobertaForQuestionAnswering"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "language": "english",
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "name": "Roberta",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "output_attentions": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 50265
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model/model.safetensors
All model checkpoint weights were used when initializing RobertaForQuestionAnswering.

All the weights of RobertaForQuestionAnswering were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/bert_eng_qa_baseroberta_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use RobertaForQuestionAnswering for predictions without further training.
loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

In [7]:
from transformers import pipeline
import torch

# Загрузка модели (весит всего ~50 МБ)
qa_pipeline = pipeline(
    "question-answering",
    model=model,
    tokenizer=concrete_tokenizer,
    device=1 if torch.cuda.is_available() else -1,  # -1 = CPU
    max_seq_len=512,      # максимальная длина чанка
    doc_stride=128,       # перекрытие между чанками (рекомендуется 128)
    max_answer_len=100    # макс. длина извлекаемого ответа
)

Device set to use cuda:1

In [8]:
idx = 0

context = str(df_res.loc[idx, 'original_text'])
question = "Which task was solved?"

In [9]:
result = qa_pipeline(
            question=question,
            context=context,
            handle_impossible_answer=True,
            max_seq_len=512,
            doc_stride=128
        )
result

Disabling tokenizer parallelism, we're using DataLoader multithreading already
RobertaSdpaSelfAttention is used but `torch.nn.functional.scaled_dot_product_attention` does not support non-absolute `position_embedding_type` or `output_attentions=True` or `head_mask`. Falling back to the manual attention implementation, but specifying the manual implementation will be required from Transformers version v5.0.0 onwards. This warning can be removed using the argument `attn_implementation="eager"` when loading the model.

{'score': 0.33691877126693726, 'start': 0, 'end': 0, 'answer': ''}

In [46]:
def answer_question_roberta(context: str, question: str) -> str:
    """
    Надёжная функция для RoBERTa QA. Всегда возвращает непустую строку.
    """
    # === 1. Валидация входных данных ===
    if not isinstance(context, str) or not context.strip():
        return "ERROR: пустой или некорректный текст"
    if not isinstance(question, str) or not question.strip():
        return "ERROR: пустой вопрос"
    
    # === 2. Вызов модели ===
    try:
        result = qa_pipeline(
            question=question,
            context=context,
            handle_impossible_answer=True,
            max_seq_len=512,
            doc_stride=128
        )
    except Exception as e:
        return f"ERROR: pipeline exception ({type(e).__name__})"
    
    # === 3. Обработка результата ===
    try:
        # Список ответов (длинный текст)
        if isinstance(result, list) and result:
            # Фильтруем только словари с ответами
            valid_answers = [
                r for r in result 
                if isinstance(r, dict) 
                and 'answer' in r 
                and isinstance(r['answer'], str)
                # and len(r['answer'].strip()) >= 2  # минимум 2 символа
                # and r.get('score', 0) > 0.001       # любой ненулевой скор
            ]
            
            if valid_answers:
                # Берём ответ с максимальным скором
                best = max(valid_answers, key=lambda x: x.get('score', 0))
                answer = best['answer'].strip()
                # Ограничиваем длину ответа
                return answer[:150] if answer else "Ответ не найден"
            else:
                return "Ответ не найден"
        
        # Один ответ (короткий текст)
        elif isinstance(result, dict) and 'answer' in result:
            answer = str(result.get('answer', '')).strip()
            if len(answer) >= 2 and result.get('score', 0) > 0.001:
                return answer[:150]
            else:
                return "Ответ не найден"
        
        # Любой другой случай
        else:
            return "Ответ не найден"
    
    except Exception as e:
        return f"ERROR: processing exception ({type(e).__name__})"

In [47]:
df_res = df_res.drop(columns=['roberta_answer'])

In [48]:
import pandas as pd
import time
from tqdm import tqdm

# === КРИТИЧЕСКИ ВАЖНО: Очистка колонки от существующих NaN ===
if 'roberta_answer' in df_res.columns:
    df_res['roberta_answer'] = df_res['roberta_answer'].fillna("").astype(str)
else:
    df_res['roberta_answer'] = ""

# Убедимся, что original_text не содержит NaN
df_res['original_text'] = df_res['original_text'].fillna("")

question = "Which task was solved?"

pbar = tqdm(total=len(df_res), desc="RoBERTa QA", unit="текст", ncols=80)

for idx in range(len(df_res)):
    # Пропускаем уже обработанные (не "Ответ не найден" и не ошибки)
    current = str(df_res.loc[idx, 'roberta_answer']).strip()
    if current and not current.startswith(("Ответ не найден", "ERROR")):
        pbar.update(1)
        continue
    
    context = str(df_res.loc[idx, 'original_text'])
    
    # Получаем ответ (гарантированно строка)
    answer = answer_question_roberta(context, question)
    
    # Принудительно сохраняем как строку
    df_res.loc[idx, 'roberta_answer'] = str(answer)
    
    pbar.update(1)
    
    # Промежуточное сохранение
    if (idx + 1) % 10 == 0:
        df_res.to_csv('df_res_with_roberta.csv', index=False)
        pbar.set_postfix({"последний": answer[:30]})

pbar.close()
df_res.to_csv('df_res_with_roberta.csv', index=False)

# Финальная статистика
total = len(df_res)
not_found = df_res['roberta_answer'].str.contains("Ответ не найден", na=False).sum()
errors = df_res['roberta_answer'].str.startswith("ERROR", na=False).sum()
valid = total - not_found - errors
nan_check = df_res['roberta_answer'].isna().sum()

print("\n" + "="*70)
print("✅ ОБРАБОТКА ЗАВЕРШЕНА")
print(f"   Всего строк:          {total}")
print(f"   Валидных ответов:     {valid} ({valid/total*100:.1f}%)")
print(f"   'Ответ не найден':    {not_found} ({not_found/total*100:.1f}%)")
print(f"   Ошибок:               {errors} ({errors/total*100:.1f}%)")
print(f"   NaN в колонке:        {nan_check} ← ДОЛЖНО БЫТЬ 0")
print("="*70)

# Примеры хороших ответов
print("\n🔍 Примеры найденных ответов:")
valid_answers = df_res[~df_res['roberta_answer'].str.contains("Ответ не найден|ERROR", na=False)]
for i, (_, row) in enumerate(valid_answers.head(5).iterrows()):
    print(f"{i+1}. {row['roberta_answer']}")

RoBERTa QA: 100%|█| 306/306 [01:30<00:00,  3.37текст/s, последний=Ответ не найде

======================================================================
✅ ОБРАБОТКА ЗАВЕРШЕНА
   Всего строк:          306
   Валидных ответов:     63 (20.6%)
   'Ответ не найден':    243 (79.4%)
   Ошибок:               0 (0.0%)
   NaN в колонке:        0 ← ДОЛЖНО БЫТЬ 0
======================================================================

🔍 Примеры найденных ответов:
1. classification, segmentation and object detection
2. 1 to 7
3. 3D facial landmark localisation
4. estimating image distribution
5. Dense Human Pose Estimation

In [ ]:
from transformers import AutoTokenizer

# tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen2.5-0.5B")

In [ ]:
import pandas as pd

# Пример датафрейма (замените на ваш)
# df = pd.read_csv('your_dataset.csv')

# # Функция подсчёта токенов БЕЗ специальных токенов (<BOS>/<EOS>)
# def count_tokens(text: str) -> int:
#     if pd.isna(text) or not isinstance(text, str):
#         return 0
#     # return_tensors=None → возвращаем список, не тензор
#     tokens = tokenizer.encode(text, add_special_tokens=False)
#     return len(tokens)

# # Применяем к колонке
# df_res['token_count'] = df_res['original_text'].apply(count_tokens)

In [ ]:
df_res.head()

In [ ]:
# # Базовая статистика
# print("Статистика длин текстов в токенах:")
# print(df_res['token_count'].describe())

# # Критические пороги для модели 0.5B
# print("\n⚠️ Рекомендации для Qwen2.5-0.5B:")
# print(f"  • Текстов > 256 токенов: {(df_res['token_count'] > 256).sum()} ({(df_res['token_count'] > 256).mean()*100:.1f}%)")
# print(f"  • Текстов > 512 токенов: {(df_res['token_count'] > 512).sum()} ({(df_res['token_count'] > 512).mean()*100:.1f}%)")
# print(f"  • Максимальная длина: {df_res['token_count'].max()} токенов")

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

model_id = "microsoft/Phi-3-mini-128k-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,
    trust_remote_code=True,
    low_cpu_mem_usage=True,
    attn_implementation="eager",  # ← КЛЮЧЕВОЙ ПАРАМЕТР для обхода ошибки
).to(device)

In [ ]:
def answer_question_phi3(context: str, question: str, max_new_tokens: int = 200) -> str:
    """
    Получает ответ от Phi-3-mini-128k-instruct на вопрос по тексту.
    Работает без ошибки DynamicCache благодаря use_cache=False.
    """
    # Упрощённый промпт без применения шаблона (избегаем проблем с apply_chat_template)
    prompt = f"""<|user|>
Текст: {context}

Вопрос: {question}<|end|>
<|assistant|>"""
    
    # Токенизация с безопасным лимитом для CPU
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=8192  # достаточно для ваших текстов (макс. 15,752 токенов)
    ).to(device)
    
    # Генерация с ОБХОДОМ ошибки DynamicCache
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.3,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            use_cache=False  # ← КЛЮЧЕВОЙ ПАРАМЕТР для обхода ошибки
        )
    
    # Декодирование и очистка ответа
    full_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    
    # Извлекаем только часть после <|assistant|>
    if "<|assistant|>" in full_text:
        answer = full_text.split("<|assistant|>")[-1].strip()
    else:
        # Fallback: убираем промпт
        prompt_clean = tokenizer.decode(inputs.input_ids[0], skip_special_tokens=True)
        answer = full_text.replace(prompt_clean, "").strip()
    
    # Убираем возможные повторы промпта в ответе
    if "Вопрос:" in answer:
        answer = answer.split("Вопрос:")[0].strip()
    
    return answer.strip()

In [ ]:
# Пример применения к вашему датафрейму
context = df_res.iloc[0]['original_text']
question = "Какова основная тема этого текста?"

print("📄 Длина текста:", len(tokenizer.encode(context, add_special_tokens=False)), "токенов")
print("\n❓ Вопрос:", question)
print("\n✅ Ответ:")
print(answer_question_phi3(context, question))

In [ ]:
import torch, psutil, os

print("Устройство модели:", next(model.parameters()).device)
print("Тип данных модели:", next(model.parameters()).dtype)
print(f"Свободная ОЗУ: {psutil.virtual_memory().available / 1024**3:.1f} ГБ из {psutil.virtual_memory().total / 1024**3:.1f} ГБ")
print(f"Используется swap: {psutil.swap_memory().used / 1024**3:.1f} ГБ")