In [1]:
from system_check import *
CUDA_state_print_limited()

CUDA доступна: True
Количество GPU: 4

In [2]:
%%capture
import sys
sys.path.append("/global_functions")
from global_functions.global_functions import *

device = get_device()

In [3]:
datasets_results_path = "../datasets_results"
res_name = "results_2.json"

df_res = load_dataframe_from_json(f"{datasets_results_path}/{res_name}")

df_res.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}"
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,[Volumetric_Medical_Image_Segmentation],[Volumetric Medical Image Segmentation],"classification, segmentation and object detect...",--None--,--None--,"{'cosine_sim': 0.5885287523269653, 'lev_dist':...","{'cosine_sim': 0.5885287523269653, 'lev_dist':..."
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}"
3,0095c269e7d0c990249312687fc43521019809c4,document: Modelling Interaction of Sentence Pa...,[Natural_Language_Inference],[Natural Language Inference],determine the semantic relationship between tw...,--None--,--None--,"{'cosine_sim': 0.6914587616920471, 'lev_dist':...","{'cosine_sim': 0.6914587616920471, 'lev_dist':..."
4,00b1cdc5bd77bf27f9b1ca630365eeeb456913b4,document: Mastering Chess and Shogi by Self - ...,"[Game_of_Go, Game_of_Shogi]","[Game of Go, Game of Shogi]",search is focused on promising variations,--None--,--None--,"{'cosine_sim': 0.5607925653457642, 'lev_dist':...","{'cosine_sim': 0.5607925653457642, 'lev_dist':..."

In [4]:
df_filtered = df_res[df_res['corrected_answer'] != "--None--"]

print(df_res.shape)
print(df_filtered.shape)

(306, 9)
(244, 9)

In [5]:
df_filtered.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}"
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}"
5,01125e3c68edb420b8d884ff53fb38d9fbe4f2b8,document: Large Pose 3D Face Reconstruction fr...,[3D_Face_Reconstruction],[3D Face Reconstruction],3D facial landmark localisation,3D facial landmark localisation,"['training', 'novel', 'architecture', 'assumpt...","{'cosine_sim': 0.9436883926391602, 'lev_dist':...","{'cosine_sim': 0.9436883926391602, 'lev_dist':..."
6,0116899fce00ffa4afee08b505300bb3968faf9f,Long Text Generation via Adversarial Training ...,[Text_Generation],[Text Generation],the next word to select,the next word to select,"['game', 'training', 'discriminator']","{'cosine_sim': 0.6716794371604919, 'lev_dist':...","{'cosine_sim': 0.6716794371604919, 'lev_dist':..."
7,0171bdeb1c6e333287be655c667cfba5edb89b76,Aggregated Residual Transformations for Deep N...,[Image_Classification],[Image Classification],factors.,Object Detection,"['reduce', 'average', 'recently']","{'cosine_sim': 0.6920448541641235, 'lev_dist':...","{'cosine_sim': 0.8140521049499512, 'lev_dist':..."

In [6]:
# import evaluate

# bertscore = evaluate.load("bertscore")
# results = bertscore.compute(
#     predictions=["Париж"],
#     references=["Столица Франции — Париж"],
#     lang="ru"
# )

In [7]:
# correct_ans = ", ".join(df_res.iloc[0].tasks_cleaned)
# correct_ans

In [8]:
# pred_ans = df_res.iloc[0].corrected_answer
# pred_ans

In [9]:
# results = bertscore.compute(
#     predictions=[pred_ans],
#     references=[correct_ans],
#     lang="en"
# )
# results

In [10]:
# results = bertscore.compute(
#     predictions=[pred_ans],
#     references=[df_res.iloc[0].tasks_cleaned],
#     lang="en"
# )
# results

In [11]:
# from bert_score import score

# P, R, F1 = score(
#     cands=[pred_ans],        # предсказания (список строк)
#     refs=[df_res.iloc[0].tasks_cleaned],      # эталоны (список строк)
#     lang="en",                     # язык → автоматически выбирает модель
#     # ИЛИ явно указать модель:
#     # model_type="DeepPavlov/rubert-base-cased",
    
#     # Дополнительные аргументы:
#     idf=False,                     # взвешивать токены по IDF (требует корпуса)
#     batch_size=64,                 # размер батча для инференса
#     num_layers=None,               # номер слоя для эмбеддингов (None → последний)
#     verbose=False,                 # показывать прогресс-бар
#     device=device,
#     rescale_with_baseline=False,   # нормализовать относительно baseline (улучшает интерпретируемость)
#     baseline_path=None             # путь к кастомному baseline
# )

In [12]:
# P, R, F1

In [13]:
# squad = evaluate.load("squad")

# results = squad.compute(
#     predictions=[{"id": "0", "prediction_text": "Париж"}],
#     references=[{
#         "id": "0",
#         "answers": {"text": ["Париж"], "answer_start": [0]}
#     }]
# )

In [14]:
# results = squad.compute(
#     predictions=[{"id": "0", "prediction_text": pred_ans}],
#     references=[{
#         "id": "0",
#         "answers": {"text": df_res.iloc[0].tasks_cleaned, "answer_start": [0]}
#     }]
# )
# results

In [15]:
# P, R, F1 = score(
#     cands=["Париж"],  # один кандидат
#     refs=[["Париж", "Столица Франции", "Город на Сене"]],  # список из одного списка эталонов
#     lang="ru"
# )

# print(f"BERTScore F1: {F1.max().item():.4f}")  # max по эталонам для этого сэмпла

In [16]:
# R

In [17]:
# from collections import Counter
# from typing import Union, List

# def char_f1(pred: str, gold: Union[str, List[str]]) -> float:
#     """
#     Character-level F1 с поддержкой нескольких эталонных ответов.
#     Возвращает максимальное значение по всем эталонам.
#     """
#     # Нормализация: приводим к списку
#     if isinstance(gold, str):
#         gold = [gold]
    
#     # Обработка пустого списка эталонов
#     if not gold:
#         return 0.0
    
#     # Вычисляем F1 для каждого эталона
#     scores = []
#     pred_lower = pred.lower()
#     pred_chars = Counter(pred_lower)
    
#     for g in gold:
#         if not g:  # пустая строка или None
#             scores.append(0.0)
#             continue
        
#         g_lower = g.lower()
#         gold_chars = Counter(g_lower)
#         common = sum((pred_chars & gold_chars).values())
        
#         if common == 0:
#             scores.append(0.0)
#             continue
        
#         precision = common / len(pred_lower) if pred_lower else 0.0
#         recall = common / len(g_lower) if g_lower else 0.0
#         f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0.0
#         scores.append(f1)
    
#     return max(scores)

In [18]:
# char_f1(pred_ans, df_res.iloc[0].tasks_cleaned)

In [33]:
from collections import Counter
from typing import Union, List
from rouge_score import rouge_scorer
from bert_score import score
import evaluate


# === 1. Character-level F1  ===
def char_f1(pred: str, gold: Union[str, List[str]]) -> float:
    if pd.isna(pred) or not str(pred).strip():
        return 0.0
    if isinstance(gold, str):
        gold = [gold]
    if not gold or all(pd.isna(g) or not str(g).strip() for g in gold):
        return 0.0
    
    scores = []
    pred_lower = str(pred).lower()
    pred_chars = Counter(pred_lower)
    
    for g in gold:
        if pd.isna(g) or not str(g).strip():
            continue
        g_lower = str(g).lower()
        gold_chars = Counter(g_lower)
        common = sum((pred_chars & gold_chars).values())
        if common == 0:
            continue
        precision = common / len(pred_lower)
        recall = common / len(g_lower)
        f1 = 2 * precision * recall / (precision + recall)
        scores.append(f1)
    
    return max(scores) if scores else 0.0

# === 2. Token-level F1 (SQuAD) ===
_squad_metric = None

def token_f1(pred: str, gold: Union[str, List[str]]) -> float:
    global _squad_metric
    if _squad_metric is None:
        _squad_metric = evaluate.load("squad")
    
    if isinstance(gold, str):
        gold = [gold]
    
    # Обработка пустых значений
    pred = str(pred).strip() if pd.notna(pred) else ""
    gold = [str(g).strip() for g in gold if pd.notna(g) and str(g).strip()]
    if not pred or not gold:
        return 0.0
    
    # Вызов squad.compute для одной строки
    result = _squad_metric.compute(
        predictions=[{"id": "0", "prediction_text": pred}],
        references=[{
            "id": "0",
            "answers": {
                "text": gold,
                "answer_start": [0] * len(gold)
            }
        }]
    )
    return result["f1"]

# === 3. Metrics BERTScore  ===
def bertscore_metrics(pred: str, gold: Union[str, List[str]]) -> dict:
    if isinstance(gold, str):
        gold = [gold]
    
    pred = str(pred).strip() if pd.notna(pred) else ""
    gold = [str(g).strip() for g in gold if pd.notna(g) and str(g).strip()]
    
    if not pred or not gold:
        return {"p": 0.0, "r": 0.0, "f1": 0.0}
    
    # Считаем метрики для каждого эталона
    best_p = best_r = best_f1 = 0.0
    for ref in gold:
        P, R, F1 = score(
            cands=[pred],
            refs=[ref],
            lang="en",
            rescale_with_baseline=False,
            verbose=False
        )
        best_p = max(best_p, P.item())
        best_r = max(best_r, R.item())
        best_f1 = max(best_f1, F1.item())
    
    return {"p": best_p, "r": best_r, "f1": best_f1}

# === 4. ROUGE-L F1 ===
_rouge_metric = None

def rouge_l_f1(pred: str, gold: Union[str, List[str]]) -> float:
    """
    Вычисляет ROUGE-L F1 между предсказанием и эталоном(ами).
    Для списка эталонов возвращает максимальный результат.
    
    Args:
        pred: Предсказанный ответ
        gold: Эталонный ответ (строка) или список эталонов
    
    Returns:
        ROUGE-L F1 в диапазоне [0.0, 1.0]
    """
    _rouge_metric = rouge_scorer.RougeScorer(['rougeL'], use_stemmer=False)

    # Преобразуем эталон в список
    if isinstance(gold, str):
        gold = [gold]
    
    # Обработка пустых/некорректных значений
    pred = str(pred).strip() if pd.notna(pred) else ""
    gold = [str(g).strip() for g in gold if pd.notna(g) and str(g).strip()]
    
    if not pred or not gold:
        return 0.0
    
    # Вычисляем ROUGE-L для каждого эталона, берём максимум
    best_f1 = 0.0
    for ref in gold:
        try:
            scores = _rouge_metric.score(ref, pred)
            best_f1 = max(best_f1, scores['rougeL'].fmeasure)
        except Exception:
            continue  # пропускаем проблемные пары
    
    return best_f1

In [28]:
from tqdm import tqdm
tqdm.pandas()

In [6]:
def compute_metrics_rowwise(
    df: pd.DataFrame,
    pred_col: str = "corrected_answer",
    gold_col: str = "tasks_cleaned"
) -> pd.DataFrame:
    """
    Вычисляет метрики качества для каждой строки датафрейма.
    
    Параметры:
    - df: исходный DataFrame
    - pred_col: имя колонки с предсказанным ответом (str)
    - gold_col: имя колонки с эталонными ответами (List[str] или str)
    
    Возвращает:
    - DataFrame с добавленными колонками метрик
    """
    df = df.copy()
    
    # Character F1
    df["char_f1"] = df.progress_apply(
        lambda row: char_f1(row[pred_col], row[gold_col]),
        axis=1
    )
    
    # Token F1 (SQuAD)
    df["token_f1"] = df.progress_apply(
        lambda row: token_f1(row[pred_col], row[gold_col]),
        axis=1
    )

    df['rouge_l_f1'] = df.progress_apply(
    lambda row: rouge_l_f1(row[pred_col], row[gold_col]),
    axis=1
    )
    
    # BERTScore (P, R, F1)
    bert_results = df.progress_apply(
        lambda row: bertscore_metrics(row[pred_col], row[gold_col]),
        axis=1
    )
    df["bertscore_p"] = bert_results.apply(lambda x: x["p"])
    df["bertscore_r"] = bert_results.apply(lambda x: x["r"])
    df["bertscore_f1"] = bert_results.apply(lambda x: x["f1"])
    
    # Округление
    for col in ["char_f1", "token_f1", "bertscore_p", "bertscore_r", "bertscore_f1"]:
        df[col] = df[col].round(4)
    
    return df

# Расчет по скорректированному ответу

In [22]:
df_test = df_filtered.copy()

In [24]:
# === Запуск ===
df_result = compute_metrics_rowwise(df_test)

100%|██████████| 244/244 [00:00<00:00, 37719.67it/s]
100%|██████████| 244/244 [00:01<00:00, 150.18it/s]
100%|██████████| 244/244 [06:22<00:00,  1.57s/it]

In [25]:
df_result.head()

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new,char_f1,token_f1,bertscore_p,bertscore_r,bertscore_f1
0,000f90380d768a85e2316225854fc377c079b5c4,Full - Resolution Residual Networks for Semant...,"[Semantic_Segmentation, Real-Time_Semantic_Seg...","[Semantic Segmentation, Real-Time Semantic Seg...",To improve segmentation performance at object ...,Semantic image segmentation,"['score', 'accuracy', 'pretraine', 'geometry']","{'cosine_sim': 0.6268187761306763, 'lev_dist':...","{'cosine_sim': 0.9270111322402954, 'lev_dist': 7}",0.8966,80.0000,0.9117,0.9219,0.9167
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"[Question_Answering, Open-Domain_Question_Answ...","[Question Answering, Open-Domain Question Answ...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}",1.0000,100.0000,0.8780,0.8524,0.8641
5,01125e3c68edb420b8d884ff53fb38d9fbe4f2b8,document: Large Pose 3D Face Reconstruction fr...,[3D_Face_Reconstruction],[3D Face Reconstruction],3D facial landmark localisation,3D facial landmark localisation,"['training', 'novel', 'architecture', 'assumpt...","{'cosine_sim': 0.9436883926391602, 'lev_dist':...","{'cosine_sim': 0.9436883926391602, 'lev_dist':...",0.6038,28.5714,0.9252,0.9602,0.9424
6,0116899fce00ffa4afee08b505300bb3968faf9f,Long Text Generation via Adversarial Training ...,[Text_Generation],[Text Generation],the next word to select,the next word to select,"['game', 'training', 'discriminator']","{'cosine_sim': 0.6716794371604919, 'lev_dist':...","{'cosine_sim': 0.6716794371604919, 'lev_dist':...",0.5789,0.0000,0.8046,0.8269,0.8156
7,0171bdeb1c6e333287be655c667cfba5edb89b76,Aggregated Residual Transformations for Deep N...,[Image_Classification],[Image Classification],factors.,Object Detection,"['reduce', 'average', 'recently']","{'cosine_sim': 0.6920448541641235, 'lev_dist':...","{'cosine_sim': 0.8140521049499512, 'lev_dist':...",0.4444,0.0000,0.9139,0.9139,0.9139

In [26]:
df_result.describe()

          char_f1    token_f1  bertscore_p  bertscore_r  bertscore_f1
count  244.000000  244.000000   244.000000   244.000000    244.000000
mean     0.655493   31.084528     0.878091     0.865901      0.871336
std      0.193885   38.781684     0.049391     0.052303      0.047304
min      0.250000    0.000000     0.776400     0.757100      0.783300
25%      0.520000    0.000000     0.840550     0.824900      0.834375
50%      0.610200    0.000000     0.871650     0.854600      0.863350
75%      0.771475   66.666700     0.915225     0.904175      0.901575
max      1.000000  100.000000     1.000000     1.000000      1.000000

# Графики

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Настройка стиля
plt.style.use('seaborn-v0_8')
fig, axes = plt.subplots(2, 3, figsize=(15, 10))
fig.suptitle('Распределение метрик качества ответов', fontsize=16)

# Список метрик для отрисовки
metrics = [
    ("char_f1", "Character-level F1"),
    ("token_f1", "Token-level F1 (SQuAD)"),
    ("bertscore_p", "BERTScore Precision"),
    ("bertscore_r", "BERTScore Recall"),
    ("bertscore_f1", "BERTScore F1")
]

# Отрисовка гистограмм
for idx, (col, title) in enumerate(metrics):
    row = idx // 3
    col_idx = idx % 3
    
    # Удаляем NaN для корректной визуализации
    data = df_result[col].dropna()
    
    sns.histplot(data, kde=True, ax=axes[row, col_idx], bins=30)
    axes[row, col_idx].set_title(title)
    axes[row, col_idx].set_xlabel("Значение метрики")
    axes[row, col_idx].set_ylabel("Частота")

# Убираем пустую ячейку (если нужно)
if len(metrics) < 6:
    axes[1, 2].remove()

plt.tight_layout()
plt.show()

In [ ]:
# Только числовые колонки с метриками
metric_cols = ['char_f1', 'token_f1', 'bertscore_p', 'bertscore_r', 'bertscore_f1']
sns.pairplot(df_result[metric_cols].dropna(), diag_kind='kde')
plt.suptitle('Корреляции между метриками', y=1.02)
plt.show()

# Расчет по не скорректированному ответу

In [27]:
df_test2 = df_filtered.copy()

In [28]:
# === Запуск ===
df_result2 = compute_metrics_rowwise(df=df_test2, pred_col="first_answer")

100%|██████████| 244/244 [00:00<00:00, 40457.39it/s]
100%|██████████| 244/244 [00:01<00:00, 152.41it/s]
100%|██████████| 244/244 [06:20<00:00,  1.56s/it]

In [29]:
df_result2.describe()

          char_f1    token_f1  bertscore_p  bertscore_r  bertscore_f1
count  244.000000  244.000000   244.000000   244.000000    244.000000
mean     0.640910   25.759823     0.873883     0.858449      0.865416
std      0.177880   34.801907     0.045199     0.047714      0.042219
min      0.160000    0.000000     0.792300     0.757100      0.783300
25%      0.515650    0.000000     0.840450     0.823550      0.834375
50%      0.619250    0.000000     0.868200     0.850400      0.858300
75%      0.743225   50.000000     0.905275     0.891150      0.890650
max      1.000000  100.000000     0.980600     0.980600      0.980600

# Расчет по Qwen

In [37]:
df_res_qwen = pd.read_csv('df_res_with_qwen_answers.csv')

In [31]:
df_res_qwen = df_res_qwen[df_res_qwen['corrected_answer'] != "--None--"]

In [38]:
df_result_qwen = compute_metrics_rowwise(df=df_res_qwen, pred_col="qwen2.5-3B_answer")

100%|██████████| 306/306 [00:00<00:00, 42542.25it/s]
100%|██████████| 306/306 [00:02<00:00, 152.11it/s]
100%|██████████| 306/306 [06:32<00:00,  1.28s/it]

In [39]:
df_result_qwen.describe()

          char_f1    token_f1  bertscore_p  bertscore_r  bertscore_f1
count  306.000000  306.000000   306.000000   306.000000    306.000000
mean     0.646680   48.745580     0.860519     0.841543      0.850698
std      0.194359   37.011805     0.042929     0.034553      0.036294
min      0.074100    0.000000     0.757900     0.755400      0.766700
25%      0.506250    0.000000     0.825500     0.815175      0.825500
50%      0.640750   50.000000     0.864550     0.842000      0.853700
75%      0.825050   80.000000     0.895700     0.869700      0.876900
max      0.948700  100.000000     0.950800     0.914300      0.932200

# Расчет по RoBERTa

In [21]:
df_res_roberta = pd.read_csv('df_res_with_roberta.csv')

In [22]:
df_res_roberta =  df_res_roberta[df_res_roberta['roberta_answer'] != "Ответ не найден"]

In [23]:
df_res_roberta.shape

(63, 11)

In [24]:
df_res_roberta.head(20)

,doc_id,original_text,tasks,tasks_cleaned,first_answer,corrected_answer,keywords,metrics_orig,metrics_new,qwen2.5-3B_answer,roberta_answer
1,0012de6bec1f25599e4f02517637e531a71909b9,document: V - Net: Fully Convolutional Neural ...,['Volumetric_Medical_Image_Segmentation'],['Volumetric Medical Image Segmentation'],"classification, segmentation and object detect...",--None--,--None--,"{'cosine_sim': 0.5885287523269653, 'lev_dist':...","{'cosine_sim': 0.5885287523269653, 'lev_dist':...",Volumetric medical image segmentation,"classification, segmentation and object detection"
2,007ab5528b3bd310a80d553cccad4b78dc496b02,document: Bi - Directional Attention Flow for ...,"['Question_Answering', 'Open-Domain_Question_A...","['Question Answering', 'Open-Domain Question A...",answering the query.,question answering,"['enable', 'improvement', 'year', 'allow', 'na...","{'cosine_sim': 0.8998040556907654, 'lev_dist':...","{'cosine_sim': 0.9999996423721313, 'lev_dist': 2}",Question Answering,1 to 7
5,01125e3c68edb420b8d884ff53fb38d9fbe4f2b8,document: Large Pose 3D Face Reconstruction fr...,['3D_Face_Reconstruction'],['3D Face Reconstruction'],3D facial landmark localisation,3D facial landmark localisation,"['training', 'novel', 'architecture', 'assumpt...","{'cosine_sim': 0.9436883926391602, 'lev_dist':...","{'cosine_sim': 0.9436883926391602, 'lev_dist':...",3D facial reconstruction,3D facial landmark localisation
9,01c824989d24a8cae214c3156edd9d4492faa579,document: Stacked Generative Adversarial Netwo...,['Conditional_Image_Generation'],['Conditional Image Generation'],"Sampling. To sample images,",--None--,--None--,"{'cosine_sim': 0.6492668986320496, 'lev_dist':...","{'cosine_sim': 0.6492668986320496, 'lev_dist':...",Image generation,estimating image distribution
10,0209389b8369aaa2a08830ac3b2036d4901ba1f1,document: DensePose: Dense Human Pose Estimati...,['Pose_Estimation'],['Pose Estimation'],pose estimation,dense supervision signal.,"['discriminative', 'outperform']","{'cosine_sim': 1.0, 'lev_dist': 2}","{'cosine_sim': 0.5526493787765503, 'lev_dist':...",Dense human pose estimation,Dense Human Pose Estimation
16,02e85d62fbd8249a046d00ac10e39546511b2a51,document: Efficient Multi - Scale 3D CNN with ...,['Brain_Tumor_Segmentation'],['Brain Tumor Segmentation'],lesion segmentation,lesion segmentation,"['multi', 'devise', 'clinical', 'computational...","{'cosine_sim': 0.6405792236328125, 'lev_dist':...","{'cosine_sim': 0.6405792236328125, 'lev_dist':...",Traumatic Brain Injuries,multi - class tumor segmentation
18,0373b97580cdfd0b69f165e1a946bae62da95dce,document: Deep Residual Networks with Exponent...,['Image_Classification'],['Image Classification'],"To control the exploding gradient,",Classification Performance Fig. [reference] il...,"['nearly', 'significantly', 'huge', 'fast', 'i...","{'cosine_sim': 0.5961365103721619, 'lev_dist':...","{'cosine_sim': 0.7654635906219482, 'lev_dist':...",Test error reduction,The vanishing / exploding gradients problem im...
20,04320b6d3e6e50a5faf0e54ae2b8b8739445a026,document: Positional Encoding to Control Outpu...,['Text_Summarization'],['Text Summarization'],control the number of characters.,--None--,[],"{'cosine_sim': 0.7302284240722656, 'lev_dist':...",--None--,Headline generation task,Japanese headline generation task
37,071b16f25117fb6133480c6259227d54fc2a5ea0,document: Neural Machine Translation by Jointl...,['Machine_Translation'],['Machine Translation'],generating the target word.,generating the target word.,"['need', 'learn', 'sentence', 'concentrate']","{'cosine_sim': 0.6666461229324341, 'lev_dist':...","{'cosine_sim': 0.6666461229324341, 'lev_dist':...",English-to-French translation,English - to - French translation
41,07cca2bdd0dc2fee02889e17789748eba9d06ffa,Inferring hybrid transportation modes from spa...,['Trajectory_Prediction'],['Trajectory Prediction'],"feature extraction,",inferring the transportation mode,"['study', 'elsevier', 'daily', 'strike']","{'cosine_sim': 0.720935583114624, 'lev_dist': 13}","{'cosine_sim': 0.740982174873352, 'lev_dist': 26}",Inferring hybrid transportation modes from spa...,classification problem of GPS data into differ...
51,0a053f55804eee01f3c8b4138a1d3364d5bc45ac,document: M - Walk: Learning to Walk over Grap...,['Link_Prediction'],['Link Prediction'],search for the target node.,Three Glass Puzzle.,"['new', 'experimental', 'outperform']","{'cosine_sim': 0.8034135699272156, 'lev_dist':...","{'cosine_sim': 0.4062255024909973, 'lev_dist':...",Knowledge Base Completion,Three Glass Puzzle
54,0a3a003457f5d7758a42a0e4b7278b39a86ed0bd,document: Meta - Transfer Learning for Few - S...,"['Few-Shot_Learning', 'Few-Shot_Image_Classifi...","['Few-Shot Learning', 'Few-Shot Image Classifi...",classifier),classification,"['novel', 'efficientred', 'challenge', 'overfi...","{'cosine_sim': 0.5575096607208252, 'lev_dist':...","{'cosine_sim': 0.5141156315803528, 'lev_dist':...",Few-shot learning tasks,few - shot learning problems
61,0b5519f76fc8e31ecf9931f00184aee86694e3a4,document: Image Reconstruction with Predictive...,['Image_Super-Resolution'],['Image Super-Resolution'],non - uniform motion blur removal.,--None--,--None--,"{'cosine_sim': 0.368259072303772, 'lev_dist': 28}","{'cosine_sim': 0.368259072303772, 'lev_dist': 28}",Non-uniform motion blur removal,denoising and deconvolution
62,0b5aef2894d3248fb5ecc955d50501f0aa276036,document: Multimodal Sentiment Analysis using ...,"['Multimodal_Emotion_Recognition', 'Multimodal...","['Multimodal Emotion Recognition', 'Multimodal...",features and classification outputs.,features and classification outputs.,"['political', 'algorithm', 'tourism', 'business']","{'cosine_sim': 0.7758622169494629, 'lev_dist':...","{'cosine_sim': 0.7758622169494629, 'lev_dist':...",Multimodal sentiment analysis,sentiment classification problem
63,0b8759d61e93b809df16d9fe9010d2a2d7241c74,document: Fast and Accurate Deep Network Learn...,['Image_Classification'],['Image Classification'],push the mean activation toward zero by an app...,--None--,[],"{'cosine_sim': 0.47576403617858887, 'lev_dist'...",--None--,Classification Performance on CIFAR-100 and CI...,vanishing gradient problem
69,0ca2bd0e40a8f0a57665535ae1c31561370ad183,HIERARCHICAL MULTISCALE RECURRENT NEURAL NETWO...,['Language_Modelling'],['Language Modelling'],discover the latent hierarchical structure of ...,real - valued sequence modelling,"['difficult', 'reduce', 'slowly', 'discrepancy...","{'cosine_sim': 0.6106122732162476, 'lev_dist':...","{'cosine_sim': 0.6679608821868896, 'lev_dist':...",Character-level language modelling and handwri...,hard boundary decision
72,0d0101e65e52ae0cec38bcd13c6a9d631979c577,document: FractalNet: Ultra - Deep Neural Netw...,['Image_Classification'],['Image Classification'],compute the element - wise mean of its inputs.,compute the element - wise mean of its inputs.,"['dropout', 'nonlinearity']","{'cosine_sim': 0.7096558809280396, 'lev_dist':...","{'cosine_sim': 0.7096558809280396, 'lev_dist':...",ImageNet classification task,ImageNet deng2009imagenet classification
77,0dcde9f2c5149f0e4c806db7b4cc4915bed077da,document: Enhanced Image Classification With a...,['Image_Classification'],['Image Classification'],feature extraction,feature extraction,"['surprisingly', 'trainable', 'rapid', 'hide',...","{'cosine_sim': 0.8415639400482178, 'lev_dist':...","{'cosine_sim': 0.8415639400482178, 'lev_dist':...",Image classification,least squares optimisation problem
79,0e8753f550350e53824358ca3f0f8cfd2f2dc2f7,document: Matrix Completion on Graphs The prob...,['Collaborative_Filtering'],['Collaborative Filtering'],Matrix completion,Matrix completion,"['surprisingly', 'usually', 'movie', 'aforemen...","{'cosine_sim': 0.6429291367530823, 'lev_dist':...","{'cosine_sim': 0.6429291367530823, 'lev_dist':...",Matrix completion,convex non - smooth optimization problem
81,0ee850dd6640a96531ac5ad21da5438db04d8b3c,document: Neural Ranking Models with Weak Supe...,['Ad-Hoc_Information_Retrieval'],['Ad-Hoc Information Retrieval'],feature extraction,inference time,"['pentagon', 'width']","{'cosine_sim': 0.7652856707572937, 'lev_dist':...","{'cosine_sim': 0.7930063009262085, 'lev_dist':...",Ranking,ranking

In [53]:
df_res_roberta.isna().sum()

doc_id                 0
original_text          0
tasks                  0
tasks_cleaned          0
first_answer           0
corrected_answer       0
keywords               0
metrics_orig           0
metrics_new            0
qwen2.5-3B_answer      0
roberta_answer       191
dtype: int64

In [34]:
df_res_roberta = compute_metrics_rowwise(df=df_res_roberta, pred_col="roberta_answer")

100%|██████████| 63/63 [00:00<00:00, 26072.14it/s]
100%|██████████| 63/63 [00:01<00:00, 40.35it/s]
100%|██████████| 63/63 [01:21<00:00,  1.29s/it]

In [36]:
df_res_roberta.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63 entries, 1 to 295
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   doc_id             63 non-null     object
 1   original_text      63 non-null     object
 2   tasks              63 non-null     object
 3   tasks_cleaned      63 non-null     object
 4   first_answer       63 non-null     object
 5   corrected_answer   63 non-null     object
 6   keywords           63 non-null     object
 7   metrics_orig       63 non-null     object
 8   metrics_new        63 non-null     object
 9   qwen2.5-3B_answer  63 non-null     object
 10  roberta_answer     63 non-null     object
 11  char_f1            63 non-null     float64
 12  token_f1           63 non-null     float64
 13  bertscore_p        63 non-null     float64
 14  bertscore_r        63 non-null     float64
 15  bertscore_f1       63 non-null     float64
dtypes: float64(5), object(11)
memory usage: 8.4+ KB

In [35]:
df_res_roberta.describe()

         char_f1    token_f1  bertscore_p  bertscore_r  bertscore_f1
count  63.000000   63.000000    63.000000    63.000000     63.000000
mean    0.565062   26.272197     0.837241     0.822432      0.829516
std     0.172005   30.614662     0.036747     0.030819      0.030625
min     0.129000    0.000000     0.733600     0.765300      0.770800
25%     0.449450    0.000000     0.811200     0.795850      0.805300
50%     0.565700   22.222200     0.836200     0.818000      0.823500
75%     0.671800   42.222200     0.862900     0.839800      0.849050
max     0.935500  100.000000     0.930300     0.890200      0.892800