In [1]:
from system_check import *
CUDA_state_print_limited()

CUDA доступна: True
Количество GPU: 4

In [2]:
import torch

def get_device() -> str:
    """
    Возвращает 'cuda' если GPU доступен, иначе 'cpu'.
    """
    return "cuda:1" if torch.cuda.is_available() else "cpu"

In [3]:
device = get_device()
print(f"Используемое устройство: {device}")

Используемое устройство: cuda:1

In [4]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch, gc

# Очистка памяти от предыдущих моделей
gc.collect()
torch.cuda.empty_cache()

# Загрузка ТОЛЬКО на CPU (без accelerate/device_map)
model_id = "Qwen/Qwen2.5-3B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.pad_token = tokenizer.eos_token  # критически важно для Qwen

model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype=torch.float16,      # экономия памяти
    low_cpu_mem_usage=True,         # загрузка без переполнения ОЗУ
    trust_remote_code=False         # не требуется для Qwen2.5
).to(device)  # ← ЯВНОЕ перемещение на CPU

print("✅ Модель загружена. Память:", sum(p.numel() for p in model.parameters()) / 1e9, "B параметров")

/home/pmartynyuk/UnTIE project/untie_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.55s/it]

✅ Модель загружена. Память: 3.085938688 B параметров

In [5]:
def answer_question_qwen(
    context: str, 
    question: str, 
    max_new_tokens: int = 150,
    max_context_tokens: int = 16384  # ← НАСТРОЙКА: лимит контекста
) -> str:
    """
    Получает ответ от Qwen2.5-3B с поддержкой длинного контекста.
    
    Args:
        context: Текст для анализа (до 128K токенов)
        question: Вопрос к тексту
        max_new_tokens: Макс. длина генерируемого ответа
        max_context_tokens: Лимит токенов контекста (рекомендуется 8192–16384 для ваших данных)
    """
    # === 1. Обрезка контекста ДО формирования промпта ===
    tokens = tokenizer.encode(context, add_special_tokens=False)
    if len(tokens) > max_context_tokens:
        # Сохраняем КОНЕЦ текста (часто содержит выводы/ответы)
        tokens = tokens[-max_context_tokens:]
        context = tokenizer.decode(tokens, skip_special_tokens=True)
    
    # === 2. Формирование промпта ===
    messages = [{
        "role": "user",
        "content": (
            "Ответь строго по тексту ниже. Если информации нет — напиши 'Не указано в тексте'.\n\n"
            f"Текст:\n{context}\n\n"
            f"Вопрос: {question}"
        )
    }]
    
    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )
    
    # === 3. Токенизация с расширенным лимитом ===
    # Важно: max_length должен быть >= max_context_tokens + длина вопроса + системные токены
    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=max_context_tokens + 512  # +512 на вопрос и системные токены
    ).to(device)
    
    # === 4. Генерация ===
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.3,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id,
            use_cache=False
        )
    
    # === 5. Извлечение ответа ===
    response_tokens = outputs[0][inputs.input_ids.shape[1]:]
    response = tokenizer.decode(response_tokens, skip_special_tokens=True)
    
    return response.strip()

In [7]:
import pandas as pd
import time
from tqdm import tqdm

In [9]:
df_res = pd.read_csv('/home/pmartynyuk/UnTIE project/datasets/ruserrc_task.csv', 
                    encoding='utf-8', 
                    sep=';')
df_res

,text,Task_aspects,Task_count,text_clean
0,В рамках проекта по <Task> автоматизации раб...,['автоматизации работы с поэтическими текстами...,2,В рамках проекта по автоматизации работы с ...
1,Проблема <Task> своевременного предупреждения...,['своевременного предупреждения населения об о...,2,Проблема своевременного предупреждения насел...
2,Работа посвящена <Contrib> описанию структур...,['генотипирования вируса клещевого энцефалита ...,2,Работа посвящена описанию структуры информа...
3,Для эффективного <Task> освоения залежей угл...,['освоения залежей углеводородов'],1,Для эффективного освоения залежей углеводор...
4,При <Task> формировании единого информационно...,['формировании единого информационного простра...,1,При формировании единого информационного про...
...,...,...,...,...
163,Рассматриваются проблемы <Task> проектирован...,['проектирования интеллектуальных систем управ...,1,Рассматриваются проблемы проектирования инт...
164,"Планирование землепользования , охрана окружаю...",['поддержки принятия решений'],1,"Планирование землепользования , охрана окружаю..."
165,Во многих <Task> задачах текстовой классифик...,['задачах текстовой классификации'],1,Во многих задачах текстовой классификации ...
166,<Task> Выбор оптимального расположения логис...,['Выбор оптимального расположения логистически...,2,Выбор оптимального расположения логистическ...
167,Рассматривается задача <Task> кластеризации ...,['кластеризации интернет-ресурсов'],1,Рассматривается задача кластеризации интерн...

In [19]:
df_res = df_res.drop(columns=["qwen2.5-3B_answer", "time"])

In [20]:
# Создаём колонку для ответов, если её нет
if 'qwen2.5-3B_answer' not in df_res.columns:
    df_res['qwen2.5-3B_answer'] = pd.NA
    df_res['time'] = pd.NA

# Вопрос для всех текстов
question = "Какая задача была решена? Дай краткий ответ без объяснения"

# Прогресс-бар
pbar = tqdm(
    total=len(df_res),
    desc="Обработка текстов Qwen2.5-3B",
    unit="текст",
    ncols=80
)

# Счётчики
success_count = 0
error_count = 0

try:
    for idx in range(len(df_res)):
        # Пропускаем уже обработанные строки
        if pd.notna(df_res.loc[idx, 'qwen2.5-3B_answer']) and df_res.loc[idx, 'qwen2.5-3B_answer'] != '':
            success_count += 1
            pbar.update(1)
            continue
        
        context = df_res.loc[idx, 'text_clean']
        
        try:
            # Получаем ответ через вашу функцию
            start_time = time.time()
            answer = answer_question_qwen(
                context=context,
                question=question,
                max_new_tokens=100,        # короткий ответ как в примере
                max_context_tokens=16384   # полный контекст для ваших длинных текстов
            )
            elapsed = time.time() - start_time
            
            # Сохраняем ответ
            df_res.loc[idx, 'qwen2.5-3B_answer'] = answer
            df_res.loc[idx, 'time'] = elapsed
            success_count += 1
            
            # Обновляем прогресс-бар
            pbar.set_postfix({
                'успех': success_count,
                'ошибок': error_count,
                'время': f"{elapsed:.1f}с"
            })
            
        except Exception as e:
            error_count += 1
            error_msg = f"[ERROR] {str(e)[:60]}"
            df_res.loc[idx, 'qwen2.5-3B_answer'] = error_msg
            df_res.loc[idx, 'time'] = 0
            pbar.set_postfix({'ошибок': error_count})
            print(f"\n⚠️ Строка {idx}: {error_msg}")
        
        pbar.update(1)
        
        # Пауза для стабильности на CPU
        time.sleep(0.3)
        
        # Промежуточное сохранение каждые 10 строк
        if (idx + 1) % 10 == 0:
            df_res.to_csv('rus_df_res_with_qwen_answers.csv', index=False)
            pbar.write(f" 💾 Сохранено {idx + 1}/{len(df_res)} строк")

except KeyboardInterrupt:
    pbar.close()
    print("\n\n🛑 Обработка прервана. Сохраняем результаты...")
    df_res.to_csv('rus_df_res_with_qwen_answers.csv', index=False)
    print("✅ Промежуточные результаты сохранены в 'df_res_with_qwen_answers.csv'")
    raise

finally:
    pbar.close()

# Финальное сохранение
df_res.to_csv('rus_df_res_with_qwen_answers.csv', index=False)

# Итоговая статистика
print("\n" + "="*70)
print("✅ ОБРАБОТКА ЗАВЕРШЕНА")
print(f"   Всего строк:    {len(df_res)}")
print(f"   Успешно:        {success_count} ({success_count/len(df_res)*100:.1f}%)")
print(f"   Ошибок:         {error_count} ({error_count/len(df_res)*100:.1f}%)")
print(f"   Результаты:     df_res_with_qwen_answers.csv")
print("="*70)

# Показать примеры ответов
print("\n🔍 Примеры ответов:")
for i in range(min(5, len(df_res))):
    print(f"\nСтрока {i}:")
    print(f"   Ответ: {df_res.loc[i, 'qwen2.5-3B_answer'][:100]}...")

Обработка текстов Qwen2.5-3B:   0%|                  | 0/168 [00:00<?, ?текст/s]The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   1%| | 1/168 [00:01<02:56,  1.06s/текст, успех=1,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   1%| | 2/168 [00:04<07:32,  2.72s/текст, успех=2,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   2%| | 3/168 [00:06<06:09,  2.24s/текст, успех=3,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   2%| | 4/168 [00:08<05:32,  2.03s/текст, успех=4,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   3%| | 5/168 [00:10<05:19,  1.96s/текст, успех=5,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   4%| | 6/168 [00:12<06:06,  2.26s/текст, успех=6,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   4%| | 7/168 [00:14<05:17,  1.97s/текст, успех=7,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   5%| | 8/168 [00:17<06:13,  2.34s/текст, успех=8,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   5%| | 9/168 [00:20<06:36,  2.49s/текст, успех=9,The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   6%| | 10/168 [00:24<07:30,  2.85s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 10/168 строк

Обработка текстов Qwen2.5-3B:   7%| | 11/168 [00:26<07:09,  2.74s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   7%| | 12/168 [00:28<06:23,  2.46s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 13/168 [00:30<06:06,  2.37s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   8%| | 14/168 [00:32<05:31,  2.15s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:   9%| | 15/168 [00:35<06:10,  2.42s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  10%| | 16/168 [00:37<06:20,  2.50s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  10%| | 17/168 [00:39<06:00,  2.39s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  11%| | 18/168 [00:41<05:06,  2.04s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  11%| | 19/168 [00:43<05:30,  2.22s/текст, успех=1The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  12%| | 20/168 [00:45<05:04,  2.06s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 20/168 строк

Обработка текстов Qwen2.5-3B:  12%|▏| 21/168 [00:47<05:11,  2.12s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  13%|▏| 22/168 [00:48<04:20,  1.78s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  14%|▏| 23/168 [00:52<05:26,  2.25s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  14%|▏| 24/168 [00:53<04:39,  1.94s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  15%|▏| 25/168 [00:56<05:48,  2.44s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  15%|▏| 26/168 [01:04<09:15,  3.91s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  16%|▏| 27/168 [01:05<07:27,  3.18s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  17%|▏| 28/168 [01:08<06:49,  2.93s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  17%|▏| 29/168 [01:09<05:52,  2.53s/текст, успех=2The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  18%|▏| 30/168 [01:11<05:09,  2.25s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 30/168 строк

Обработка текстов Qwen2.5-3B:  18%|▏| 31/168 [01:14<05:32,  2.43s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  19%|▏| 32/168 [01:16<05:11,  2.29s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  20%|▏| 33/168 [01:18<05:05,  2.26s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  20%|▏| 34/168 [01:20<04:55,  2.21s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  21%|▏| 35/168 [01:21<04:30,  2.03s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  21%|▏| 36/168 [01:26<06:09,  2.80s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  22%|▏| 37/168 [01:28<05:51,  2.68s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  23%|▏| 38/168 [01:30<05:17,  2.44s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  23%|▏| 39/168 [01:32<04:35,  2.13s/текст, успех=3The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  24%|▏| 40/168 [01:35<05:01,  2.36s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 40/168 строк

Обработка текстов Qwen2.5-3B:  24%|▏| 41/168 [01:35<03:52,  1.83s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  25%|▎| 42/168 [01:42<06:49,  3.25s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  26%|▎| 43/168 [01:44<05:56,  2.85s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  26%|▎| 44/168 [01:46<05:17,  2.56s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  27%|▎| 45/168 [01:47<04:39,  2.27s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  27%|▎| 46/168 [01:49<04:16,  2.11s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  28%|▎| 47/168 [01:51<03:58,  1.97s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  29%|▎| 48/168 [01:52<03:51,  1.93s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  29%|▎| 49/168 [01:57<05:13,  2.64s/текст, успех=4The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  30%|▎| 50/168 [02:00<05:33,  2.83s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 50/168 строк

Обработка текстов Qwen2.5-3B:  30%|▎| 51/168 [02:01<04:18,  2.21s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  31%|▎| 52/168 [02:02<03:53,  2.02s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  32%|▎| 53/168 [02:05<04:07,  2.15s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  32%|▎| 54/168 [02:06<03:22,  1.78s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  33%|▎| 55/168 [02:10<04:34,  2.43s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  33%|▎| 56/168 [02:12<04:36,  2.47s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  34%|▎| 57/168 [02:14<04:27,  2.41s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  35%|▎| 58/168 [02:16<04:03,  2.21s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  35%|▎| 59/168 [02:17<03:23,  1.87s/текст, успех=5The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  36%|▎| 60/168 [02:19<03:14,  1.80s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 60/168 строк

Обработка текстов Qwen2.5-3B:  36%|▎| 61/168 [02:21<03:21,  1.88s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  37%|▎| 62/168 [02:22<02:55,  1.65s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  38%|▍| 63/168 [02:25<03:17,  1.88s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  38%|▍| 64/168 [02:26<03:04,  1.78s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  39%|▍| 65/168 [02:30<03:55,  2.29s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  39%|▍| 66/168 [02:31<03:26,  2.02s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  40%|▍| 67/168 [02:33<03:17,  1.96s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  40%|▍| 68/168 [02:35<03:14,  1.95s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  41%|▍| 69/168 [02:36<03:06,  1.88s/текст, успех=6The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  42%|▍| 70/168 [02:39<03:08,  1.93s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 70/168 строк

Обработка текстов Qwen2.5-3B:  42%|▍| 71/168 [02:40<03:00,  1.86s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  43%|▍| 72/168 [02:41<02:42,  1.70s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  43%|▍| 73/168 [02:45<03:39,  2.31s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  44%|▍| 74/168 [02:46<02:59,  1.91s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  45%|▍| 75/168 [02:49<03:23,  2.19s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  45%|▍| 76/168 [02:50<02:55,  1.91s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  46%|▍| 77/168 [02:52<02:35,  1.71s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  46%|▍| 78/168 [02:54<02:59,  2.00s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  47%|▍| 79/168 [02:56<02:54,  1.96s/текст, успех=7The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  48%|▍| 80/168 [02:57<02:25,  1.65s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 80/168 строк

Обработка текстов Qwen2.5-3B:  48%|▍| 81/168 [03:01<03:26,  2.37s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  49%|▍| 82/168 [03:02<02:47,  1.95s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  49%|▍| 83/168 [03:03<02:20,  1.65s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  50%|▌| 84/168 [03:08<03:37,  2.59s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  51%|▌| 85/168 [03:09<03:00,  2.17s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  51%|▌| 86/168 [03:12<03:10,  2.33s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  52%|▌| 87/168 [03:14<03:09,  2.34s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  52%|▌| 88/168 [03:16<02:51,  2.14s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  53%|▌| 89/168 [03:17<02:33,  1.95s/текст, успех=8The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  54%|▌| 90/168 [03:19<02:28,  1.91s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 90/168 строк

Обработка текстов Qwen2.5-3B:  54%|▌| 91/168 [03:21<02:21,  1.84s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  55%|▌| 92/168 [03:22<02:09,  1.70s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  55%|▌| 93/168 [03:25<02:27,  1.97s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  56%|▌| 94/168 [03:26<02:07,  1.72s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  57%|▌| 95/168 [03:27<01:46,  1.47s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  57%|▌| 96/168 [03:28<01:46,  1.47s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 97/168 [03:33<02:46,  2.34s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  58%|▌| 98/168 [03:34<02:34,  2.20s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  59%|▌| 99/168 [03:36<02:14,  1.95s/текст, успех=9The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  60%|▌| 100/168 [03:38<02:07,  1.87s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 100/168 строк

Обработка текстов Qwen2.5-3B:  60%|▌| 101/168 [03:42<02:57,  2.65s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  61%|▌| 102/168 [03:45<03:07,  2.84s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  61%|▌| 103/168 [03:47<02:44,  2.54s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  62%|▌| 104/168 [03:55<04:17,  4.02s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  62%|▋| 105/168 [03:59<04:26,  4.23s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  63%|▋| 106/168 [04:04<04:36,  4.47s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  64%|▋| 107/168 [04:06<03:46,  3.71s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  64%|▋| 108/168 [04:07<02:53,  2.89s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  65%|▋| 109/168 [04:09<02:37,  2.67s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  65%|▋| 110/168 [04:11<02:11,  2.27s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 110/168 строк

Обработка текстов Qwen2.5-3B:  66%|▋| 111/168 [04:14<02:25,  2.55s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  67%|▋| 112/168 [04:16<02:10,  2.33s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  67%|▋| 113/168 [04:18<02:04,  2.26s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  68%|▋| 114/168 [04:24<03:08,  3.49s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  68%|▋| 115/168 [04:27<03:01,  3.43s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  69%|▋| 116/168 [04:28<02:20,  2.70s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  70%|▋| 117/168 [04:31<02:12,  2.60s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  70%|▋| 118/168 [04:33<02:00,  2.41s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  71%|▋| 119/168 [04:37<02:24,  2.94s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  71%|▋| 120/168 [04:39<01:58,  2.47s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 120/168 строк

Обработка текстов Qwen2.5-3B:  72%|▋| 121/168 [04:41<02:03,  2.63s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  73%|▋| 122/168 [04:44<01:59,  2.59s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  73%|▋| 123/168 [04:48<02:13,  2.98s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  74%|▋| 124/168 [04:51<02:13,  3.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  74%|▋| 125/168 [04:54<02:13,  3.10s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  75%|▊| 126/168 [04:56<01:58,  2.82s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  76%|▊| 127/168 [04:58<01:37,  2.37s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  76%|▊| 128/168 [05:02<02:00,  3.01s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  77%|▊| 129/168 [05:04<01:43,  2.65s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  77%|▊| 130/168 [05:06<01:25,  2.26s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 130/168 строк

Обработка текстов Qwen2.5-3B:  78%|▊| 131/168 [05:09<01:35,  2.57s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  79%|▊| 132/168 [05:12<01:43,  2.89s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  79%|▊| 133/168 [05:15<01:39,  2.83s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  80%|▊| 134/168 [05:17<01:26,  2.53s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  80%|▊| 135/168 [05:18<01:11,  2.16s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  81%|▊| 136/168 [05:19<00:59,  1.87s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  82%|▊| 137/168 [05:21<00:53,  1.73s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  82%|▊| 138/168 [05:25<01:13,  2.46s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  83%|▊| 139/168 [05:28<01:18,  2.70s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  83%|▊| 140/168 [05:35<01:49,  3.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 140/168 строк

Обработка текстов Qwen2.5-3B:  84%|▊| 141/168 [05:37<01:29,  3.32s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  85%|▊| 142/168 [05:39<01:18,  3.02s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  85%|▊| 143/168 [05:42<01:14,  2.97s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  86%|▊| 144/168 [05:46<01:21,  3.39s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  86%|▊| 145/168 [05:48<01:10,  3.04s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  87%|▊| 146/168 [05:51<01:04,  2.91s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  88%|▉| 147/168 [05:53<00:57,  2.74s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  88%|▉| 148/168 [05:55<00:49,  2.50s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  89%|▉| 149/168 [05:59<00:55,  2.92s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  89%|▉| 150/168 [06:01<00:46,  2.57s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 150/168 строк

Обработка текстов Qwen2.5-3B:  90%|▉| 151/168 [06:04<00:43,  2.56s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  90%|▉| 152/168 [06:06<00:38,  2.44s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  91%|▉| 153/168 [06:07<00:33,  2.24s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  92%|▉| 154/168 [06:10<00:31,  2.24s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  92%|▉| 155/168 [06:11<00:24,  1.87s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  93%|▉| 156/168 [06:12<00:21,  1.82s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  93%|▉| 157/168 [06:16<00:24,  2.25s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  94%|▉| 158/168 [06:20<00:28,  2.82s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  95%|▉| 159/168 [06:21<00:21,  2.44s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  95%|▉| 160/168 [06:30<00:34,  4.29s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

 💾 Сохранено 160/168 строк

Обработка текстов Qwen2.5-3B:  96%|▉| 161/168 [06:33<00:27,  3.89s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  96%|▉| 162/168 [06:39<00:26,  4.43s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  97%|▉| 163/168 [06:42<00:21,  4.26s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  98%|▉| 164/168 [06:49<00:19,  4.90s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  98%|▉| 165/168 [06:51<00:12,  4.21s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  99%|▉| 166/168 [06:53<00:06,  3.28s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B:  99%|▉| 167/168 [06:55<00:02,  2.89s/текст, успех=The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
Обработка текстов Qwen2.5-3B: 100%|█| 168/168 [06:57<00:00,  2.48s/текст, успех=

======================================================================
✅ ОБРАБОТКА ЗАВЕРШЕНА
   Всего строк:    168
   Успешно:        168 (100.0%)
   Ошибок:         0 (0.0%)
   Результаты:     df_res_with_qwen_answers.csv
======================================================================

🔍 Примеры ответов:

Строка 0:
   Ответ: Упрощение исследований поэтических текстов...

Строка 1:
   Ответ: Объединение существующих реализаций алгоритмов для численного моделирования цунами в одну систему, к...

Строка 2:
   Ответ: Генотипирования вируса клещевого энцефалита (ВКЭ)....

Строка 3:
   Ответ: Решена задача геонавигации нефтегазовых скважин с горизонтальным завершением....

Строка 4:
   Ответ: Предложенный подход к формализации структуры ЕИП предприятия-разработчика МЭС....

In [21]:
df_res_qwen = pd.read_csv('/home/pmartynyuk/UnTIE project/scripts/rus_df_res_with_qwen_answers.csv',
                            encoding='utf-8', sep=',')
df_res_qwen.head()

,text,Task_aspects,Task_count,text_clean,qwen2.5-3B_answer,time
0,В рамках проекта по <Task> автоматизации раб...,['автоматизации работы с поэтическими текстами...,2,В рамках проекта по автоматизации работы с ...,Упрощение исследований поэтических текстов,1.056020
1,Проблема <Task> своевременного предупреждения...,['своевременного предупреждения населения об о...,2,Проблема своевременного предупреждения насел...,Объединение существующих реализаций алгоритмов...,3.587075
2,Работа посвящена <Contrib> описанию структур...,['генотипирования вируса клещевого энцефалита ...,2,Работа посвящена описанию структуры информа...,Генотипирования вируса клещевого энцефалита (В...,1.354576
3,Для эффективного <Task> освоения залежей угл...,['освоения залежей углеводородов'],1,Для эффективного освоения залежей углеводор...,Решена задача геонавигации нефтегазовых скважи...,1.397231
4,При <Task> формировании единого информационно...,['формировании единого информационного простра...,1,При формировании единого информационного про...,Предложенный подход к формализации структуры Е...,1.547555

In [22]:
from transformers import *
roberta_qa_dir = "/home/pmartynyuk/UnTIE project/scripts/models_processing/models/rubert_ru_qa_model"

model = AutoModelForQuestionAnswering.from_pretrained(roberta_qa_dir, output_attentions=True).to(device)
concrete_tokenizer = AutoTokenizer.from_pretrained(roberta_qa_dir)

loading configuration file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/rubert_ru_qa_model/config.json
Model config XLMRobertaConfig {
  "architectures": [
    "XLMRobertaForQuestionAnswering"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "language": "english",
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "xlm-roberta",
  "name": "XLMRoberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_attentions": true,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.53.3",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

loading weights file /home/pmartynyuk/UnTIE project/scripts/models_processing/models/rubert_ru_qa_model/model.safetensors
All model checkpoint weights were used when initializing XLMRobertaForQuestionAnswering.

All the weights of XLMRobertaForQuestionAnswering were initialized from the model checkpoint at /home/pmartynyuk/UnTIE project/scripts/models_processing/models/rubert_ru_qa_model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use XLMRobertaForQuestionAnswering for predictions without further training.
loading file sentencepiece.bpe.model
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading file chat_template.jinja

In [23]:
from transformers import pipeline
import torch

# Загрузка модели (весит всего ~50 МБ)
qa_pipeline = pipeline(
    "question-answering",
    model=model,
    tokenizer=concrete_tokenizer,
    device=1 if torch.cuda.is_available() else -1,  # -1 = CPU
    max_seq_len=512,      # максимальная длина чанка
    doc_stride=128,       # перекрытие между чанками (рекомендуется 128)
    max_answer_len=100    # макс. длина извлекаемого ответа
)

Device set to use cuda:1

In [28]:
idx = 0

context = str(df_res_qwen.loc[idx, 'text_clean'])
question = "Какая задача была поставлена?"

In [29]:
result = qa_pipeline(
            question=question,
            context=context,
            handle_impossible_answer=True,
            max_seq_len=512,
            doc_stride=128
        )
result

{'score': 0.2592003643512726,
 'start': 895,
 'end': 937,
 'answer': ' призвана решать информационная система  ,'}

In [34]:
def answer_question_rubert(context: str, question: str) -> str:
    """
    Надёжная функция для rubert QA. Всегда возвращает непустую строку.
    """
    # === 1. Валидация входных данных ===
    if not isinstance(context, str) or not context.strip():
        return "ERROR: пустой или некорректный текст"
    if not isinstance(question, str) or not question.strip():
        return "ERROR: пустой вопрос"
    
    # === 2. Вызов модели ===
    try:
        result = qa_pipeline(
            question=question,
            context=context,
            handle_impossible_answer=True,
            max_seq_len=512,
            doc_stride=128
        )
    except Exception as e:
        return f"ERROR: pipeline exception ({type(e).__name__})"
    
    # === 3. Обработка результата ===
    try:
        # Список ответов (длинный текст)
        if isinstance(result, list) and result:
            # Фильтруем только словари с ответами
            valid_answers = [
                r for r in result 
                if isinstance(r, dict) 
                and 'answer' in r 
                and isinstance(r['answer'], str)
                # and len(r['answer'].strip()) >= 2  # минимум 2 символа
                # and r.get('score', 0) > 0.001       # любой ненулевой скор
            ]
            
            if valid_answers:
                # Берём ответ с максимальным скором
                best = max(valid_answers, key=lambda x: x.get('score', 0))
                answer = best['answer'].strip()
                # Ограничиваем длину ответа
                return answer[:150] if answer else "Ответ не найден"
            else:
                return "Ответ не найден"
        
        # Один ответ (короткий текст)
        elif isinstance(result, dict) and 'answer' in result:
            answer = str(result.get('answer', '')).strip()
            if len(answer) >= 2 and result.get('score', 0) > 0.001:
                return answer[:150]
            else:
                return "Ответ не найден"
        
        # Любой другой случай
        else:
            return "Ответ не найден"
    
    except Exception as e:
        return f"ERROR: processing exception ({type(e).__name__})"

In [33]:
df_res_rubert = df_res.drop(columns=["qwen2.5-3B_answer", "time"])

In [38]:
import pandas as pd
import time
from tqdm import tqdm

# === КРИТИЧЕСКИ ВАЖНО: Очистка колонки от существующих NaN ===
if 'rubert_answer' in df_res_rubert.columns:
    df_res_rubert['rubert_answer'] = df_res_rubert['rubert_answer'].fillna("").astype(str)
else:
    df_res_rubert['rubert_answer'] = ""

# Убедимся, что original_text не содержит NaN
df_res_rubert['text_clean'] = df_res_rubert['text_clean'].fillna("")

question = "Which task was solved?"

pbar = tqdm(total=len(df_res_rubert), desc="rubert QA", unit="текст", ncols=80)

for idx in range(len(df_res_rubert)):
    # Пропускаем уже обработанные (не "Ответ не найден" и не ошибки)
    current = str(df_res_rubert.loc[idx, 'rubert_answer']).strip()
    if current and not current.startswith(("Ответ не найден", "ERROR")):
        pbar.update(1)
        continue
    
    context = str(df_res_rubert.loc[idx, 'text_clean'])
    
    # Получаем ответ (гарантированно строка)
    answer = answer_question_rubert(context, question)
    
    # Принудительно сохраняем как строку
    df_res_rubert.loc[idx, 'rubert_answer'] = str(answer)
    
    pbar.update(1)
    
    # Промежуточное сохранение
    if (idx + 1) % 10 == 0:
        df_res_rubert.to_csv('df_res_rubert.csv', index=False)
        pbar.set_postfix({"последний": answer[:30]})

pbar.close()
df_res_rubert.to_csv('df_res_rubert.csv', index=False)

# Финальная статистика
total = len(df_res_rubert)
not_found = df_res_rubert['rubert_answer'].str.contains("Ответ не найден", na=False).sum()
errors = df_res_rubert['rubert_answer'].str.startswith("ERROR", na=False).sum()
valid = total - not_found - errors
nan_check = df_res_rubert['rubert_answer'].isna().sum()

print("\n" + "="*70)
print("✅ ОБРАБОТКА ЗАВЕРШЕНА")
print(f"   Всего строк:          {total}")
print(f"   Валидных ответов:     {valid} ({valid/total*100:.1f}%)")
print(f"   'Ответ не найден':    {not_found} ({not_found/total*100:.1f}%)")
print(f"   Ошибок:               {errors} ({errors/total*100:.1f}%)")
print(f"   NaN в колонке:        {nan_check} ← ДОЛЖНО БЫТЬ 0")
print("="*70)

# Примеры хороших ответов
print("\n🔍 Примеры найденных ответов:")
valid_answers = df_res_rubert[~df_res_rubert['rubert_answer'].str.contains("Ответ не найден|ERROR", na=False)]
for i, (_, row) in enumerate(valid_answers.head(5).iterrows()):
    print(f"{i+1}. {row['rubert_answer']}")

rubert QA:   2%|▋                            | 4/168 [00:00<00:04, 34.76текст/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
rubert QA: 100%|█| 168/168 [00:05<00:00, 31.95текст/s, последний=Показаны недост

======================================================================
✅ ОБРАБОТКА ЗАВЕРШЕНА
   Всего строк:          168
   Валидных ответов:     168 (100.0%)
   'Ответ не найден':    0 (0.0%)
   Ошибок:               0 (0.0%)
   NaN в колонке:        0 ← ДОЛЖНО БЫТЬ 0
======================================================================

🔍 Примеры найденных ответов:
1. призвана решать информационная система  ,
2. своевременного предупреждения населения об опасности цунами
3. генотипирования вируса клещевого энцефалита (ВКЭ)  .
4. геонавигация скважины со сложной траекторией выполняется по геофизическим данным в реальном масштабе времени. Представленная работа посвящена   разраб
5. с использованием метода матрицы структуры проекта,

In [40]:
df_res_rubert = pd.read_csv('/home/pmartynyuk/UnTIE project/scripts/df_res_rubert.csv',
                            encoding='utf-8', sep=',')
df_res_rubert.head()

,text,Task_aspects,Task_count,text_clean,rubert_answer
0,В рамках проекта по <Task> автоматизации раб...,['автоматизации работы с поэтическими текстами...,2,В рамках проекта по автоматизации работы с ...,"призвана решать информационная система ,"
1,Проблема <Task> своевременного предупреждения...,['своевременного предупреждения населения об о...,2,Проблема своевременного предупреждения насел...,своевременного предупреждения населения об опа...
2,Работа посвящена <Contrib> описанию структур...,['генотипирования вируса клещевого энцефалита ...,2,Работа посвящена описанию структуры информа...,генотипирования вируса клещевого энцефалита (В...
3,Для эффективного <Task> освоения залежей угл...,['освоения залежей углеводородов'],1,Для эффективного освоения залежей углеводор...,геонавигация скважины со сложной траекторией в...
4,При <Task> формировании единого информационно...,['формировании единого информационного простра...,1,При формировании единого информационного про...,с использованием метода матрицы структуры прое...